/**
 * Green-words ledger access for the mini-games.
 *
 * `public/green_words.json` (generated by scripts/build_word_ledger.py,
 * never hand-edited) is the real curriculum word list: ~1,700 decodable
 * words tagged with their focus sound and journey level. Milo's Cannon
 * already ran on it; this module gives every other game the same depth
 * instead of the ~120-word hand-typed WORD_BANK in soundGameWords.ts.
 *
 * `useGameBank(level)` returns a grapheme → words map with two guarantees:
 *  - every key is a sound taught at or below the child's level, so
 *    distractor graphemes drawn from the bank's keys are always sounds
 *    the child has met (the old bank padded from ALL graphemes — a
 *    Level 1 child could be offered "igh" as a wrong answer);
 *  - every word sits at or below the child's level, so nothing on screen
 *    is undecodable for them.
 *
 * The curated WORD_BANK stays merged in as both fallback (fetch failed —
 * the games must never be wordless) and seasoning (its words are the
 * short, picturable ones).
 */
import { useEffect, useMemo, useState } from 'react';
import type { JourneyLevel } from '@/lib/levels8';
import { JOURNEY_LEVELS } from '@/lib/levels8';
import { setLedgerUnits, WORD_BANK } from '@/lib/soundGameWords';

export interface LedgerWord {
  word: string;
  /** The focus grapheme, matching JOURNEY_LEVELS gpcs naming ("ay", "a-e"). */
  sound: string;
  level: number;
  units: string[];
}

let ledgerPromise: Promise<LedgerWord[]> | null = null;
let ledgerCache: LedgerWord[] | null = null;

export function loadLedger(): Promise<LedgerWord[]> {
  if (!ledgerPromise) {
    ledgerPromise = fetch('/green_words.json')
      .then(r => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((d: { words?: LedgerWord[] }) => {
        ledgerCache = d.words ?? [];
        indexLedger(ledgerCache);
        return ledgerCache;
      })
      .catch(() => {
        ledgerCache = [];
        return ledgerCache;
      });
  }
  return ledgerPromise;
}

// ── phonics-truth index ─────────────────────────────────────────────
// word → the sounds it GENUINELY contains, per the ledger's grapheme
// breakdown. Two corrections on top of raw units:
//  - split digraphs are stored decomposed ("cake" → c,a,e,k), so the
//    magic-e letters must not be credited as short /a/ and /e/ — the two
//    component letters of the word's split-digraph focus are removed;
//  - the word's focus `sound` is always credited as itself.
let unitIndex: Record<string, string[]> | null = null;

function indexLedger(words: LedgerWord[]) {
  const idx: Record<string, string[]> = {};
  for (const w of words) {
    let units = [...w.units];
    if (w.sound.includes('-') && !w.sound.startsWith('-')) {
      for (const part of w.sound.split('-')) {
        const i = units.indexOf(part);
        if (i >= 0) units.splice(i, 1);
      }
      units = [...units, w.sound];
    }
    if (!units.includes(w.sound)) units.push(w.sound);
    idx[w.word] = units;
  }
  unitIndex = idx;
  setLedgerUnits(idx);
}

/** The sounds a ledger word genuinely contains (null if unknown word or
 *  the ledger hasn't loaded yet). */
export function unitsOf(word: string): string[] | null {
  return unitIndex?.[word] ?? null;
}

// ── word-audio manifest ─────────────────────────────────────────────
// The games speak with the pre-recorded George (ElevenLabs) MP3s; browser
// TTS mangles short words ("jet" that doesn't sound like jet). The
// manifest lists which recordings exist so the banks can prefer words the
// child will hear in the RIGHT voice. Regenerate with
// scripts/generate_game_word_audio.mjs + py -c "...words_manifest.json".
let audioKeys: Set<string> | null = null;
let audioPromise: Promise<void> | null = null;

export function loadAudioManifest(): Promise<void> {
  if (!audioPromise) {
    audioPromise = fetch('/sounds/words_manifest.json')
      .then(r => (r.ok ? r.json() : []))
      .then((keys: string[]) => { audioKeys = new Set(keys); })
      .catch(() => { audioKeys = new Set(); });
  }
  return audioPromise;
}

export function hasAudio(word: string): boolean {
  if (!audioKeys) return true; // manifest unknown — don't starve the banks
  return audioKeys.has(word.toLowerCase().replace(/[^a-z]/g, ''));
}

/** All graphemes taught at or below this journey level. */
export function taughtGraphemes(level: JourneyLevel): Set<string> {
  const s = new Set<string>();
  for (const l of JOURNEY_LEVELS) {
    if (l.level > level.level) break;
    for (const g of l.gpcs) s.add(g);
  }
  return s;
}

/** Words longer than this overflow tiles and bubbles; the ledger goes up
 *  to 12 letters and the longest curated word is 11. */
const MAX_WORD_LEN = 11;

function buildBank(level: JourneyLevel, ledger: LedgerWord[] | null): Record<string, string[]> {
  const taught = taughtGraphemes(level);
  const bank: Record<string, Set<string>> = {};
  const add = (key: string, word: string) => {
    if (word.length > MAX_WORD_LEN) return;
    (bank[key] ??= new Set()).add(word);
  };

  // Curated words first — restricted to taught sounds.
  for (const [g, words] of Object.entries(WORD_BANK)) {
    if (!taught.has(g)) continue;
    for (const w of words) add(g, w);
  }

  // Ledger words at or below the level. Suffix sounds are keyed "-ous" in
  // the gpcs but may appear bare in the ledger; try both spellings.
  if (ledger) {
    for (const w of ledger) {
      if (w.level > level.level) continue;
      const key = taught.has(w.sound) ? w.sound : taught.has(`-${w.sound}`) ? `-${w.sound}` : null;
      if (key) add(key, w.word);
    }
  }

  return Object.fromEntries(Object.entries(bank).map(([g, set]) => {
    const all = [...set];
    // Prefer words with a George recording — never let browser TTS be the
    // voice of a game when a recorded word will do.
    const voiced = all.filter(hasAudio);
    return [g, voiced.length >= 2 ? voiced : all];
  }));
}

/**
 * The grapheme → words bank for this level. Returns the curated-only bank
 * immediately, upgraded in place to the full ledger bank once the fetch
 * lands (instant on every mount after the first).
 */
export function useGameBank(level: JourneyLevel): Record<string, string[]> {
  const [ledger, setLedger] = useState<LedgerWord[] | null>(ledgerCache);
  const [audioReady, setAudioReady] = useState(false);
  useEffect(() => {
    let live = true;
    if (!ledgerCache) loadLedger().then(l => { if (live) setLedger(l); });
    loadAudioManifest().then(() => { if (live) setAudioReady(true); });
    return () => { live = false; };
  }, []);
  return useMemo(() => buildBank(level, ledger), [level, ledger, audioReady]);
}
