/**
 * Interactive book data for Level 3 — "New Spellings"
 * Focus: split vowel digraphs (a-e, i-e, o-e, u-e) and vowel digraphs (ea, oi, aw, ai, oa, ie)
 *
 * L3.1 "The Big Bike Race"   — a-e, i-e
 * L3.2 "Lost at the Night Market" — o-e, u-e
 * L3.3 "Reach for the Treat" — ea, ie
 * L3.4 "Draw It Again"       — oi, aw
 * L3.5 "The Boat with the Red Sail" — ai, oa
 */

import type { InteractivePage, StoryWord } from './interactiveBookData';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function w(display: string, word: string, phonemes: string[]): StoryWord {
  return { display, word, phonemes };
}

function tricky(display: string, word: string): StoryWord {
  return { display, word, phonemes: [], isTricky: true };
}

// Level 3 allSounds grid (all L1 + L2 + L3 sounds)
const L3_ALL_SOUNDS = [
  's/ss', 'a', 't', 'p', 'i', 'n', 'm', 'd', 'g', 'o',
  'c/k/ck', 'e', 'u', 'r', 'h', 'b', 'f/ff',
  'l/ll', 'j', 'v', 'w', 'x', 'y', 'z/zz',
  'qu', 'ch', 'sh', 'th', 'ng', 'nk',
  'ee', 'oo', 'ar', 'or', 'ur', 'ow', 'oi',
  'ea', 'a-e', 'i-e', 'o-e', 'u-e', 'aw', 'ai', 'oa', 'ie',
];

// ═══════════════════════════════════════════════════════════════════════════════
// L3.1 — "The Big Bike Race"
// Focus sounds: a-e, i-e
// ═══════════════════════════════════════════════════════════════════════════════

export const BOOK_L3_1_PAGES: InteractivePage[] = [
  // ── COVER ──
  {
    type: 'cover',
    title: 'The Big Bike Race',
    subtitle: 'Level 3 · New Spellings',
    imageUrl: '/illustrations/3_1/cover.png',
  },

  // ── SOUND GRID ──
  {
    type: 'sound_grid',
    focusSounds: ['a-e', 'i-e'],
    allSounds: L3_ALL_SOUNDS,
  },

  // ── VOCAB PREVIEW ──
  {
    type: 'vocab_preview',
    words: [
      w('ride', 'ride', ['r','i-e','d']),
      w('bike', 'bike', ['b','i-e','k']),
      w('gate', 'gate', ['g','a-e','t']),
      w('lake', 'lake', ['l','a-e','k']),
      w('made', 'made', ['m','a-e','d']),
      w('brave', 'brave', ['b','r','a-e','v']),
      w('pine', 'pine', ['p','i-e','n']),
      w('wide', 'wide', ['w','i-e','d']),
      w('line', 'line', ['l','i-e','n']),
    ],
  },

  // ── STORY PAGES ──
  // Page 1: "Bikes line up at the gate..."
    { type: 'story', sentences: ['Bikes line up at the arch.', 'It is time for the race to start!', 'I stand with my bike on the line.'],
    words: [
      cvc('Bikes', 'bikes'),
      cvc('line', 'line'),
      cvc('up', 'up'),
      cvc('at', 'at'),
      tricky('the', 'the'),
      pw('arch.', 'arch', ['ar', 'ch']),
      cvc('It', 'it'),
      tricky('is', 'is'),
      cvc('time', 'time'),
      pw('for', 'for', ['f', 'or']),
      tricky('the', 'the'),
      cvc('race', 'race'),
      tricky('to', 'to'),
      pw('start!', 'start', ['s', 't', 'ar', 't']),
      tricky('I', 'I'),
      cvc('stand', 'stand'),
      pw('with', 'with', ['w', 'i', 'th']),
      cvc('my', 'my'),
      cvc('bike', 'bike'),
      cvc('on', 'on'),
      tricky('the', 'the'),
      cvc('line.', 'line'),
    ],
    imageUrl: '/illustrations/3_1/page1.png', audioUrl: '/sounds/sentences/L3_1_p1.mp3' },
  { type: 'story', sentences: ['‘Ride to the lake and back!’ the man said.', 'Can I win?', 'I grip my bike tight.'],
    words: [
      cvc('‘Ride', 'ride'),
      tricky('to', 'to'),
      tricky('the', 'the'),
      cvc('lake', 'lake'),
      cvc('and', 'and'),
      pw('back!’', 'back', ['b', 'a', 'ck']),
      tricky('the', 'the'),
      cvc('man', 'man'),
      pw('said.', 'said', ['s', 'ai', 'd']),
      cvc('Can', 'can'),
      tricky('I', 'I'),
      cvc('win?', 'win'),
      tricky('I', 'I'),
      cvc('grip', 'grip'),
      cvc('my', 'my'),
      cvc('bike', 'bike'),
      pw('tight.', 'tight', ['t', 'igh', 't']),
    ],
    imageUrl: '/illustrations/3_1/page2.png', audioUrl: '/sounds/sentences/L3_1_p2.mp3' },
  { type: 'story', sentences: ['Off I go!', 'Past a tall pine tree.', 'Past a wide stone arch.', 'I ride fast in the sun.'],
    words: [
      pw('Off', 'off', ['o', 'ff']),
      tricky('I', 'I'),
      tricky('go!', 'go'),
      cvc('Past', 'past'),
      tricky('a', 'a'),
      pw('tall', 'tall', ['t', 'a', 'll']),
      cvc('pine', 'pine'),
      pw('tree.', 'tree', ['t', 'r', 'ee']),
      cvc('Past', 'past'),
      tricky('a', 'a'),
      cvc('wide', 'wide'),
      cvc('stone', 'stone'),
      pw('arch.', 'arch', ['ar', 'ch']),
      tricky('I', 'I'),
      cvc('ride', 'ride'),
      cvc('fast', 'fast'),
      cvc('in', 'in'),
      tricky('the', 'the'),
      cvc('sun.', 'sun'),
    ],
    imageUrl: '/illustrations/3_1/page3.png', audioUrl: '/sounds/sentences/L3_1_p3.mp3' },
  { type: 'story', sentences: ['Look out!', 'Stones on the track.', 'A bike slides and a girl falls off.', 'She gave me a brave smile.'],
    words: [
      pw('Look', 'look', ['l', 'oo', 'k']),
      pw('out!', 'out', ['ou', 't']),
      cvc('Stones', 'stones'),
      cvc('on', 'on'),
      tricky('the', 'the'),
      pw('track.', 'track', ['t', 'r', 'a', 'ck']),
      tricky('A', 'a'),
      cvc('bike', 'bike'),
      cvc('slides', 'slides'),
      cvc('and', 'and'),
      tricky('a', 'a'),
      pw('girl', 'girl', ['g', 'ir', 'l']),
      pw('falls', 'falls', ['f', 'a', 'll', 's']),
      pw('off.', 'off', ['o', 'ff']),
      tricky('She', 'she'),
      cvc('gave', 'gave'),
      tricky('me', 'me'),
      tricky('a', 'a'),
      cvc('brave', 'brave'),
      cvc('smile.', 'smile'),
    ],
    imageUrl: '/illustrations/3_1/page4.png', audioUrl: '/sounds/sentences/L3_1_p4.mp3' },
  { type: 'story', sentences: ['I can see the lake!', 'It shines in the sun.', 'I ride past it and turn back.'],
    words: [
      tricky('I', 'I'),
      cvc('can', 'can'),
      pw('see', 'see', ['s', 'ee']),
      tricky('the', 'the'),
      cvc('lake!', 'lake'),
      cvc('It', 'it'),
      pw('shines', 'shines', ['sh', 'i', 'n', 'e', 's']),
      cvc('in', 'in'),
      tricky('the', 'the'),
      cvc('sun.', 'sun'),
      tricky('I', 'I'),
      cvc('ride', 'ride'),
      cvc('past', 'past'),
      cvc('it', 'it'),
      cvc('and', 'and'),
      cvc('turn', 'turn'),
      pw('back.', 'back', ['b', 'a', 'ck']),
    ],
    imageUrl: '/illustrations/3_1/page5.png', audioUrl: '/sounds/sentences/L3_1_p5.mp3' },
  { type: 'story', sentences: ['Can I make it back in time?', 'I ride and ride.', 'I must not be late!'],
    words: [
      cvc('Can', 'can'),
      tricky('I', 'I'),
      cvc('make', 'make'),
      cvc('it', 'it'),
      pw('back', 'back', ['b', 'a', 'ck']),
      cvc('in', 'in'),
      cvc('time?', 'time'),
      tricky('I', 'I'),
      cvc('ride', 'ride'),
      cvc('and', 'and'),
      cvc('ride.', 'ride'),
      tricky('I', 'I'),
      cvc('must', 'must'),
      cvc('not', 'not'),
      tricky('be', 'be'),
      cvc('late!', 'late'),
    ],
    imageUrl: '/illustrations/3_1/page6.png', audioUrl: '/sounds/sentences/L3_1_p6.mp3' },
  { type: 'story', sentences: ['I am past the line!', 'I made it!', 'I slide off my bike with a wide grin.'],
    words: [
      tricky('I', 'I'),
      cvc('am', 'am'),
      cvc('past', 'past'),
      tricky('the', 'the'),
      cvc('line!', 'line'),
      tricky('I', 'I'),
      cvc('made', 'made'),
      cvc('it!', 'it'),
      tricky('I', 'I'),
      cvc('slide', 'slide'),
      pw('off', 'off', ['o', 'ff']),
      cvc('my', 'my'),
      cvc('bike', 'bike'),
      pw('with', 'with', ['w', 'i', 'th']),
      tricky('a', 'a'),
      cvc('wide', 'wide'),
      cvc('grin.', 'grin'),
    ],
    imageUrl: '/illustrations/3_1/page7.png', audioUrl: '/sounds/sentences/L3_1_p7.mp3' },
  { type: 'story', sentences: ['A prize!', 'I am on the top step!', 'I smile and wave at my mates.', 'What a good day!'],
    words: [
      tricky('A', 'a'),
      cvc('prize!', 'prize'),
      tricky('I', 'I'),
      cvc('am', 'am'),
      cvc('on', 'on'),
      tricky('the', 'the'),
      cvc('top', 'top'),
      cvc('step!', 'step'),
      tricky('I', 'I'),
      cvc('smile', 'smile'),
      cvc('and', 'and'),
      cvc('wave', 'wave'),
      cvc('at', 'at'),
      cvc('my', 'my'),
      cvc('mates.', 'mates'),
      pw('What', 'what', ['wh', 'a', 't']),
      tricky('a', 'a'),
      pw('good', 'good', ['g', 'oo', 'd']),
      pw('day!', 'day', ['d', 'ay']),
    ],
    imageUrl: '/illustrations/3_1/page8.png', audioUrl: '/sounds/sentences/L3_1_p8.mp3' },

  // ── QUIZ ──
  {
    type: 'quiz',
    questions: [
      { question: 'Where did they ride to?',
        options: [{ label: 'the lake', isCorrect: true }, { label: 'the shops', isCorrect: false }, { label: 'the park', isCorrect: false }] },
      { question: 'What happened on the track?',
        options: [{ label: 'a girl fell off', isCorrect: true }, { label: 'it rained', isCorrect: false }, { label: 'a dog ran past', isCorrect: false }] },
      { question: 'What happened at the end?',
        options: [{ label: 'he got on the top step', isCorrect: true }, { label: 'he fell off', isCorrect: false }, { label: 'he came last', isCorrect: false }] },
    ],
  },

  // ── SOUND SPOTLIGHTS ──
  { type: 'sound_spotlight', sound: 'a-e', items: [
    { word: 'cake', imageUrl: '/images/words/cake.png', focusIndex: 1 },
    { word: 'gate', imageUrl: '/images/words/gate.png', focusIndex: 1 },
    { word: 'lake', imageUrl: '/images/words/lake.png', focusIndex: 1 },
    { word: 'name', imageUrl: '/images/words/name.png', focusIndex: 1 }] },
  { type: 'sound_spotlight', sound: 'i-e', items: [
    { word: 'bike', imageUrl: '/images/words/bike.png', focusIndex: 1 },
    { word: 'ride', imageUrl: '/images/words/ride.png', focusIndex: 1 },
    { word: 'pine', imageUrl: '/images/words/pine.png', focusIndex: 1 },
    { word: 'smile', imageUrl: '/images/words/smile.png', focusIndex: 2 }] },

  // ── WORD READING ──
  { type: 'word_reading', words: [
    w('bike', 'bike', ['b','i-e','k']), w('gate', 'gate', ['g','a-e','t']),
    w('ride', 'ride', ['r','i-e','d']), w('lake', 'lake', ['l','a-e','k']),
    w('made', 'made', ['m','a-e','d']), w('line', 'line', ['l','i-e','n'])] },

  // ── TRICKY WORDS ──
  { type: 'tricky_words', words: [
    tricky('the', 'the'), tricky('said', 'said'), tricky('some', 'some'),
    w('like', 'like', ['l','i-e','k']), tricky('what', 'what'), tricky('all', 'all')] },

  // ── SPELLING ──
  { type: 'spelling', words: [
    { word: 'bike', imageUrl: '/images/words/bike.png', letters: ['b','i','k','e'] },
    { word: 'gate', imageUrl: '/images/words/gate.png', letters: ['g','a','t','e'] },
    { word: 'ride', imageUrl: '/images/words/ride.png', letters: ['r','i','d','e'] },
    { word: 'lake', imageUrl: '/images/words/lake.png', letters: ['l','a','k','e'] }] },

  // ── NONSENSE WORDS ──
  { type: 'nonsense_words', words: [
    w('dake', 'dake', ['d','a-e','k']), w('fipe', 'fipe', ['f','i-e','p']),
    w('grine', 'grine', ['g','r','i-e','n']), w('blate', 'blate', ['b','l','a-e','t']),
    w('snide', 'snide', ['s','n','i-e','d']), w('prame', 'prame', ['p','r','a-e','m']),
    w('trike', 'trike', ['t','r','i-e','k']), w('glane', 'glane', ['g','l','a-e','n'])] },

  // ── WRITING PRACTICE ──
  { type: 'writing_practice', letters: ['a-e', 'i-e', 'a', 'i'] },

  // ── STORY ORDERING ──
  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/3_1/page1.png', label: 'Bikes line up at the gate.', correctIndex: 0 },
    { imageUrl: '/illustrations/3_1/page2.png', label: 'Ride to the lake!', correctIndex: 1 },
    { imageUrl: '/illustrations/3_1/page3.png', label: 'Past a pine tree.', correctIndex: 2 },
    { imageUrl: '/illustrations/3_1/page4.png', label: 'A girl falls off!', correctIndex: 3 },
    { imageUrl: '/illustrations/3_1/page5.png', label: 'I can see the lake!', correctIndex: 4 },
    { imageUrl: '/illustrations/3_1/page6.png', label: 'Can I make it?', correctIndex: 5 },
    { imageUrl: '/illustrations/3_1/page7.png', label: 'I made it!', correctIndex: 6 },
    { imageUrl: '/illustrations/3_1/page8.png', label: 'A prize!', correctIndex: 7 }] },

  // ── DRAWING ──
  { type: 'drawing', prompt: 'Draw Your Favourite Part' },

  // ── CERTIFICATE ──
  { type: 'certificate', bookTitle: 'The Big Bike Race' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// L3.2 — "Lost at the Night Market"
// Focus sounds: o-e, u-e
// ═══════════════════════════════════════════════════════════════════════════════

export const BOOK_L3_2_PAGES: InteractivePage[] = [
  {
    type: 'cover',
    title: 'Lost at the Night Market',
    subtitle: 'Level 3 · New Spellings',
    imageUrl: '/illustrations/3_2/cover.png',
  },
  {
    type: 'sound_grid',
    focusSounds: ['o-e', 'u-e'],
    allSounds: L3_ALL_SOUNDS,
  },
  {
    type: 'vocab_preview',
    words: [
      w('close', 'close', ['c','l','o-e','s']),
      w('spoke', 'spoke', ['s','p','o-e','k']),
      w('huge', 'huge', ['h','u-e','j']),
      w('stone', 'stone', ['s','t','o-e','n']),
      w('home', 'home', ['h','o-e','m']),
      w('froze', 'froze', ['f','r','o-e','z']),
      w('bright', 'bright', ['b','r','igh','t']),
      w('noodle', 'noodle', ['n','oo','d','l']),
    ],
  },

  // Page 1
    { type: 'story', sentences: ['Mum and I went to the night market.', 'It was huge!', '‘Stay close to me,’ Mum spoke.', 'And I did.'],
    words: [
      cvc('Mum', 'mum'),
      cvc('and', 'and'),
      tricky('I', 'I'),
      cvc('went', 'went'),
      tricky('to', 'to'),
      tricky('the', 'the'),
      pw('night', 'night', ['n', 'igh', 't']),
      pw('market.', 'market', ['m', 'ar', 'k', 'e', 't']),
      cvc('It', 'it'),
      cvc('was', 'was'),
      cvc('huge!', 'huge'),
      pw('‘Stay', 'stay', ['s', 't', 'ay']),
      cvc('close', 'close'),
      tricky('to', 'to'),
      tricky('me,’', 'me'),
      cvc('Mum', 'mum'),
      cvc('spoke.', 'spoke'),
      cvc('And', 'and'),
      tricky('I', 'I'),
      cvc('did.', 'did'),
    ],
    imageUrl: '/illustrations/3_2/page1.png', audioUrl: '/sounds/sentences/L3_2_p1.mp3' },
  { type: 'story', sentences: ['We see cute stone models on a stand.', 'We see bright noodle pots.', 'The food smelt so good!'],
    words: [
      tricky('We', 'we'),
      pw('see', 'see', ['s', 'ee']),
      cvc('cute', 'cute'),
      cvc('stone', 'stone'),
      cvc('models', 'models'),
      cvc('on', 'on'),
      tricky('a', 'a'),
      cvc('stand.', 'stand'),
      tricky('We', 'we'),
      pw('see', 'see', ['s', 'ee']),
      pw('bright', 'bright', ['b', 'r', 'igh', 't']),
      pw('noodle', 'noodle', ['n', 'oo', 'd', 'l', 'e']),
      cvc('pots.', 'pots'),
      tricky('The', 'the'),
      pw('food', 'food', ['f', 'oo', 'd']),
      cvc('smelt', 'smelt'),
      cvc('so', 'so'),
      pw('good!', 'good', ['g', 'oo', 'd']),
    ],
    imageUrl: '/illustrations/3_2/page2.png', audioUrl: '/sounds/sentences/L3_2_p2.mp3' },
  { type: 'story', sentences: ['Then a man bumped me!', 'I spun round and round.', 'I can\'t see Mum!', 'I froze.'],
    words: [
      pw('Then', 'then', ['th', 'e', 'n']),
      tricky('a', 'a'),
      cvc('man', 'man'),
      pw('bumped', 'bumped', ['b', 'u', 'm', 'p', 'ed']),
      tricky('me!', 'me'),
      tricky('I', 'I'),
      cvc('spun', 'spun'),
      pw('round', 'round', ['r', 'ou', 'n', 'd']),
      cvc('and', 'and'),
      pw('round.', 'round', ['r', 'ou', 'n', 'd']),
      tricky('I', 'I'),
      cvc('can\'t', 'cant'),
      pw('see', 'see', ['s', 'ee']),
      cvc('Mum!', 'mum'),
      tricky('I', 'I'),
      cvc('froze.', 'froze'),
    ],
    imageUrl: '/illustrations/3_2/page3.png', audioUrl: '/sounds/sentences/L3_2_p3.mp3' },
  { type: 'story', sentences: ['It was dark and loud.', 'I felt so small.', '‘Mum!’ I shout.', 'But Mum is not there.'],
    words: [
      cvc('It', 'it'),
      cvc('was', 'was'),
      pw('dark', 'dark', ['d', 'ar', 'k']),
      cvc('and', 'and'),
      pw('loud.', 'loud', ['l', 'ou', 'd']),
      tricky('I', 'I'),
      cvc('felt', 'felt'),
      cvc('so', 'so'),
      pw('small.', 'small', ['s', 'm', 'a', 'll']),
      cvc('‘Mum!’', 'mum'),
      tricky('I', 'I'),
      pw('shout.', 'shout', ['sh', 'ou', 't']),
      cvc('But', 'but'),
      cvc('Mum', 'mum'),
      tricky('is', 'is'),
      cvc('not', 'not'),
      pw('there.', 'there', ['th', 'e', 'r', 'e']),
    ],
    imageUrl: '/illustrations/3_2/page4.png', audioUrl: '/sounds/sentences/L3_2_p4.mp3' },
  { type: 'story', sentences: ['Then I see the cute stone models!', 'We went past those!', 'Mum must be close!'],
    words: [
      pw('Then', 'then', ['th', 'e', 'n']),
      tricky('I', 'I'),
      pw('see', 'see', ['s', 'ee']),
      tricky('the', 'the'),
      cvc('cute', 'cute'),
      cvc('stone', 'stone'),
      cvc('models!', 'models'),
      tricky('We', 'we'),
      cvc('went', 'went'),
      cvc('past', 'past'),
      pw('those!', 'those', ['th', 'o', 's', 'e']),
      cvc('Mum', 'mum'),
      cvc('must', 'must'),
      tricky('be', 'be'),
      cvc('close!', 'close'),
    ],
    imageUrl: '/illustrations/3_2/page5.png', audioUrl: '/sounds/sentences/L3_2_p5.mp3' },
  { type: 'story', sentences: ['I run past the bright lights.', 'I run past the noodle stand.', 'Then… I see Mum!'],
    words: [
      tricky('I', 'I'),
      cvc('run', 'run'),
      cvc('past', 'past'),
      tricky('the', 'the'),
      pw('bright', 'bright', ['b', 'r', 'igh', 't']),
      pw('lights.', 'lights', ['l', 'igh', 't', 's']),
      tricky('I', 'I'),
      cvc('run', 'run'),
      cvc('past', 'past'),
      tricky('the', 'the'),
      pw('noodle', 'noodle', ['n', 'oo', 'd', 'l', 'e']),
      cvc('stand.', 'stand'),
      pw('Then…', 'then', ['th', 'e', 'n']),
      tricky('I', 'I'),
      pw('see', 'see', ['s', 'ee']),
      cvc('Mum!', 'mum'),
    ],
    imageUrl: '/illustrations/3_2/page6.png', audioUrl: '/sounds/sentences/L3_2_p6.mp3' },
  { type: 'story', sentences: ['Mum gave me a huge tight hug.', '‘You are safe!’ she spoke.', 'I did not let go.'],
    words: [
      cvc('Mum', 'mum'),
      cvc('gave', 'gave'),
      tricky('me', 'me'),
      tricky('a', 'a'),
      cvc('huge', 'huge'),
      pw('tight', 'tight', ['t', 'igh', 't']),
      cvc('hug.', 'hug'),
      pw('‘You', 'you', ['y', 'ou']),
      pw('are', 'are', ['are']),
      cvc('safe!’', 'safe'),
      tricky('she', 'she'),
      cvc('spoke.', 'spoke'),
      tricky('I', 'I'),
      cvc('did', 'did'),
      cvc('not', 'not'),
      cvc('let', 'let'),
      tricky('go.', 'go'),
    ],
    imageUrl: '/illustrations/3_2/page7.png', audioUrl: '/sounds/sentences/L3_2_p7.mp3' },
  { type: 'story', sentences: ['We sat close and ate hot noodles in the moonlight.', '‘Stay close to me!’ spoke Mum.', 'I gave a huge grin.', 'Home time!'],
    words: [
      tricky('We', 'we'),
      cvc('sat', 'sat'),
      cvc('close', 'close'),
      cvc('and', 'and'),
      cvc('ate', 'ate'),
      cvc('hot', 'hot'),
      pw('noodles', 'noodles', ['n', 'oo', 'd', 'l', 'e', 's']),
      cvc('in', 'in'),
      tricky('the', 'the'),
      pw('moonlight.', 'moonlight', ['m', 'oo', 'n', 'l', 'igh', 't']),
      pw('‘Stay', 'stay', ['s', 't', 'ay']),
      cvc('close', 'close'),
      tricky('to', 'to'),
      tricky('me!’', 'me'),
      cvc('spoke', 'spoke'),
      cvc('Mum.', 'mum'),
      tricky('I', 'I'),
      cvc('gave', 'gave'),
      tricky('a', 'a'),
      cvc('huge', 'huge'),
      cvc('grin.', 'grin'),
      cvc('Home', 'home'),
      cvc('time!', 'time'),
    ],
    imageUrl: '/illustrations/3_2/page8.png', audioUrl: '/sounds/sentences/L3_2_p8.mp3' },

  // ── QUIZ ──
  {
    type: 'quiz',
    questions: [
      { question: 'What did the girl see on the stall?',
        options: [{ label: 'stone models', isCorrect: true }, { label: 'toy cars', isCorrect: false }, { label: 'hats', isCorrect: false }] },
      { question: 'How did the girl find Mum?',
        options: [{ label: 'she remembered the elephant stall', isCorrect: true }, { label: 'a man helped', isCorrect: false }, { label: 'Mum called out', isCorrect: false }] },
      { question: 'What did they eat at the end?',
        options: [{ label: 'noodles', isCorrect: true }, { label: 'rice', isCorrect: false }, { label: 'cake', isCorrect: false }] },
    ],
  },

  { type: 'sound_spotlight', sound: 'o-e', items: [
    { word: 'stone', imageUrl: '/images/words/stone.png', focusIndex: 2 },
    { word: 'spoke', imageUrl: '/images/words/spoke.png', focusIndex: 2 },
    { word: 'home', imageUrl: '/images/words/home.png', focusIndex: 1 },
    { word: 'close', imageUrl: '/images/words/close.png', focusIndex: 2 }] },
  { type: 'sound_spotlight', sound: 'u-e', items: [
    { word: 'huge', imageUrl: '/images/words/huge.png', focusIndex: 1 },
    { word: 'cute', imageUrl: '/images/words/cute.png', focusIndex: 1 },
    { word: 'rule', imageUrl: '/images/words/rule.png', focusIndex: 1 },
    { word: 'rude', imageUrl: '/images/words/rude.png', focusIndex: 1 }] },

  { type: 'word_reading', words: [
    w('close', 'close', ['c','l','o-e','s']), w('spoke', 'spoke', ['s','p','o-e','k']),
    w('huge', 'huge', ['h','u-e','j']), w('stone', 'stone', ['s','t','o-e','n']),
    w('cute', 'cute', ['c','u-e','t']), w('home', 'home', ['h','o-e','m'])] },

  { type: 'tricky_words', words: [
    tricky('I', 'I'), tricky('the', 'the'), tricky('you', 'you'),
    tricky('she', 'she'), tricky('we', 'we'), tricky('elephant', 'elephant')] },

  { type: 'spelling', words: [
    { word: 'close', imageUrl: '/images/words/close.png', letters: ['c','l','o','s','e'] },
    { word: 'spoke', imageUrl: '/images/words/spoke.png', letters: ['s','p','o','k','e'] },
    { word: 'huge', imageUrl: '/images/words/huge.png', letters: ['h','u','g','e'] },
    { word: 'stone', imageUrl: '/images/words/stone.png', letters: ['s','t','o','n','e'] }] },

  { type: 'nonsense_words', words: [
    w('blone', 'blone', ['b','l','o-e','n']), w('brude', 'brude', ['b','r','u-e','d']),
    w('snoke', 'snoke', ['s','n','o-e','k']), w('plune', 'plune', ['p','l','u-e','n']),
    w('frope', 'frope', ['f','r','o-e','p']), w('smude', 'smude', ['s','m','u-e','d']),
    w('stobe', 'stobe', ['s','t','o-e','b']), w('trupe', 'trupe', ['t','r','u-e','p'])] },

  { type: 'writing_practice', letters: ['o-e', 'u-e', 'o', 'u'] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/3_2/page1.png', label: 'Mum and I at the market.', correctIndex: 0 },
    { imageUrl: '/illustrations/3_2/page2.png', label: 'Stone elephants on a stall!', correctIndex: 1 },
    { imageUrl: '/illustrations/3_2/page3.png', label: 'A man bumped me! Lost!', correctIndex: 2 },
    { imageUrl: '/illustrations/3_2/page4.png', label: 'Dark and loud. Mum!', correctIndex: 3 },
    { imageUrl: '/illustrations/3_2/page5.png', label: 'The elephants! I remember!', correctIndex: 4 },
    { imageUrl: '/illustrations/3_2/page6.png', label: 'I see Mum!', correctIndex: 5 },
    { imageUrl: '/illustrations/3_2/page7.png', label: 'A huge tight hug.', correctIndex: 6 },
    { imageUrl: '/illustrations/3_2/page8.png', label: 'Noodles in the moonlight.', correctIndex: 7 }] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'Lost at the Night Market' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// L3.3 — "Reach for the Treat!"
// Focus sounds: ea, ie — Helping your community, Accra Ghana
// ═══════════════════════════════════════════════════════════════════════════════

export const BOOK_L3_3_PAGES: InteractivePage[] = [
  { type: 'cover', title: 'Reach for the Treat!', subtitle: 'Level 3 · New Spellings', imageUrl: '/illustrations/3_3/cover.png' },
  { type: 'sound_grid', focusSounds: ['ea', 'ie'], allSounds: L3_ALL_SOUNDS },

  { type: 'vocab_preview', words: [
    w('reach', 'reach', ['r','ea','ch']), w('clean', 'clean', ['c','l','ea','n']),
    w('team', 'team', ['t','ea','m']), w('each', 'each', ['ea','ch']),
    w('treat', 'treat', ['t','r','ea','t']), w('feast', 'feast', ['f','ea','s','t']),
    w('tried', 'tried', ['t','r','ie','d']), w('cried', 'cried', ['c','r','ie','d']),
    w('spied', 'spied', ['s','p','ie','d']), w('dream', 'dream', ['d','r','ea','m']),
    w('neat', 'neat', ['n','ea','t']), w('beam', 'beam', ['b','ea','m']),
  ]},

  // Page 1 — girl sees Nana tired at her gate
    { type: 'story', sentences: ['Nana sits by her gate.', 'She looks so tired.', '"I need to clean," she said.', '"But it is too much."'],
    words: [
      cvc('Nana', 'nana'),
      cvc('sits', 'sits'),
      cvc('by', 'by'),
      cvc('her', 'her'),
      cvc('gate.', 'gate'),
      tricky('She', 'she'),
      pw('looks', 'looks', ['l', 'oo', 'k', 's']),
      cvc('so', 'so'),
      pw('tired.', 'tired', ['t', 'ire', 'd']),
      tricky('"I', 'I'),
      pw('need', 'need', ['n', 'ee', 'd']),
      tricky('to', 'to'),
      pw('clean,"', 'clean', ['c', 'l', 'ea', 'n']),
      tricky('she', 'she'),
      pw('said.', 'said', ['s', 'ai', 'd']),
      cvc('"But', 'but'),
      cvc('it', 'it'),
      tricky('is', 'is'),
      pw('too', 'too', ['t', 'oo']),
      pw('much."', 'much', ['m', 'u', 'ch']),
    ],
    imageUrl: '/illustrations/3_3/page1.png', audioUrl: '/sounds/sentences/L3_3_p1.mp3' },
  { type: 'story', sentences: ['I kneel by each plant pot and clean the leaves.', '"Let me help, Nana!" I said.', 'But this is too much for just me.'],
    words: [
      tricky('I', 'I'),
      pw('kneel', 'kneel', ['kn', 'ee', 'l']),
      cvc('by', 'by'),
      pw('each', 'each', ['ea', 'ch']),
      cvc('plant', 'plant'),
      cvc('pot', 'pot'),
      cvc('and', 'and'),
      pw('clean', 'clean', ['c', 'l', 'ea', 'n']),
      tricky('the', 'the'),
      pw('leaves.', 'leaves', ['l', 'ea', 'v', 'e', 's']),
      cvc('"Let', 'let'),
      tricky('me', 'me'),
      cvc('help,', 'help'),
      cvc('Nana!"', 'nana'),
      tricky('I', 'I'),
      pw('said.', 'said', ['s', 'ai', 'd']),
      cvc('But', 'but'),
      pw('this', 'this', ['th', 'i', 's']),
      tricky('is', 'is'),
      pw('too', 'too', ['t', 'oo']),
      pw('much', 'much', ['m', 'u', 'ch']),
      pw('for', 'for', ['f', 'or']),
      cvc('just', 'just'),
      tricky('me.', 'me'),
    ],
    imageUrl: '/illustrations/3_3/page2.png', audioUrl: '/sounds/sentences/L3_3_p2.mp3' },
  { type: 'story', sentences: ['I need my best mate!', 'I run and find him.', '"Please, can you help?" I cried.', '"We need to be a team!"'],
    words: [
      tricky('I', 'I'),
      pw('need', 'need', ['n', 'ee', 'd']),
      cvc('my', 'my'),
      cvc('best', 'best'),
      cvc('mate!', 'mate'),
      tricky('I', 'I'),
      cvc('run', 'run'),
      cvc('and', 'and'),
      cvc('find', 'find'),
      cvc('him.', 'him'),
      pw('"Please,', 'please', ['p', 'l', 'ea', 's', 'e']),
      cvc('can', 'can'),
      pw('you', 'you', ['y', 'ou']),
      cvc('help?"', 'help'),
      tricky('I', 'I'),
      pw('cried.', 'cried', ['c', 'r', 'ie', 'd']),
      tricky('"We', 'we'),
      pw('need', 'need', ['n', 'ee', 'd']),
      tricky('to', 'to'),
      tricky('be', 'be'),
      tricky('a', 'a'),
      pw('team!"', 'team', ['t', 'ea', 'm']),
    ],
    imageUrl: '/illustrations/3_3/page3.png', audioUrl: '/sounds/sentences/L3_3_p3.mp3' },
  { type: 'story', sentences: ['We each grab a cloth.', 'We clean the step and sweep the yard.', 'Leaves fly!'],
    words: [
      tricky('We', 'we'),
      pw('each', 'each', ['ea', 'ch']),
      cvc('grab', 'grab'),
      tricky('a', 'a'),
      pw('cloth.', 'cloth', ['c', 'l', 'o', 'th']),
      tricky('We', 'we'),
      pw('clean', 'clean', ['c', 'l', 'ea', 'n']),
      tricky('the', 'the'),
      cvc('step', 'step'),
      cvc('and', 'and'),
      pw('sweep', 'sweep', ['s', 'w', 'ee', 'p']),
      tricky('the', 'the'),
      pw('yard.', 'yard', ['y', 'ar', 'd']),
      pw('Leaves', 'leaves', ['l', 'ea', 'v', 'e', 's']),
      cvc('fly!', 'fly'),
    ],
    imageUrl: '/illustrations/3_3/page4.png', audioUrl: '/sounds/sentences/L3_3_p4.mp3' },
  { type: 'story', sentences: ['I stand on a stool.', 'He holds it.', 'I reach up and grab each tin from the shelf.', '"I got them!"'],
    words: [
      tricky('I', 'I'),
      cvc('stand', 'stand'),
      cvc('on', 'on'),
      tricky('a', 'a'),
      pw('stool.', 'stool', ['s', 't', 'oo', 'l']),
      tricky('He', 'he'),
      cvc('holds', 'holds'),
      cvc('it.', 'it'),
      tricky('I', 'I'),
      pw('reach', 'reach', ['r', 'ea', 'ch']),
      cvc('up', 'up'),
      cvc('and', 'and'),
      cvc('grab', 'grab'),
      pw('each', 'each', ['ea', 'ch']),
      cvc('tin', 'tin'),
      cvc('from', 'from'),
      tricky('the', 'the'),
      pw('shelf.', 'shelf', ['sh', 'e', 'l', 'f']),
      tricky('"I', 'I'),
      cvc('got', 'got'),
      pw('them!"', 'them', ['th', 'e', 'm']),
    ],
    imageUrl: '/illustrations/3_3/page5.png', audioUrl: '/sounds/sentences/L3_3_p5.mp3' },
  { type: 'story', sentences: ['We take the tins out to the yard.', 'We clean each one and line them up neat.', 'Nana peeks out.', '"What a dream team!" she cried.'],
    words: [
      tricky('We', 'we'),
      cvc('take', 'take'),
      tricky('the', 'the'),
      cvc('tins', 'tins'),
      pw('out', 'out', ['ou', 't']),
      tricky('to', 'to'),
      tricky('the', 'the'),
      pw('yard.', 'yard', ['y', 'ar', 'd']),
      tricky('We', 'we'),
      pw('clean', 'clean', ['c', 'l', 'ea', 'n']),
      pw('each', 'each', ['ea', 'ch']),
      cvc('one', 'one'),
      cvc('and', 'and'),
      cvc('line', 'line'),
      pw('them', 'them', ['th', 'e', 'm']),
      cvc('up', 'up'),
      pw('neat.', 'neat', ['n', 'ea', 't']),
      cvc('Nana', 'nana'),
      pw('peeks', 'peeks', ['p', 'ee', 'k', 's']),
      pw('out.', 'out', ['ou', 't']),
      pw('"What', 'what', ['wh', 'a', 't']),
      tricky('a', 'a'),
      pw('dream', 'dream', ['d', 'r', 'ea', 'm']),
      pw('team!"', 'team', ['t', 'ea', 'm']),
      tricky('she', 'she'),
      pw('cried.', 'cried', ['c', 'r', 'ie', 'd']),
    ],
    imageUrl: '/illustrations/3_3/page6.png', audioUrl: '/sounds/sentences/L3_3_p6.mp3' },
  { type: 'story', sentences: ['Then we run to the shop.', 'We get beans and rice and sweet plantain for Nana.', 'What a treat!'],
    words: [
      pw('Then', 'then', ['th', 'e', 'n']),
      tricky('we', 'we'),
      cvc('run', 'run'),
      tricky('to', 'to'),
      tricky('the', 'the'),
      pw('shop.', 'shop', ['sh', 'o', 'p']),
      tricky('We', 'we'),
      cvc('get', 'get'),
      pw('beans', 'beans', ['b', 'ea', 'n', 's']),
      cvc('and', 'and'),
      cvc('rice', 'rice'),
      cvc('and', 'and'),
      pw('sweet', 'sweet', ['s', 'w', 'ee', 't']),
      pw('plantain', 'plantain', ['p', 'l', 'a', 'n', 't', 'ai', 'n']),
      pw('for', 'for', ['f', 'or']),
      cvc('Nana.', 'nana'),
      pw('What', 'what', ['wh', 'a', 't']),
      tricky('a', 'a'),
      pw('treat!', 'treat', ['t', 'r', 'ea', 't']),
    ],
    imageUrl: '/illustrations/3_3/page7.png', audioUrl: '/sounds/sentences/L3_3_p7.mp3' },
  { type: 'story', sentences: ['Nana grins and grins.', 'She brings us each a big feast — beans and rice with fried plantain!', 'We cheer: "Thank you, Nana!"'],
    words: [
      cvc('Nana', 'nana'),
      cvc('grins', 'grins'),
      cvc('and', 'and'),
      cvc('grins.', 'grins'),
      tricky('She', 'she'),
      pw('brings', 'brings', ['b', 'r', 'i', 'ng', 's']),
      cvc('us', 'us'),
      pw('each', 'each', ['ea', 'ch']),
      tricky('a', 'a'),
      cvc('big', 'big'),
      pw('feast', 'feast', ['f', 'ea', 's', 't']),
      tricky('—', '—'),
      pw('beans', 'beans', ['b', 'ea', 'n', 's']),
      cvc('and', 'and'),
      cvc('rice', 'rice'),
      pw('with', 'with', ['w', 'i', 'th']),
      pw('fried', 'fried', ['f', 'r', 'ie', 'd']),
      pw('plantain!', 'plantain', ['p', 'l', 'a', 'n', 't', 'ai', 'n']),
      tricky('We', 'we'),
      pw('cheer:', 'cheer', ['ch', 'ee', 'r']),
      pw('"Thank', 'thank', ['th', 'a', 'nk']),
      pw('you,', 'you', ['y', 'ou']),
      cvc('Nana!"', 'nana'),
    ],
    imageUrl: '/illustrations/3_3/page8.png', audioUrl: '/sounds/sentences/L3_3_p8.mp3' },

  // ── QUIZ ──
  { type: 'quiz', questions: [
    { question: 'What did Nana need help with?',
      options: [{ label: 'cleaning her shelf', isCorrect: true }, { label: 'cooking food', isCorrect: false }, { label: 'finding her cat', isCorrect: false }] },
    { question: 'How did the children reach the shelf?',
      options: [{ label: 'stood on a stool', isCorrect: true }, { label: 'climbed a tree', isCorrect: false }, { label: 'used a ladder', isCorrect: false }] },
    { question: 'What treat did Nana give them?',
      options: [{ label: 'beans and rice with fried plantain', isCorrect: true }, { label: 'a mango', isCorrect: false }, { label: 'a cake', isCorrect: false }] },
  ]},

  // ── SOUND SPOTLIGHTS ──
  { type: 'sound_spotlight', sound: 'ea', items: [
    { word: 'reach', imageUrl: '/images/words/reach.png', focusIndex: 1 },
    { word: 'clean', imageUrl: '/images/words/clean.png', focusIndex: 2 },
    { word: 'treat', imageUrl: '/images/words/treat.png', focusIndex: 2 },
    { word: 'team', imageUrl: '/images/words/team.png', focusIndex: 1 }] },
  { type: 'sound_spotlight', sound: 'ie', items: [
    { word: 'tried', imageUrl: '/images/words/tried.png', focusIndex: 2 },
    { word: 'cried', imageUrl: '/images/words/cried.png', focusIndex: 2 },
    { word: 'fried', imageUrl: '/images/words/fried.png', focusIndex: 2 },
    { word: 'dried', imageUrl: '/images/words/dried.png', focusIndex: 2 }] },

  // ── WORD READING ──
  { type: 'word_reading', words: [
    w('reach', 'reach', ['r','ea','ch']), w('clean', 'clean', ['c','l','ea','n']),
    w('team', 'team', ['t','ea','m']), w('treat', 'treat', ['t','r','ea','t']),
    w('tried', 'tried', ['t','r','ie','d']), w('cried', 'cried', ['c','r','ie','d'])] },

  // ── TRICKY WORDS ──
  { type: 'tricky_words', words: [
    tricky('she', 'she'), tricky('said', 'said'), tricky('I', 'I'),
    tricky('the', 'the'), tricky('to', 'to'), tricky('my', 'my')] },

  // ── SPELLING ──
  { type: 'spelling', words: [
    { word: 'reach', imageUrl: '/images/words/reach.png', letters: ['r','ea','ch'] },
    { word: 'clean', imageUrl: '/images/words/clean.png', letters: ['c','l','ea','n'] },
    { word: 'team', imageUrl: '/images/words/team.png', letters: ['t','ea','m'] },
    { word: 'treat', imageUrl: '/images/words/treat.png', letters: ['t','r','ea','t'] }] },

  // ── ALIEN WORDS ──
  { type: 'nonsense_words', words: [
    w('blea', 'blea', ['b','l','ea']), w('smea', 'smea', ['s','m','ea']),
    w('trea', 'trea', ['t','r','ea']), w('plean', 'plean', ['p','l','ea','n']),
    w('spie', 'spie', ['s','p','ie']), w('flie', 'flie', ['f','l','ie']),
    w('drie', 'drie', ['d','r','ie']), w('gried', 'gried', ['g','r','ie','d']),
    w('sneat', 'sneat', ['s','n','ea','t']), w('cleam', 'cleam', ['c','l','ea','m']),
    w('breap', 'breap', ['b','r','ea','p']), w('stie', 'stie', ['s','t','ie'])] },

  { type: 'writing_practice', letters: ['ea', 'ie'] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/3_3/page1.png', label: 'Nana is tired. "I need to clean."', correctIndex: 0 },
    { imageUrl: '/illustrations/3_3/page2.png', label: 'I clean the leaves for Nana.', correctIndex: 1 },
    { imageUrl: '/illustrations/3_3/page3.png', label: 'I find him. "We need a team!"', correctIndex: 2 },
    { imageUrl: '/illustrations/3_3/page4.png', label: 'We clean and sweep the yard.', correctIndex: 3 },
    { imageUrl: '/illustrations/3_3/page5.png', label: 'I reach each tin from the shelf!', correctIndex: 4 },
    { imageUrl: '/illustrations/3_3/page6.png', label: 'What a dream team!', correctIndex: 5 },
    { imageUrl: '/illustrations/3_3/page7.png', label: 'We get sweet plantain at the shop.', correctIndex: 6 },
    { imageUrl: '/illustrations/3_3/page8.png', label: 'Nana brings us a feast! We beam.', correctIndex: 7 }] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'Reach for the Treat!' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// L3.4 — "Draw It Again!"
// Focus sounds: oi, aw
// ═══════════════════════════════════════════════════════════════════════════════

export const BOOK_L3_4_PAGES: InteractivePage[] = [
  {
    type: 'cover',
    title: 'What Min Saw',
    subtitle: 'Level 3 · New Spellings',
    imageUrl: '/illustrations/3_4/cover.png',
  },
  {
    type: 'sound_grid',
    focusSounds: ['oi', 'aw'],
    allSounds: L3_ALL_SOUNDS,
  },
  {
    type: 'vocab_preview',
    words: [
      w('draw', 'draw', ['d','r','aw']),
      w('hawk', 'hawk', ['h','aw','k']),
      w('claws', 'claws', ['c','l','aw','z']),
      w('oil', 'oil', ['oi','l']),
      w('points', 'points', ['p','oi','n','t','s']),
      w('toil', 'toil', ['t','oi','l']),
      w('raw', 'raw', ['r','aw']),
      w('spoil', 'spoil', ['s','p','oi','l']),
    ],
  },

  // Page 1
  {
    type: 'story',
    sentences: ['Mum got her coat.', "'Let us go to the park,' she said.", 'Min was so glad.', 'She got on her pink coat and ran to the door.'],
    words: [
      w('Mum', 'mum', ['m','u','m']), w('got', 'got', ['g','o','t']),
      w('her', 'her', ['h','er']), w('coat.', 'coat', ['c','oa','t']),
      tricky("'Let", 'let'), w('us', 'us', ['u','s']),
      tricky('go', 'go'), tricky('to', 'to'), tricky('the', 'the'),
      w("park,'", 'park', ['p','ar','k']),
      tricky('she', 'she'), tricky('said.', 'said'),
      w('Min', 'min', ['m','i','n']), tricky('was', 'was'),
      tricky('so', 'so'), w('glad.', 'glad', ['g','l','a','d']),
      tricky('She', 'she'), w('got', 'got', ['g','o','t']),
      w('on', 'on', ['o','n']), w('her', 'her', ['h','er']),
      w('pink', 'pink', ['p','i','nk']), w('coat', 'coat', ['c','oa','t']),
      w('and', 'and', ['a','n','d']), w('ran', 'ran', ['r','a','n']),
      tricky('to', 'to'), tricky('the', 'the'),
      w('door.', 'door', ['d','oor']),
    ],
    imageUrl: '/illustrations/3_4/page1.png', audioUrl: '/sounds/sentences/L3_4_p1.mp3',
  },

  // Page 2
  {
    type: 'story',
    sentences: ['Out on the street, Mum pointed up.', "'Look at that tall block!' she said.", 'Min saw a big red bus zoom past.'],
    words: [
      w('Out', 'out', ['ou','t']), w('on', 'on', ['o','n']),
      tricky('the', 'the'),
      w('street,', 'street', ['s','t','r','ee','t']),
      w('Mum', 'mum', ['m','u','m']),
      w('pointed', 'pointed', ['p','oi','n','t','e','d']),
      w('up.', 'up', ['u','p']),
      tricky("'Look", 'look'), w('at', 'at', ['a','t']),
      w('that', 'that', ['th','a','t']),
      tricky('tall', 'tall'),
      w("block!'", 'block', ['b','l','o','ck']),
      tricky('she', 'she'), tricky('said.', 'said'),
      w('Min', 'min', ['m','i','n']),
      w('saw', 'saw', ['s','aw']), tricky('a', 'a'),
      w('big', 'big', ['b','i','g']), w('red', 'red', ['r','e','d']),
      w('bus', 'bus', ['b','u','s']),
      w('zoom', 'zoom', ['z','oo','m']),
      w('past.', 'past', ['p','a','s','t']),
    ],
    imageUrl: '/illustrations/3_4/page2.png', audioUrl: '/sounds/sentences/L3_4_p2.mp3',
  },

  // Page 3
  {
    type: 'story',
    sentences: ['At the park, Min saw a soft grey cat.', 'The cat had a small white paw and bright eyes.', "'Hello, cat!' said Min with a grin."],
    words: [
      w('At', 'at', ['a','t']), tricky('the', 'the'),
      w('park,', 'park', ['p','ar','k']),
      w('Min', 'min', ['m','i','n']), w('saw', 'saw', ['s','aw']),
      tricky('a', 'a'), w('soft', 'soft', ['s','o','f','t']),
      w('grey', 'grey', ['g','r','ey']),
      w('cat.', 'cat', ['c','a','t']),
      tricky('The', 'the'), w('cat', 'cat', ['c','a','t']),
      tricky('had', 'had'), tricky('a', 'a'),
      w('small', 'small', ['s','m','a','ll']),
      w('white', 'white', ['wh','i-e','t']),
      w('paw', 'paw', ['p','aw']),
      w('and', 'and', ['a','n','d']),
      w('bright', 'bright', ['b','r','igh','t']),
      tricky('eyes.', 'eyes'),
      tricky("'Hello,", 'hello'),
      w("cat!'", 'cat', ['c','a','t']),
      tricky('said', 'said'), w('Min', 'min', ['m','i','n']),
      w('with', 'with', ['w','i','th']), tricky('a', 'a'),
      w('grin.', 'grin', ['g','r','i','n']),
    ],
    imageUrl: '/illustrations/3_4/page3.png', audioUrl: '/sounds/sentences/L3_4_p3.mp3',
  },

  // Page 4
  {
    type: 'story',
    sentences: ['Min hopped on a stone in a stream.', 'She spotted a bright coin in the soil!', "'Look, Mum!' she said.", 'She picked it up and held it tight.'],
    words: [
      w('Min', 'min', ['m','i','n']),
      w('hopped', 'hopped', ['h','o','pp','ed']),
      w('on', 'on', ['o','n']), tricky('a', 'a'),
      w('stone', 'stone', ['s','t','o-e','n']),
      w('in', 'in', ['i','n']), tricky('a', 'a'),
      w('stream.', 'stream', ['s','t','r','ea','m']),
      tricky('She', 'she'),
      w('spotted', 'spotted', ['s','p','o','tt','e','d']),
      tricky('a', 'a'),
      w('bright', 'bright', ['b','r','igh','t']),
      w('coin', 'coin', ['c','oi','n']),
      w('in', 'in', ['i','n']), tricky('the', 'the'),
      w('soil!', 'soil', ['s','oi','l']),
      tricky("'Look,", 'look'),
      w("Mum!'", 'mum', ['m','u','m']),
      tricky('she', 'she'), tricky('said.', 'said'),
      tricky('She', 'she'),
      w('picked', 'picked', ['p','i','ck','ed']),
      w('it', 'it', ['i','t']), w('up', 'up', ['u','p']),
      w('and', 'and', ['a','n','d']),
      w('held', 'held', ['h','e','l','d']),
      w('it', 'it', ['i','t']),
      w('tight.', 'tight', ['t','igh','t']),
    ],
    imageUrl: '/illustrations/3_4/page4.png', audioUrl: '/sounds/sentences/L3_4_p4.mp3',
  },

  // Page 5
  {
    type: 'story',
    sentences: ['They went up a steep hill.', 'From the top, Min saw the whole town.', 'Mum pointed at the bright bend in the river.'],
    words: [
      tricky('They', 'they'),
      w('went', 'went', ['w','e','n','t']),
      w('up', 'up', ['u','p']), tricky('a', 'a'),
      w('steep', 'steep', ['s','t','ee','p']),
      w('hill.', 'hill', ['h','i','ll']),
      w('From', 'from', ['f','r','o','m']),
      tricky('the', 'the'), w('top,', 'top', ['t','o','p']),
      w('Min', 'min', ['m','i','n']),
      w('saw', 'saw', ['s','aw']),
      tricky('the', 'the'), tricky('whole', 'whole'),
      w('town.', 'town', ['t','ow','n']),
      w('Mum', 'mum', ['m','u','m']),
      w('pointed', 'pointed', ['p','oi','n','t','e','d']),
      w('at', 'at', ['a','t']), tricky('the', 'the'),
      w('bright', 'bright', ['b','r','igh','t']),
      w('bend', 'bend', ['b','e','n','d']),
      w('in', 'in', ['i','n']), tricky('the', 'the'),
      w('river.', 'river', ['r','i','v','er']),
    ],
    imageUrl: '/illustrations/3_4/page5.png', audioUrl: '/sounds/sentences/L3_4_p5.mp3',
  },

  // Page 6
  {
    type: 'story',
    sentences: ['All at once — a hawk!', 'A big brown hawk flapped past.', 'It had sharp claws and wide wings.', 'Min looked up.', 'Her jaw dropped!'],
    words: [
      tricky('All', 'all'),
      w('at', 'at', ['a','t']), tricky('once', 'once'),
      tricky('—', 'em-dash'), tricky('a', 'a'),
      w('hawk!', 'hawk', ['h','aw','k']),
      tricky('A', 'a'), w('big', 'big', ['b','i','g']),
      w('brown', 'brown', ['b','r','ow','n']),
      w('hawk', 'hawk', ['h','aw','k']),
      w('flapped', 'flapped', ['f','l','a','pp','ed']),
      w('past.', 'past', ['p','a','s','t']),
      w('It', 'it', ['i','t']), tricky('had', 'had'),
      w('sharp', 'sharp', ['sh','ar','p']),
      w('claws', 'claws', ['c','l','aw','z']),
      w('and', 'and', ['a','n','d']),
      w('wide', 'wide', ['w','i-e','d']),
      w('wings.', 'wings', ['w','i','ng','s']),
      w('Min', 'min', ['m','i','n']),
      w('looked', 'looked', ['l','oo','k','ed']),
      w('up.', 'up', ['u','p']),
      w('Her', 'her', ['h','er']),
      w('jaw', 'jaw', ['j','aw']),
      w('dropped!', 'dropped', ['d','r','o','pp','ed']),
    ],
    imageUrl: '/illustrations/3_4/page6.png', audioUrl: '/sounds/sentences/L3_4_p6.mp3',
  },

  // Page 7
  {
    type: 'story',
    sentences: ['They sat on the grass to rest.', 'The hawk soared in big slow rings.', "'I saw a hawk!' said Min.", "'I will not forget!'"],
    words: [
      tricky('They', 'they'),
      w('sat', 'sat', ['s','a','t']),
      w('on', 'on', ['o','n']), tricky('the', 'the'),
      w('grass', 'grass', ['g','r','a','ss']),
      tricky('to', 'to'),
      w('rest.', 'rest', ['r','e','s','t']),
      tricky('The', 'the'),
      w('hawk', 'hawk', ['h','aw','k']),
      w('soared', 'soared', ['s','oar','ed']),
      w('in', 'in', ['i','n']),
      w('big', 'big', ['b','i','g']),
      w('slow', 'slow', ['s','l','ow']),
      w('rings.', 'rings', ['r','i','ng','s']),
      tricky("'I", 'I'),
      w('saw', 'saw', ['s','aw']), tricky('a', 'a'),
      w("hawk!'", 'hawk', ['h','aw','k']),
      tricky('said', 'said'),
      w('Min.', 'min', ['m','i','n']),
      tricky("'I", 'I'), w('will', 'will', ['w','i','ll']),
      w('not', 'not', ['n','o','t']),
      w("forget!'", 'forget', ['f','or','g','e','t']),
    ],
    imageUrl: '/illustrations/3_4/page7.png', audioUrl: '/sounds/sentences/L3_4_p7.mp3',
  },

  // Page 8
  {
    type: 'story',
    sentences: ['On the way home, the trees were gold.', 'Min still had her coin.', 'She smiled at Mum.', "'What a day! I saw so much!'"],
    words: [
      w('On', 'on', ['o','n']), tricky('the', 'the'),
      w('way', 'way', ['w','ay']),
      w('home,', 'home', ['h','o-e','m']),
      tricky('the', 'the'),
      w('trees', 'trees', ['t','r','ee','s']),
      tricky('were', 'were'),
      w('gold.', 'gold', ['g','o','l','d']),
      w('Min', 'min', ['m','i','n']),
      w('still', 'still', ['s','t','i','ll']),
      tricky('had', 'had'), w('her', 'her', ['h','er']),
      w('coin.', 'coin', ['c','oi','n']),
      tricky('She', 'she'),
      w('smiled', 'smiled', ['s','m','i-e','l','d']),
      w('at', 'at', ['a','t']),
      w('Mum.', 'mum', ['m','u','m']),
      tricky("'What", 'what'), tricky('a', 'a'),
      w('day!', 'day', ['d','ay']),
      tricky('I', 'I'),
      w('saw', 'saw', ['s','aw']),
      tricky('so', 'so'),
      w("much!'", 'much', ['m','u','ch']),
    ],
    imageUrl: '/illustrations/3_4/page8.png', audioUrl: '/sounds/sentences/L3_4_p8.mp3',
  },
  {
    type: 'quiz',
    questions: [
      { question: 'Where did Min and Mum go?',
        options: [{ label: 'the park', isCorrect: true }, { label: 'the shops', isCorrect: false }, { label: 'school', isCorrect: false }] },
      { question: 'What did Min find in the soil?',
        options: [{ label: 'a bright coin', isCorrect: true }, { label: 'a snail', isCorrect: false }, { label: 'a stick', isCorrect: false }] },
      { question: 'What flew past at the end?',
        options: [{ label: 'a big brown hawk', isCorrect: true }, { label: 'a bus', isCorrect: false }, { label: 'a butterfly', isCorrect: false }] },
    ],
  },

  { type: 'sound_spotlight', sound: 'oi', items: [
    { word: 'oil', imageUrl: '/images/words/oil.png', focusIndex: 0 },
    { word: 'coin', imageUrl: '/images/words/coin.png', focusIndex: 1 },
    { word: 'join', imageUrl: '/images/words/join.png', focusIndex: 1 },
    { word: 'soil', imageUrl: '/images/words/soil.png', focusIndex: 1 }] },
  { type: 'sound_spotlight', sound: 'aw', items: [
    { word: 'draw', imageUrl: '/images/words/draw.png', focusIndex: 2 },
    { word: 'hawk', imageUrl: '/images/words/hawk.png', focusIndex: 1 },
    { word: 'straw', imageUrl: '/images/words/straw.png', focusIndex: 3 },
    { word: 'claw', imageUrl: '/images/words/claw.png', focusIndex: 2 }] },

  { type: 'word_reading', words: [
    w('draw', 'draw', ['d','r','aw']), w('hawk', 'hawk', ['h','aw','k']),
    w('oil', 'oil', ['oi','l']), w('join', 'join', ['j','oi','n']),
    w('claws', 'claws', ['c','l','aw','z']), w('toil', 'toil', ['t','oi','l'])] },

  { type: 'tricky_words', words: [
    tricky('said', 'said'), tricky('she', 'she'), tricky('he', 'he'),
    tricky('are', 'are'), tricky('so', 'so'), tricky('they', 'they')] },

  { type: 'spelling', words: [
    { word: 'draw', imageUrl: '/images/words/draw.png', letters: ['d','r','a','w'] },
    { word: 'hawk', imageUrl: '/images/words/hawk.png', letters: ['h','a','w','k'] },
    { word: 'oil', imageUrl: '/images/words/oil.png', letters: ['o','i','l'] },
    { word: 'join', imageUrl: '/images/words/join.png', letters: ['j','o','i','n'] }] },

  { type: 'nonsense_words', words: [
    w('bloin', 'bloin', ['b','l','oi','n']), w('crawk', 'crawk', ['c','r','aw','k']),
    w('froil', 'froil', ['f','r','oi','l']), w('snaw', 'snaw', ['s','n','aw']),
    w('gloid', 'gloid', ['g','l','oi','d']), w('prawn', 'prawn', ['p','r','aw','n']),
    w('troil', 'troil', ['t','r','oi','l']), w('flawk', 'flawk', ['f','l','aw','k'])] },

  { type: 'writing_practice', letters: ['oi', 'aw', 'o', 'a'] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/3_4/page1.png', label: 'A walk to the park.', correctIndex: 0 },
    { imageUrl: '/illustrations/3_4/page2.png', label: 'Out on the street.', correctIndex: 1 },
    { imageUrl: '/illustrations/3_4/page3.png', label: 'A soft grey cat.', correctIndex: 2 },
    { imageUrl: '/illustrations/3_4/page4.png', label: 'A coin in the soil.', correctIndex: 3 },
    { imageUrl: '/illustrations/3_4/page5.png', label: 'Up a steep hill.', correctIndex: 4 },
    { imageUrl: '/illustrations/3_4/page6.png', label: 'A brown hawk!', correctIndex: 5 },
    { imageUrl: '/illustrations/3_4/page7.png', label: 'The hawk soars.', correctIndex: 6 },
    { imageUrl: '/illustrations/3_4/page8.png', label: 'Home with the coin.', correctIndex: 7 }] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'What Min Saw' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// L3.5 — "The Boat with the Red Sail"
// Focus sounds: ai, oa
// ═══════════════════════════════════════════════════════════════════════════════

export const BOOK_L3_5_PAGES: InteractivePage[] = [
  {
    type: 'cover',
    title: 'The Boat with the Red Sail',
    subtitle: 'Level 3 · New Spellings',
    imageUrl: '/illustrations/3_5/cover.png',
  },
  {
    type: 'sound_grid',
    focusSounds: ['ai', 'oa'],
    allSounds: L3_ALL_SOUNDS,
  },
  {
    type: 'vocab_preview',
    words: [
      w('wait', 'wait', ['w','ai','t']),
      w('rain', 'rain', ['r','ai','n']),
      w('sail', 'sail', ['s','ai','l']),
      w('snail', 'snail', ['s','n','ai','l']),
      w('boat', 'boat', ['b','oa','t']),
      w('coast', 'coast', ['c','oa','s','t']),
      w('groan', 'groan', ['g','r','oa','n']),
      w('foam', 'foam', ['f','oa','m']),
    ],
  },

  // Page 1
  {
    type: 'story',
    sentences: ['Kai sits on the road eating toast.', 'He spots a boat far out at sea.', 'It has a big red sail!'],
    words: [
      tricky('Kai', 'kai'),
      w('sits', 'sits', ['s','i','t','s']),
      w('on', 'on', ['o','n']), tricky('the', 'the'),
      w('road', 'road', ['r','oa','d']),
      w('eating', 'eating', ['ee','t','i','ng']),
      w('toast.', 'toast', ['t','oa','s','t']),
      tricky('He', 'he'),
      w('spots', 'spots', ['s','p','o','t','s']),
      tricky('a', 'a'),
      w('boat', 'boat', ['b','oa','t']),
      w('far', 'far', ['f','ar']),
      w('out', 'out', ['ou','t']),
      w('at', 'at', ['a','t']),
      w('sea.', 'sea', ['s','ea']),
      w('It', 'it', ['i','t']),
      tricky('has', 'has'), tricky('a', 'a'),
      w('big', 'big', ['b','i','g']),
      w('red', 'red', ['r','e','d']),
      w('sail!', 'sail', ['s','ai','l']),
    ],
    imageUrl: '/illustrations/3_5/page1.png', audioUrl: '/sounds/sentences/L3_5_p1.mp3',
  },

  // Page 2
  {
    type: 'story',
    sentences: ['Kai grabs his coat and runs!', 'Rain splats on the main road.', 'That red sail — it must be him!'],
    words: [
      tricky('Kai', 'kai'),
      w('grabs', 'grabs', ['g','r','a','b','s']),
      tricky('his', 'his'),
      w('coat', 'coat', ['c','oa','t']),
      w('and', 'and', ['a','n','d']),
      w('runs!', 'runs', ['r','u','n','s']),
      w('Rain', 'rain', ['r','ai','n']),
      w('splats', 'splats', ['s','p','l','a','t','s']),
      w('on', 'on', ['o','n']), tricky('the', 'the'),
      w('main', 'main', ['m','ai','n']),
      w('road.', 'road', ['r','oa','d']),
      w('That', 'that', ['th','a','t']),
      w('red', 'red', ['r','e','d']),
      w('sail', 'sail', ['s','ai','l']),
      tricky('—', 'em-dash'),
      w('it', 'it', ['i','t']),
      w('must', 'must', ['m','u','s','t']),
      tricky('be', 'be'), tricky('him!', 'him'),
    ],
    imageUrl: '/illustrations/3_5/page2.png', audioUrl: '/sounds/sentences/L3_5_p2.mp3',
  },

  // Page 3
  {
    type: 'story',
    sentences: ['From the trail, Kai spots fish on the boat!', 'A fat snail blocks his path.', "'Not now, snail!' said Kai."],
    words: [
      w('From', 'from', ['f','r','o','m']),
      tricky('the', 'the'),
      w('trail,', 'trail', ['t','r','ai','l']),
      tricky('Kai', 'kai'),
      w('spots', 'spots', ['s','p','o','t','s']),
      w('fish', 'fish', ['f','i','sh']),
      w('on', 'on', ['o','n']), tricky('the', 'the'),
      w('boat!', 'boat', ['b','oa','t']),
      tricky('A', 'a'),
      w('fat', 'fat', ['f','a','t']),
      w('snail', 'snail', ['s','n','ai','l']),
      w('blocks', 'blocks', ['b','l','o','ck','s']),
      tricky('his', 'his'),
      w('path.', 'path', ['p','a','th']),
      tricky("'Not", 'not'),
      w('now,', 'now', ['n','ow']),
      w("snail!'", 'snail', ['s','n','ai','l']),
      tricky('said', 'said'),
      tricky('Kai.', 'kai'),
    ],
    imageUrl: '/illustrations/3_5/page3.png', audioUrl: '/sounds/sentences/L3_5_p3.mp3',
  },

  // Page 4
  {
    type: 'story',
    sentences: ['Kai slips and slides into a drain!', 'His coat is soaked in mud.', 'He groans — the boat will not wait!'],
    words: [
      tricky('Kai', 'kai'),
      w('slips', 'slips', ['s','l','i','p','s']),
      w('and', 'and', ['a','n','d']),
      w('slides', 'slides', ['s','l','i-e','d','s']),
      tricky('into', 'into'), tricky('a', 'a'),
      w('drain!', 'drain', ['d','r','ai','n']),
      tricky('His', 'his'),
      w('coat', 'coat', ['c','oa','t']),
      tricky('is', 'is'),
      w('soaked', 'soaked', ['s','oa','k','ed']),
      w('in', 'in', ['i','n']),
      w('mud.', 'mud', ['m','u','d']),
      tricky('He', 'he'),
      w('groans', 'groans', ['g','r','oa','n','s']),
      tricky('—', 'em-dash'),
      tricky('the', 'the'),
      w('boat', 'boat', ['b','oa','t']),
      w('will', 'will', ['w','i','ll']),
      w('not', 'not', ['n','o','t']),
      w('wait!', 'wait', ['w','ai','t']),
    ],
    imageUrl: '/illustrations/3_5/page4.png', audioUrl: '/sounds/sentences/L3_5_p4.mp3',
  },

  // Page 5
  {
    type: 'story',
    sentences: ['He runs and runs to the coast at last!', 'The boat sails in from the sea.', 'Kai spots the red sail!'],
    words: [
      tricky('He', 'he'),
      w('runs', 'runs', ['r','u','n','s']),
      w('and', 'and', ['a','n','d']),
      w('runs', 'runs', ['r','u','n','s']),
      tricky('to', 'to'), tricky('the', 'the'),
      w('coast', 'coast', ['c','oa','s','t']),
      w('at', 'at', ['a','t']),
      w('last!', 'last', ['l','a','s','t']),
      tricky('The', 'the'),
      w('boat', 'boat', ['b','oa','t']),
      w('sails', 'sails', ['s','ai','l','s']),
      w('in', 'in', ['i','n']),
      w('from', 'from', ['f','r','o','m']),
      tricky('the', 'the'),
      w('sea.', 'sea', ['s','ea']),
      tricky('Kai', 'kai'),
      w('spots', 'spots', ['s','p','o','t','s']),
      tricky('the', 'the'),
      w('red', 'red', ['r','e','d']),
      w('sail!', 'sail', ['s','ai','l']),
    ],
    imageUrl: '/illustrations/3_5/page5.png', audioUrl: '/sounds/sentences/L3_5_p5.mp3',
  },

  // Page 6
  {
    type: 'story',
    sentences: ['The boat docks with a big load of fish.', 'A man in a coat shouts out.', "'Kai! Kai!'"],
    words: [
      tricky('The', 'the'),
      w('boat', 'boat', ['b','oa','t']),
      w('docks', 'docks', ['d','o','ck','s']),
      w('with', 'with', ['w','i','th']),
      tricky('a', 'a'),
      w('big', 'big', ['b','i','g']),
      w('load', 'load', ['l','oa','d']),
      tricky('of', 'of'),
      w('fish.', 'fish', ['f','i','sh']),
      tricky('A', 'a'),
      w('man', 'man', ['m','a','n']),
      w('in', 'in', ['i','n']), tricky('a', 'a'),
      w('coat', 'coat', ['c','oa','t']),
      w('shouts', 'shouts', ['sh','ou','t','s']),
      w('out.', 'out', ['ou','t']),
      tricky("'Kai!", 'kai'),
      tricky("Kai!'", 'kai'),
    ],
    imageUrl: '/illustrations/3_5/page6.png', audioUrl: '/sounds/sentences/L3_5_p6.mp3',
  },

  // Page 7
  {
    type: 'story',
    sentences: ['It is Dad!', 'Dad leaps off the boat and scoops Kai up.', 'They spin in the sun!'],
    words: [
      w('It', 'it', ['i','t']),
      tricky('is', 'is'),
      w('Dad!', 'dad', ['d','a','d']),
      w('Dad', 'dad', ['d','a','d']),
      w('leaps', 'leaps', ['l','ea','p','s']),
      w('off', 'off', ['o','ff']),
      tricky('the', 'the'),
      w('boat', 'boat', ['b','oa','t']),
      w('and', 'and', ['a','n','d']),
      w('scoops', 'scoops', ['s','c','oo','p','s']),
      tricky('Kai', 'kai'),
      w('up.', 'up', ['u','p']),
      tricky('They', 'they'),
      w('spin', 'spin', ['s','p','i','n']),
      w('in', 'in', ['i','n']),
      tricky('the', 'the'),
      w('sun!', 'sun', ['s','u','n']),
    ],
    imageUrl: '/illustrations/3_5/page7.png', audioUrl: '/sounds/sentences/L3_5_p7.mp3',
  },

  // Page 8
  {
    type: 'story',
    sentences: ['They stroll back up the road with the fish.', 'The snail is still on the trail!', "'I beat the snail!' grins Kai."],
    words: [
      tricky('They', 'they'),
      w('stroll', 'stroll', ['s','t','r','o','ll']),
      w('back', 'back', ['b','a','ck']),
      w('up', 'up', ['u','p']), tricky('the', 'the'),
      w('road', 'road', ['r','oa','d']),
      w('with', 'with', ['w','i','th']),
      tricky('the', 'the'),
      w('fish.', 'fish', ['f','i','sh']),
      tricky('The', 'the'),
      w('snail', 'snail', ['s','n','ai','l']),
      tricky('is', 'is'),
      w('still', 'still', ['s','t','i','ll']),
      w('on', 'on', ['o','n']),
      tricky('the', 'the'),
      w('trail!', 'trail', ['t','r','ai','l']),
      tricky("'I", 'I'),
      w('beat', 'beat', ['b','ea','t']),
      tricky('the', 'the'),
      w("snail!'", 'snail', ['s','n','ai','l']),
      w('grins', 'grins', ['g','r','i','n','s']),
      tricky('Kai.', 'kai'),
    ],
    imageUrl: '/illustrations/3_5/page8.png', audioUrl: '/sounds/sentences/L3_5_p8.mp3',
  },
  {
    type: 'quiz',
    questions: [
      { question: 'What does Kai chase across town?',
        options: [{ label: 'a boat with a red sail', isCorrect: true }, { label: 'a snail', isCorrect: false }, { label: 'a bus', isCorrect: false }] },
      { question: 'What slips Kai into a drain?',
        options: [{ label: 'mud / wet road', isCorrect: true }, { label: 'a rock', isCorrect: false }, { label: 'the snail', isCorrect: false }] },
      { question: 'Who is on the boat?',
        options: [{ label: 'Dad', isCorrect: true }, { label: 'Mum', isCorrect: false }, { label: 'a stranger', isCorrect: false }] },
    ],
  },

  { type: 'sound_spotlight', sound: 'ai', items: [
    { word: 'sail', imageUrl: '/images/words/sail.png', focusIndex: 1 },
    { word: 'rain', imageUrl: '/images/words/rain.png', focusIndex: 1 },
    { word: 'snail', imageUrl: '/images/words/snail.png', focusIndex: 2 },
    { word: 'wait', imageUrl: '/images/words/wait.png', focusIndex: 1 }] },
  { type: 'sound_spotlight', sound: 'oa', items: [
    { word: 'boat', imageUrl: '/images/words/boat.png', focusIndex: 1 },
    { word: 'coat', imageUrl: '/images/words/coat.png', focusIndex: 1 },
    { word: 'road', imageUrl: '/images/words/road.png', focusIndex: 1 },
    { word: 'goat', imageUrl: '/images/words/goat.png', focusIndex: 1 }] },

  { type: 'word_reading', words: [
    w('boat', 'boat', ['b','oa','t']), w('sail', 'sail', ['s','ai','l']),
    w('rain', 'rain', ['r','ai','n']), w('coast', 'coast', ['c','oa','s','t']),
    w('wait', 'wait', ['w','ai','t']), w('groan', 'groan', ['g','r','oa','n'])] },

  { type: 'tricky_words', words: [
    tricky('said', 'said'), tricky('was', 'was'), tricky('so', 'so'),
    tricky('he', 'he'), tricky('what', 'what'), tricky('they', 'they')] },

  { type: 'spelling', words: [
    { word: 'boat', imageUrl: '/images/words/boat.png', letters: ['b','o','a','t'] },
    { word: 'sail', imageUrl: '/images/words/sail.png', letters: ['s','a','i','l'] },
    { word: 'rain', imageUrl: '/images/words/rain.png', letters: ['r','a','i','n'] },
    { word: 'wait', imageUrl: '/images/words/wait.png', letters: ['w','a','i','t'] }] },

  { type: 'nonsense_words', words: [
    w('blain', 'blain', ['b','l','ai','n']), w('froat', 'froat', ['f','r','oa','t']),
    w('snait', 'snait', ['s','n','ai','t']), w('groal', 'groal', ['g','r','oa','l']),
    w('plaid', 'plaid', ['p','l','ai','d']), w('troam', 'troam', ['t','r','oa','m']),
    w('stain', 'stain', ['s','t','ai','n']), w('cloat', 'cloat', ['c','l','oa','t'])] },

  { type: 'writing_practice', letters: ['ai', 'oa', 'a', 'o'] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/3_5/page1.png', label: 'Kai spots a red sail.', correctIndex: 0 },
    { imageUrl: '/illustrations/3_5/page2.png', label: 'Rain on the main road.', correctIndex: 1 },
    { imageUrl: '/illustrations/3_5/page3.png', label: 'A snail blocks the trail.', correctIndex: 2 },
    { imageUrl: '/illustrations/3_5/page4.png', label: 'Into the drain!', correctIndex: 3 },
    { imageUrl: '/illustrations/3_5/page5.png', label: 'He runs to the coast.', correctIndex: 4 },
    { imageUrl: '/illustrations/3_5/page6.png', label: 'A man calls his name.', correctIndex: 5 },
    { imageUrl: '/illustrations/3_5/page7.png', label: 'It is Dad!', correctIndex: 6 },
    { imageUrl: '/illustrations/3_5/page8.png', label: 'Stroll home, snail still on the trail.', correctIndex: 7 } ] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'The Boat with the Red Sail' },
];
