/**
 * Interactive book page data for Level 5 books
 * L5 focus sounds: ore, oor, ire, ear, ure, tion, ph, kn, wr
 */

import type { InteractivePage, StoryWord } from './interactiveBookData';

// ── Helpers ──

function word(display: string, w: string, phonemes: string[]): StoryWord {
  return { display, word: w, phonemes };
}
function tricky(display: string, w: string): StoryWord {
  return { display, word: w, phonemes: [], isTricky: true };
}

// L5 cumulative sounds (all sounds from L1–L5)
const L5_ALL_SOUNDS = [
  's/ss', 'a', 't', 'p', 'i', 'n', 'm', 'd', 'g', 'o',
  'c/k/ck', 'e', 'u', 'r', 'h', 'b', 'f/ff',
  'l/ll', 'j', 'v', 'w', 'x', 'y', 'z/zz',
  'qu', 'ch', 'sh', 'th', 'ng', 'nk',
  // L2
  'ai', 'ee', 'igh', 'oa', 'oo', 'ar', 'or', 'ur', 'ow', 'oi',
  'er',
  // L3
  'aw/au', 'ew', 'oe', 'ou', 'ie', 'ea', 'wh', 'ph',
  // L4
  'ay', 'ey', 'a-e', 'e-e', 'i-e', 'o-e', 'u-e',
  // L5
  'ore', 'oor', 'ire', 'ear', 'ure', 'tion', 'kn', 'wr',
];

// ═══════════════════════════════════════════════════════════════════════════
// L5.1 — "Before the Shore"
// Focus sounds: ore, ire, oor (Flashback/Time Shift structure)
// Setting: British seaside, boy finds a stone
// ═══════════════════════════════════════════════════════════════════════════

export const BOOK_L5_1_PAGES: InteractivePage[] = [
  // ── COVER ──
  { type: 'cover', title: 'Before the Shore', subtitle: 'Level 5 · Reading Together', imageUrl: '/illustrations/5_1/cover.png' },

  // ── SOUNDS ──
  {
    type: 'sound_grid',
    focusSounds: ['ore', 'ire', 'oor'],
    allSounds: L5_ALL_SOUNDS,
  },

  // ── VOCAB PREVIEW ──
  {
    type: 'vocab_preview',
    words: [
      word('shore', 'shore', ['sh','ore']),
      word('before', 'before', ['b','e','f','ore']),
      word('explore', 'explore', ['e','x','p','l','ore']),
      word('fire', 'fire', ['f','ire']),
      word('wire', 'wire', ['w','ire']),
      word('floor', 'floor', ['f','l','oor']),
      word('stone', 'stone', ['s','t','o-e','n']),
      word('flames', 'flames', ['f','l','a-e','m','s']),
    ],
  },

  // ── STORY PAGES ──
  // Page 1
  {
    type: 'story',
    sentences: ['The boy went through the park on his way home.', 'He was tired, and his feet were sore from play.', 'He sat on a bench to rest for a bit.', 'On the path he saw a smooth, flat stone.', 'He bent to pick it up and held it.'],
    words: [
      tricky('The', 'the'), word('boy', 'boy', ['b','oy']),
      word('went', 'went', ['w','e','n','t']), tricky('through', 'through'),
      tricky('the', 'the'), word('park', 'park', ['p','ar','k']),
      word('on', 'on', ['o','n']), word('his', 'his', ['h','i','s']),
      word('way', 'way', ['w','ay']), word('home.', 'home', ['h','o-e','m']),
      tricky('He', 'he'), tricky('was', 'was'),
      word('tired,', 'tired', ['t','ire','d']), word('and', 'and', ['a','n','d']),
      word('his', 'his', ['h','i','s']), word('feet', 'feet', ['f','ee','t']),
      tricky('were', 'were'), word('sore', 'sore', ['s','ore']),
      word('from', 'from', ['f','r','o','m']), word('play.', 'play', ['p','l','ay']),
      tricky('He', 'he'), word('sat', 'sat', ['s','a','t']),
      word('on', 'on', ['o','n']), tricky('a', 'a'),
      word('bench', 'bench', ['b','e','n','ch']), tricky('to', 'to'),
      word('rest', 'rest', ['r','e','s','t']), word('for', 'for', ['f','or']),
      tricky('a', 'a'), word('bit.', 'bit', ['b','i','t']),
      word('On', 'on', ['o','n']), tricky('the', 'the'),
      word('path', 'path', ['p','a','th']), tricky('he', 'he'),
      word('saw', 'saw', ['s','aw']), tricky('a', 'a'),
      word('smooth,', 'smooth', ['s','m','oo','th']), word('flat', 'flat', ['f','l','a','t']),
      word('stone.', 'stone', ['s','t','o-e','n']),
      tricky('He', 'he'), word('bent', 'bent', ['b','e','n','t']),
      tricky('to', 'to'), word('pick', 'pick', ['p','i','ck']),
      word('it', 'it', ['i','t']), word('up', 'up', ['u','p']),
      word('and', 'and', ['a','n','d']), word('held', 'held', ['h','e','l','d']),
      word('it.', 'it', ['i','t']),
    ],
    imageUrl: '/illustrations/5_1/page1.png', audioUrl: '/sounds/sentences/L5_1_p1.mp3',
  },

  // Page 2
  {
    type: 'story',
    sentences: ['The stone felt cool in his hand as he sat.', 'It had a shine, like one found by the shore.', 'Once, before this winter, he had seen a stone like it.', 'He sat still and went back to that day.', 'Leaves fell near the bench, and he shut his eyes.'],
    words: [
      tricky('The', 'the'), word('stone', 'stone', ['s','t','o-e','n']),
      word('felt', 'felt', ['f','e','l','t']), word('cool', 'cool', ['c','oo','l']),
      word('in', 'in', ['i','n']), word('his', 'his', ['h','i','s']),
      word('hand', 'hand', ['h','a','n','d']), word('as', 'as', ['a','s']),
      tricky('he', 'he'), word('sat.', 'sat', ['s','a','t']),
      word('It', 'it', ['i','t']), word('had', 'had', ['h','a','d']),
      tricky('a', 'a'), word('shine,', 'shine', ['sh','i-e','n']),
      word('like', 'like', ['l','i-e','k']), tricky('one', 'one'),
      word('found', 'found', ['f','ou','n','d']), word('by', 'by', ['b','y']),
      tricky('the', 'the'), word('shore.', 'shore', ['sh','ore']),
      tricky('Once,', 'once'), word('before', 'before', ['b','e','f','ore']),
      word('this', 'this', ['th','i','s']), word('winter,', 'winter', ['w','i','n','t','er']),
      tricky('he', 'he'), word('had', 'had', ['h','a','d']),
      word('seen', 'seen', ['s','ee','n']), tricky('a', 'a'),
      word('stone', 'stone', ['s','t','o-e','n']), word('like', 'like', ['l','i-e','k']),
      word('it.', 'it', ['i','t']),
      tricky('He', 'he'), word('sat', 'sat', ['s','a','t']),
      word('still', 'still', ['s','t','i','ll']), word('and', 'and', ['a','n','d']),
      word('went', 'went', ['w','e','n','t']), word('back', 'back', ['b','a','ck']),
      tricky('to', 'to'), word('that', 'that', ['th','a','t']),
      word('day.', 'day', ['d','ay']),
      word('Leaves', 'leaves', ['l','ea','v','s']), word('fell', 'fell', ['f','e','ll']),
      word('near', 'near', ['n','ear']), tricky('the', 'the'),
      word('bench,', 'bench', ['b','e','n','ch']), word('and', 'and', ['a','n','d']),
      tricky('he', 'he'), word('shut', 'shut', ['sh','u','t']),
      word('his', 'his', ['h','i','s']), tricky('eyes.', 'eyes'),
    ],
    imageUrl: '/illustrations/5_1/page2.png', audioUrl: '/sounds/sentences/L5_1_p2.mp3',
  },

  // Page 3
  {
    type: 'story',
    sentences: ['Before winter came, Dad took him to the shore.', 'The sea air was pure and fresh, and the sand felt soft.', '"Let us explore!" said Dad, and they ran on the beach.', 'They splashed in waves and watched the fire by the rocks.', 'Dad took a photo as flames moved in slow motion.'],
    words: [
      word('Before', 'before', ['b','e','f','ore']),
      word('winter', 'winter', ['w','i','n','t','er']), word('came,', 'came', ['c','a-e','m']),
      word('Dad', 'dad', ['d','a','d']), word('took', 'took', ['t','oo','k']),
      word('him', 'him', ['h','i','m']), tricky('to', 'to'),
      tricky('the', 'the'), word('shore.', 'shore', ['sh','ore']),
      tricky('The', 'the'), word('sea', 'sea', ['s','ea']),
      word('air', 'air', ['air']), tricky('was', 'was'),
      word('pure', 'pure', ['p','ure']), word('and', 'and', ['a','n','d']),
      word('fresh,', 'fresh', ['f','r','e','sh']), word('and', 'and', ['a','n','d']),
      tricky('the', 'the'), word('sand', 'sand', ['s','a','n','d']),
      word('felt', 'felt', ['f','e','l','t']), word('soft.', 'soft', ['s','o','f','t']),
      word('Let', 'let', ['l','e','t']), word('us', 'us', ['u','s']),
      word('explore!', 'explore', ['e','x','p','l','ore']),
      tricky('said', 'said'), word('Dad,', 'dad', ['d','a','d']),
      word('and', 'and', ['a','n','d']), tricky('they', 'they'),
      word('ran', 'ran', ['r','a','n']), word('on', 'on', ['o','n']),
      tricky('the', 'the'), word('beach.', 'beach', ['b','ea','ch']),
      tricky('They', 'they'), word('splashed', 'splashed', ['s','p','l','a','sh','ed']),
      word('in', 'in', ['i','n']), word('waves', 'waves', ['w','a-e','v','s']),
      word('and', 'and', ['a','n','d']), word('watched', 'watched', ['w','a','tch','ed']),
      tricky('the', 'the'), word('fire', 'fire', ['f','ire']),
      word('by', 'by', ['b','y']), tricky('the', 'the'),
      word('rocks.', 'rocks', ['r','o','ck','s']),
      word('Dad', 'dad', ['d','a','d']), word('took', 'took', ['t','oo','k']),
      tricky('a', 'a'), word('photo', 'photo', ['ph','o','t','o']),
      word('as', 'as', ['a','s']), word('flames', 'flames', ['f','l','a-e','m','s']),
      word('moved', 'moved', ['m','o-e','v','ed']), word('in', 'in', ['i','n']),
      word('slow', 'slow', ['s','l','ow']), word('motion.', 'motion', ['m','o-e','tion']),
    ],
    imageUrl: '/illustrations/5_1/page3.png', audioUrl: '/sounds/sentences/L5_1_p3.mp3',
  },

  // Page 4
  {
    type: 'story',
    sentences: ['The next day, he explored the rock pools near the shore.', 'He found more and more shells and set them in a pile.', 'Dad helped him put the best ones on a wire.', '"We can make a gift," said Dad, and the boy grinned.', 'He twisted the wire with care, and it looked nice.'],
    words: [
      tricky('The', 'the'), word('next', 'next', ['n','e','x','t']),
      word('day,', 'day', ['d','ay']), tricky('he', 'he'),
      word('explored', 'explored', ['e','x','p','l','ore','d']),
      tricky('the', 'the'), word('rock', 'rock', ['r','o','ck']),
      word('pools', 'pools', ['p','oo','l','s']), word('near', 'near', ['n','ear']),
      tricky('the', 'the'), word('shore.', 'shore', ['sh','ore']),
      tricky('He', 'he'), word('found', 'found', ['f','ou','n','d']),
      word('more', 'more', ['m','ore']), word('and', 'and', ['a','n','d']),
      word('more', 'more', ['m','ore']), word('shells', 'shells', ['sh','e','ll','s']),
      word('and', 'and', ['a','n','d']), word('set', 'set', ['s','e','t']),
      word('them', 'them', ['th','e','m']), word('in', 'in', ['i','n']),
      tricky('a', 'a'), word('pile.', 'pile', ['p','i-e','l']),
      word('Dad', 'dad', ['d','a','d']), word('helped', 'helped', ['h','e','l','p','ed']),
      word('him', 'him', ['h','i','m']), word('put', 'put', ['p','u','t']),
      tricky('the', 'the'), word('best', 'best', ['b','e','s','t']),
      word('ones', 'ones', ['o-e','n','s']), word('on', 'on', ['o','n']),
      tricky('a', 'a'), word('wire.', 'wire', ['w','ire']),
      tricky('We', 'we'), word('can', 'can', ['c','a','n']),
      word('make', 'make', ['m','a-e','k']), tricky('a', 'a'),
      word('gift,', 'gift', ['g','i','f','t']), tricky('said', 'said'),
      word('Dad,', 'dad', ['d','a','d']), word('and', 'and', ['a','n','d']),
      tricky('the', 'the'), word('boy', 'boy', ['b','oy']),
      word('grinned.', 'grinned', ['g','r','i','nn','ed']),
      tricky('He', 'he'), word('twisted', 'twisted', ['t','w','i','s','t','e','d']),
      tricky('the', 'the'), word('wire', 'wire', ['w','ire']),
      word('with', 'with', ['w','i','th']), word('care,', 'care', ['c','are']),
      word('and', 'and', ['a','n','d']), word('it', 'it', ['i','t']),
      word('looked', 'looked', ['l','oo','k','ed']), word('nice.', 'nice', ['n','i-e','s']),
    ],
    imageUrl: '/illustrations/5_1/page4.png', audioUrl: '/sounds/sentences/L5_1_p4.mp3',
  },

  // Page 5
  {
    type: 'story',
    sentences: ['Then it was time to go home from the shore.', 'He spotted a smooth, flat stone by the water line.', '"Keep it safe," said Dad, so you remember this trip.', 'He put the stone in his pocket and smiled.'],
    words: [
      word('Then', 'then', ['th','e','n']), word('it', 'it', ['i','t']),
      tricky('was', 'was'), word('time', 'time', ['t','i-e','m']),
      tricky('to', 'to'), tricky('go', 'go'),
      word('home', 'home', ['h','o-e','m']), word('from', 'from', ['f','r','o','m']),
      tricky('the', 'the'), word('shore.', 'shore', ['sh','ore']),
      tricky('He', 'he'), word('spotted', 'spotted', ['s','p','o','tt','e','d']),
      tricky('a', 'a'), word('smooth,', 'smooth', ['s','m','oo','th']),
      word('flat', 'flat', ['f','l','a','t']), word('stone', 'stone', ['s','t','o-e','n']),
      word('by', 'by', ['b','y']), tricky('the', 'the'),
      tricky('water', 'water'), word('line.', 'line', ['l','i-e','n']),
      word('Keep', 'keep', ['k','ee','p']), word('it', 'it', ['i','t']),
      word('safe,', 'safe', ['s','a-e','f']), tricky('said', 'said'),
      word('Dad,', 'dad', ['d','a','d']), tricky('so', 'so'),
      tricky('you', 'you'), word('remember', 'remember', ['r','e','m','e','m','b','er']),
      word('this', 'this', ['th','i','s']), word('trip.', 'trip', ['t','r','i','p']),
      tricky('He', 'he'), word('put', 'put', ['p','u','t']),
      tricky('the', 'the'), word('stone', 'stone', ['s','t','o-e','n']),
      word('in', 'in', ['i','n']), word('his', 'his', ['h','i','s']),
      word('pocket', 'pocket', ['p','o','ck','e','t']),
      word('and', 'and', ['a','n','d']), word('smiled.', 'smiled', ['s','m','i-e','l','d']),
    ],
    imageUrl: '/illustrations/5_1/page5.png', audioUrl: '/sounds/sentences/L5_1_p5.mp3',
  },

  // Page 6
  {
    type: 'story',
    sentences: ['Back on the bench, the boy sat up and smiled.', 'He still had that shore stone at home on a shelf.', 'But this was a new stone, smooth and cool to hold.', 'He held it up to the light and took a breath.', 'The shore felt so close again, right at his feet.'],
    words: [
      word('Back', 'back', ['b','a','ck']), word('on', 'on', ['o','n']),
      tricky('the', 'the'), word('bench,', 'bench', ['b','e','n','ch']),
      tricky('the', 'the'), word('boy', 'boy', ['b','oy']),
      word('sat', 'sat', ['s','a','t']), word('up', 'up', ['u','p']),
      word('and', 'and', ['a','n','d']), word('smiled.', 'smiled', ['s','m','i-e','l','d']),
      tricky('He', 'he'), word('still', 'still', ['s','t','i','ll']),
      word('had', 'had', ['h','a','d']), word('that', 'that', ['th','a','t']),
      word('shore', 'shore', ['sh','ore']), word('stone', 'stone', ['s','t','o-e','n']),
      word('at', 'at', ['a','t']), word('home', 'home', ['h','o-e','m']),
      word('on', 'on', ['o','n']), tricky('a', 'a'),
      word('shelf.', 'shelf', ['sh','e','l','f']),
      word('But', 'but', ['b','u','t']), word('this', 'this', ['th','i','s']),
      tricky('was', 'was'), tricky('a', 'a'),
      word('new', 'new', ['n','ew']), word('stone,', 'stone', ['s','t','o-e','n']),
      word('smooth', 'smooth', ['s','m','oo','th']), word('and', 'and', ['a','n','d']),
      word('cool', 'cool', ['c','oo','l']), tricky('to', 'to'),
      word('hold.', 'hold', ['h','o','l','d']),
      tricky('He', 'he'), word('held', 'held', ['h','e','l','d']),
      word('it', 'it', ['i','t']), word('up', 'up', ['u','p']),
      tricky('to', 'to'), tricky('the', 'the'),
      word('light', 'light', ['l','igh','t']), word('and', 'and', ['a','n','d']),
      word('took', 'took', ['t','oo','k']), tricky('a', 'a'),
      word('breath.', 'breath', ['b','r','ea','th']),
      tricky('The', 'the'), word('shore', 'shore', ['sh','ore']),
      word('felt', 'felt', ['f','e','l','t']), tricky('so', 'so'),
      word('close', 'close', ['c','l','o-e','s']), tricky('again,', 'again'),
      word('right', 'right', ['r','igh','t']), word('at', 'at', ['a','t']),
      word('his', 'his', ['h','i','s']), word('feet.', 'feet', ['f','ee','t']),
    ],
    imageUrl: '/illustrations/5_1/page6.png', audioUrl: '/sounds/sentences/L5_1_p6.mp3',
  },

  // Page 7
  {
    type: 'story',
    sentences: ['He ran home and in at the front door.', 'He got his shore stone, so now he had two.', 'He knew where Dad kept the wire and thin cord.', 'He made a loop for each stone and tied knots.', 'He wrote Dad on a tag, for a gift later.'],
    words: [
      tricky('He', 'he'), word('ran', 'ran', ['r','a','n']),
      word('home', 'home', ['h','o-e','m']), word('and', 'and', ['a','n','d']),
      word('in', 'in', ['i','n']), word('at', 'at', ['a','t']),
      tricky('the', 'the'), word('front', 'front', ['f','r','o','n','t']),
      word('door.', 'door', ['d','oor']),
      tricky('He', 'he'), word('got', 'got', ['g','o','t']),
      word('his', 'his', ['h','i','s']), word('shore', 'shore', ['sh','ore']),
      word('stone,', 'stone', ['s','t','o-e','n']), tricky('so', 'so'),
      word('now', 'now', ['n','ow']), tricky('he', 'he'),
      word('had', 'had', ['h','a','d']), tricky('two.', 'two'),
      tricky('He', 'he'), tricky('knew', 'knew'),
      tricky('where', 'where'), word('Dad', 'dad', ['d','a','d']),
      word('kept', 'kept', ['k','e','p','t']), tricky('the', 'the'),
      word('wire', 'wire', ['w','ire']), word('and', 'and', ['a','n','d']),
      word('thin', 'thin', ['th','i','n']), word('cord.', 'cord', ['c','or','d']),
      tricky('He', 'he'), word('made', 'made', ['m','a-e','d']),
      tricky('a', 'a'), word('loop', 'loop', ['l','oo','p']),
      word('for', 'for', ['f','or']), word('each', 'each', ['ea','ch']),
      word('stone', 'stone', ['s','t','o-e','n']), word('and', 'and', ['a','n','d']),
      word('tied', 'tied', ['t','ie','d']), word('knots.', 'knots', ['kn','o','t','s']),
      tricky('He', 'he'), word('wrote', 'wrote', ['wr','o-e','t']),
      word('Dad', 'dad', ['d','a','d']), word('on', 'on', ['o','n']),
      tricky('a', 'a'), word('tag,', 'tag', ['t','a','g']),
      word('for', 'for', ['f','or']), tricky('a', 'a'),
      word('gift', 'gift', ['g','i','f','t']), word('later.', 'later', ['l','a-e','t','er']),
    ],
    imageUrl: '/illustrations/5_1/page7.png', audioUrl: '/sounds/sentences/L5_1_p7.mp3',
  },

  // Page 8
  {
    type: 'story',
    sentences: ['He gave the stones to Dad in the sitting room.', '"From the shore and from the park," he said, proud.', 'Dad smiled wide and hooked them on his brown bag.', '"I will keep them with me, so I never forget."', 'Dad wore them that day, hanging bright on his bag.'],
    words: [
      tricky('He', 'he'), word('gave', 'gave', ['g','a-e','v']),
      tricky('the', 'the'), word('stones', 'stones', ['s','t','o-e','n','s']),
      tricky('to', 'to'), word('Dad', 'dad', ['d','a','d']),
      word('in', 'in', ['i','n']), tricky('the', 'the'),
      word('sitting', 'sitting', ['s','i','tt','i','ng']),
      word('room.', 'room', ['r','oo','m']),
      word('From', 'from', ['f','r','o','m']), tricky('the', 'the'),
      word('shore', 'shore', ['sh','ore']), word('and', 'and', ['a','n','d']),
      word('from', 'from', ['f','r','o','m']), tricky('the', 'the'),
      word('park,', 'park', ['p','ar','k']), tricky('he', 'he'),
      tricky('said,', 'said'), word('proud.', 'proud', ['p','r','ou','d']),
      word('Dad', 'dad', ['d','a','d']), word('smiled', 'smiled', ['s','m','i-e','l','d']),
      word('wide', 'wide', ['w','i-e','d']), word('and', 'and', ['a','n','d']),
      word('hooked', 'hooked', ['h','oo','k','ed']),
      word('them', 'them', ['th','e','m']), word('on', 'on', ['o','n']),
      word('his', 'his', ['h','i','s']), word('brown', 'brown', ['b','r','ow','n']),
      word('bag.', 'bag', ['b','a','g']),
      tricky('I', 'I'), word('will', 'will', ['w','i','ll']),
      word('keep', 'keep', ['k','ee','p']), word('them', 'them', ['th','e','m']),
      word('with', 'with', ['w','i','th']), word('me,', 'me', ['m','ee']),
      tricky('so', 'so'), tricky('I', 'I'),
      word('never', 'never', ['n','e','v','er']),
      word('forget.', 'forget', ['f','or','g','e','t']),
      word('Dad', 'dad', ['d','a','d']), word('wore', 'wore', ['w','ore']),
      word('them', 'them', ['th','e','m']), word('that', 'that', ['th','a','t']),
      word('day,', 'day', ['d','ay']), word('hanging', 'hanging', ['h','a','ng','i','ng']),
      word('bright', 'bright', ['b','r','igh','t']), word('on', 'on', ['o','n']),
      word('his', 'his', ['h','i','s']), word('bag.', 'bag', ['b','a','g']),
    ],
    imageUrl: '/illustrations/5_1/page8.png', audioUrl: '/sounds/sentences/L5_1_p8.mp3',
  },

  // ── QUIZ ──
  {
    type: 'quiz',
    questions: [
      { question: 'Where did the boy go with Dad?',
        options: [{ label: 'the shore', isCorrect: true }, { label: 'the shop', isCorrect: false }, { label: 'school', isCorrect: false }] },
      { question: 'What did the boy find on the path?',
        options: [{ label: 'a stone', isCorrect: true }, { label: 'a shell', isCorrect: false }, { label: 'a coin', isCorrect: false }] },
      { question: 'What did he make for Dad?',
        options: [{ label: 'a gift with wire and stones', isCorrect: true }, { label: 'a cake', isCorrect: false }, { label: 'a card', isCorrect: false }] },
    ],
  },

  // ── SOUND SPOTLIGHTS ──
  { type: 'sound_spotlight', sound: 'ore', items: [
    { word: 'shore', imageUrl: '/images/words/shore.png', focusIndex: 2 },
    { word: 'more', imageUrl: '/images/words/more.png', focusIndex: 1 },
    { word: 'before', imageUrl: '/images/words/before.png', focusIndex: 3 },
    { word: 'explore', imageUrl: '/images/words/explore.png', focusIndex: 4 },
  ] },
  { type: 'sound_spotlight', sound: 'ire', items: [
    { word: 'fire', imageUrl: '/images/words/fire.png', focusIndex: 1 },
    { word: 'wire', imageUrl: '/images/words/wire.png', focusIndex: 1 },
    { word: 'tired', imageUrl: '/images/words/tired.png', focusIndex: 1 },
    { word: 'hire', imageUrl: '/images/words/hire.png', focusIndex: 1 },
  ] },

  // ── WORD READING ──
  { type: 'word_reading', words: [
    word('shore', 'shore', ['sh','ore']), word('fire', 'fire', ['f','ire']),
    word('wire', 'wire', ['w','ire']), word('more', 'more', ['m','ore']),
    word('before', 'before', ['b','e','f','ore']), word('explore', 'explore', ['e','x','p','l','ore']),
  ] },

  // ── TRICKY WORDS ──
  { type: 'tricky_words', words: [
    tricky('said', 'said'), tricky('was', 'was'), tricky('once', 'once'),
    tricky('they', 'they'), tricky('through', 'through'), tricky('knew', 'knew'),
  ] },

  // ── NONSENSE WORDS ──
  { type: 'nonsense_words', words: [
    word('blore', 'blore', ['b','l','ore']), word('glire', 'glire', ['g','l','ire']),
    word('frore', 'frore', ['f','r','ore']), word('snire', 'snire', ['s','n','ire']),
    word('plore', 'plore', ['p','l','ore']), word('drire', 'drire', ['d','r','ire']),
    word('spore', 'spore', ['s','p','ore']), word('twire', 'twire', ['t','w','ire']),
  ] },

  // ── SPELLING ──
  { type: 'spelling', words: [
    { word: 'shore', imageUrl: '/images/words/shore.png', letters: ['sh','ore'] },
    { word: 'fire', imageUrl: '/images/words/fire.png', letters: ['f','ire'] },
    { word: 'wire', imageUrl: '/images/words/wire.png', letters: ['w','ire'] },
    { word: 'more', imageUrl: '/images/words/more.png', letters: ['m','ore'] },
  ] },

  // ── STORY ORDERING ──
  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/5_1/page1.png', label: 'He found a stone.', correctIndex: 0 },
    { imageUrl: '/illustrations/5_1/page3.png', label: 'He explored the shore.', correctIndex: 1 },
    { imageUrl: '/illustrations/5_1/page4.png', label: 'He found shells.', correctIndex: 2 },
    { imageUrl: '/illustrations/5_1/page5.png', label: 'He kept a stone.', correctIndex: 3 },
    { imageUrl: '/illustrations/5_1/page7.png', label: 'He made a gift.', correctIndex: 4 },
    { imageUrl: '/illustrations/5_1/page8.png', label: 'He gave it to Dad.', correctIndex: 5 },
  ] },

  // ── DRAWING + CERTIFICATE ──
  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'Before the Shore' },
];


// ═══════════════════════════════════════════════════════════════════════════
// L5.2 — "Near the Door"
// Focus sounds: ear, oor (Dual Perspective structure)
// Setting: Nordic cabin, girl finds a fox
// ═══════════════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════════════
// L5.2 — "Near the Door"
// Focus sounds: ear, oor (Image-driven pivot rewrite — outdoor journey)
// Setting: Snowy Nordic woods, child meets fox, rabbit, deer
// REWRITE 2026-05-05: Re-aligned text to rendered images (outdoor 3-animal
// journey). Critique-writer base + -ed reintroduced where natural.
// ═══════════════════════════════════════════════════════════════════════════

export const BOOK_L5_2_PAGES: InteractivePage[] = [
  { type: 'cover', title: 'Near the Door', subtitle: 'Level 5 · Reading Together', imageUrl: '/illustrations/5_2/cover.png' },

  {
    type: 'sound_grid',
    focusSounds: ['ear', 'oor'],
    allSounds: L5_ALL_SOUNDS,
  },

  {
    type: 'vocab_preview',
    words: [
      word('near', 'near', ['n','ear']),
      word('hear', 'hear', ['h','ear']),
      word('dear', 'dear', ['d','ear']),
      word('clear', 'clear', ['c','l','ear']),
      word('fear', 'fear', ['f','ear']),
      word('door', 'door', ['d','oor']),
      word('floor', 'floor', ['f','l','oor']),
    ],
  },

  // Page 1 — Setting out, hearing a crunch
  {
    type: 'story',
    sentences: [
      'Dad sat at the fire in his thick wool socks.',
      'I stood near the door with my coat and hat.',
      'It was cool outside, and I could hear a soft crunch.',
      'I put my ear to the door and heard it again.',
      'What could it be out there in the snow?',
    ],
    words: [
      word('Dad', 'dad', ['d','a','d']), word('sat', 'sat', ['s','a','t']),
      word('at', 'at', ['a','t']), tricky('the', 'the'),
      word('fire', 'fire', ['f','ire']),
      word('in', 'in', ['i','n']), word('his', 'his', ['h','i','s']),
      word('thick', 'thick', ['th','i','ck']),
      word('wool', 'wool', ['w','oo','l']),
      word('socks.', 'socks', ['s','o','ck','s']),
      tricky('I', 'I'), word('stood', 'stood', ['s','t','oo','d']),
      word('near', 'near', ['n','ear']), tricky('the', 'the'),
      word('door', 'door', ['d','oor']),
      word('with', 'with', ['w','i','th']), word('my', 'my', ['m','y']),
      word('coat', 'coat', ['c','oa','t']),
      word('and', 'and', ['a','n','d']),
      word('hat.', 'hat', ['h','a','t']),
      word('It', 'it', ['i','t']), tricky('was', 'was'),
      word('cool', 'cool', ['c','oo','l']),
      word('outside,', 'outside', ['ou','t','s','i-e','d']),
      word('and', 'and', ['a','n','d']), tricky('I', 'I'),
      tricky('could', 'could'), word('hear', 'hear', ['h','ear']),
      tricky('a', 'a'), word('soft', 'soft', ['s','o','f','t']),
      word('crunch.', 'crunch', ['c','r','u','n','ch']),
      tricky('I', 'I'), word('put', 'put', ['p','u','t']),
      word('my', 'my', ['m','y']),
      word('ear', 'ear', ['ear']), tricky('to', 'to'),
      tricky('the', 'the'), word('door', 'door', ['d','oor']),
      word('and', 'and', ['a','n','d']),
      tricky('heard', 'heard'),
      word('it', 'it', ['i','t']), tricky('again.', 'again'),
      word('What', 'what', ['wh','a','t']),
      tricky('could', 'could'), word('it', 'it', ['i','t']),
      word('be', 'be', ['b','ee']), word('out', 'out', ['ou','t']),
      tricky('there', 'there'), word('in', 'in', ['i','n']),
      tricky('the', 'the'), word('snow?', 'snow', ['s','n','ow']),
    ],
    imageUrl: '/illustrations/5_2/page1.png', audioUrl: '/sounds/sentences/L5_2_p1.mp3',
  },

  // Page 2 — Stepping out, spotting a tail
  {
    type: 'story',
    sentences: [
      'I pulled the door wide and stepped out into the woods.',
      'It was still cool, and I could hear that crunch again.',
      'It was near a tall pine tree, but I could not see more.',
      'A red tail peeked out, swayed, then went still.',
      'I crept near.',
    ],
    words: [
      tricky('I', 'I'), tricky('pulled', 'pulled'),
      tricky('the', 'the'), word('door', 'door', ['d','oor']),
      word('wide', 'wide', ['w','i-e','d']),
      word('and', 'and', ['a','n','d']),
      word('stepped', 'stepped', ['s','t','e','pp','ed']),
      word('out', 'out', ['ou','t']), tricky('into', 'into'),
      tricky('the', 'the'), word('woods.', 'woods', ['w','oo','d','s']),
      word('It', 'it', ['i','t']), tricky('was', 'was'),
      word('still', 'still', ['s','t','i','ll']),
      word('cool,', 'cool', ['c','oo','l']),
      word('and', 'and', ['a','n','d']), tricky('I', 'I'),
      tricky('could', 'could'), word('hear', 'hear', ['h','ear']),
      word('that', 'that', ['th','a','t']),
      word('crunch', 'crunch', ['c','r','u','n','ch']),
      tricky('again.', 'again'),
      word('It', 'it', ['i','t']), tricky('was', 'was'),
      word('near', 'near', ['n','ear']), tricky('a', 'a'),
      tricky('tall', 'tall'), word('pine', 'pine', ['p','i-e','n']),
      word('tree,', 'tree', ['t','r','ee']),
      word('but', 'but', ['b','u','t']), tricky('I', 'I'),
      tricky('could', 'could'), word('not', 'not', ['n','o','t']),
      word('see', 'see', ['s','ee']), word('more.', 'more', ['m','ore']),
      tricky('A', 'a'), word('red', 'red', ['r','e','d']),
      word('tail', 'tail', ['t','ai','l']),
      word('peeked', 'peeked', ['p','ee','k','ed']),
      word('out,', 'out', ['ou','t']),
      word('swayed,', 'swayed', ['s','w','ay','ed']),
      word('then', 'then', ['th','e','n']),
      word('went', 'went', ['w','e','n','t']),
      word('still.', 'still', ['s','t','i','ll']),
      tricky('I', 'I'), word('crept', 'crept', ['c','r','e','p','t']),
      word('near.', 'near', ['n','ear']),
    ],
    imageUrl: '/illustrations/5_2/page2.png', audioUrl: '/sounds/sentences/L5_2_p2.mp3',
  },

  // Page 3 — The fox revealed
  {
    type: 'story',
    sentences: [
      'Out popped a fox, with neat paws and sharp ears.',
      'He looked at me and sat down in the soft snow.',
      'I felt a bit of fear, but I did not run.',
      'I spoke soft and clear.',
      '"Dear fox, you are safe with me."',
    ],
    words: [
      word('Out', 'out', ['ou','t']),
      word('popped', 'popped', ['p','o','pp','ed']),
      tricky('a', 'a'), word('fox,', 'fox', ['f','o','x']),
      word('with', 'with', ['w','i','th']),
      word('neat', 'neat', ['n','ea','t']),
      word('paws', 'paws', ['p','aw','s']),
      word('and', 'and', ['a','n','d']),
      word('sharp', 'sharp', ['sh','ar','p']),
      word('ears.', 'ears', ['ear','s']),
      tricky('He', 'he'), word('looked', 'looked', ['l','oo','k','ed']),
      word('at', 'at', ['a','t']), word('me', 'me', ['m','ee']),
      word('and', 'and', ['a','n','d']),
      word('sat', 'sat', ['s','a','t']),
      word('down', 'down', ['d','ow','n']),
      word('in', 'in', ['i','n']), tricky('the', 'the'),
      word('soft', 'soft', ['s','o','f','t']),
      word('snow.', 'snow', ['s','n','ow']),
      tricky('I', 'I'), word('felt', 'felt', ['f','e','l','t']),
      tricky('a', 'a'), word('bit', 'bit', ['b','i','t']),
      tricky('of', 'of'), word('fear,', 'fear', ['f','ear']),
      word('but', 'but', ['b','u','t']), tricky('I', 'I'),
      word('did', 'did', ['d','i','d']),
      word('not', 'not', ['n','o','t']),
      word('run.', 'run', ['r','u','n']),
      tricky('I', 'I'), word('spoke', 'spoke', ['s','p','o-e','k']),
      word('soft', 'soft', ['s','o','f','t']),
      word('and', 'and', ['a','n','d']),
      word('clear.', 'clear', ['c','l','ear']),
      word('Dear', 'dear', ['d','ear']),
      word('fox,', 'fox', ['f','o','x']),
      tricky('you', 'you'), tricky('are', 'are'),
      word('safe', 'safe', ['s','a-e','f']),
      word('with', 'with', ['w','i','th']),
      word('me.', 'me', ['m','ee']),
    ],
    imageUrl: '/illustrations/5_2/page3.png', audioUrl: '/sounds/sentences/L5_2_p3.mp3',
  },

  // Page 4 — Tap by the stream, two long ears
  {
    type: 'story',
    sentences: [
      'The fox sniffed and trotted off into the trees.',
      'Then a soft tap came near a rock at the stream.',
      'Two long ears stuck up, pink and still in the snow.',
      'A rabbit was near the rock, under a thin sheet of snow.',
      'I kept still.',
    ],
    words: [
      tricky('The', 'the'), word('fox', 'fox', ['f','o','x']),
      word('sniffed', 'sniffed', ['s','n','i','ff','ed']),
      word('and', 'and', ['a','n','d']),
      word('trotted', 'trotted', ['t','r','o','tt','ed']),
      word('off', 'off', ['o','ff']),
      tricky('into', 'into'), tricky('the', 'the'),
      word('trees.', 'trees', ['t','r','ee','s']),
      word('Then', 'then', ['th','e','n']),
      tricky('a', 'a'), word('soft', 'soft', ['s','o','f','t']),
      word('tap', 'tap', ['t','a','p']),
      word('came', 'came', ['c','a-e','m']),
      word('near', 'near', ['n','ear']),
      tricky('a', 'a'), word('rock', 'rock', ['r','o','ck']),
      word('at', 'at', ['a','t']), tricky('the', 'the'),
      word('stream.', 'stream', ['s','t','r','ea','m']),
      tricky('Two', 'two'), word('long', 'long', ['l','o','ng']),
      word('ears', 'ears', ['ear','s']),
      word('stuck', 'stuck', ['s','t','u','ck']),
      word('up,', 'up', ['u','p']),
      word('pink', 'pink', ['p','i','nk']),
      word('and', 'and', ['a','n','d']),
      word('still', 'still', ['s','t','i','ll']),
      word('in', 'in', ['i','n']), tricky('the', 'the'),
      word('snow.', 'snow', ['s','n','ow']),
      tricky('A', 'a'), word('rabbit', 'rabbit', ['r','a','bb','i','t']),
      tricky('was', 'was'),
      word('near', 'near', ['n','ear']), tricky('the', 'the'),
      word('rock,', 'rock', ['r','o','ck']),
      word('under', 'under', ['u','n','d','er']),
      tricky('a', 'a'), word('thin', 'thin', ['th','i','n']),
      word('sheet', 'sheet', ['sh','ee','t']),
      tricky('of', 'of'), word('snow.', 'snow', ['s','n','ow']),
      tricky('I', 'I'), word('kept', 'kept', ['k','e','p','t']),
      word('still.', 'still', ['s','t','i','ll']),
    ],
    imageUrl: '/illustrations/5_2/page4.png', audioUrl: '/sounds/sentences/L5_2_p4.mp3',
  },

  // Page 5 — Rabbit leaps the stream
  {
    type: 'story',
    sentences: [
      'The rabbit sprang from the rock and ran to the stream.',
      'It leapt clear over the water with long, strong legs.',
      'Splash, splash, then the rabbit ran on again.',
      'I called out as it landed safe and kept on.',
      'What a dear, quick rabbit with big pink ears!',
    ],
    words: [
      tricky('The', 'the'), word('rabbit', 'rabbit', ['r','a','bb','i','t']),
      word('sprang', 'sprang', ['s','p','r','a','ng']),
      word('from', 'from', ['f','r','o','m']),
      tricky('the', 'the'), word('rock', 'rock', ['r','o','ck']),
      word('and', 'and', ['a','n','d']),
      word('ran', 'ran', ['r','a','n']), tricky('to', 'to'),
      tricky('the', 'the'), word('stream.', 'stream', ['s','t','r','ea','m']),
      word('It', 'it', ['i','t']),
      word('leapt', 'leapt', ['l','ea','p','t']),
      word('clear', 'clear', ['c','l','ear']),
      tricky('over', 'over'), tricky('the', 'the'),
      tricky('water', 'water'),
      word('with', 'with', ['w','i','th']),
      word('long,', 'long', ['l','o','ng']),
      word('strong', 'strong', ['s','t','r','o','ng']),
      word('legs.', 'legs', ['l','e','g','s']),
      word('Splash,', 'splash', ['s','p','l','a','sh']),
      word('splash,', 'splash', ['s','p','l','a','sh']),
      word('then', 'then', ['th','e','n']),
      tricky('the', 'the'), word('rabbit', 'rabbit', ['r','a','bb','i','t']),
      word('ran', 'ran', ['r','a','n']),
      word('on', 'on', ['o','n']), tricky('again.', 'again'),
      tricky('I', 'I'), tricky('called', 'called'),
      word('out', 'out', ['ou','t']),
      word('as', 'as', ['a','s']), word('it', 'it', ['i','t']),
      word('landed', 'landed', ['l','a','n','d','ed']),
      word('safe', 'safe', ['s','a-e','f']),
      word('and', 'and', ['a','n','d']),
      word('kept', 'kept', ['k','e','p','t']),
      word('on.', 'on', ['o','n']),
      word('What', 'what', ['wh','a','t']),
      tricky('a', 'a'), word('dear,', 'dear', ['d','ear']),
      word('quick', 'quick', ['qu','i','ck']),
      word('rabbit', 'rabbit', ['r','a','bb','i','t']),
      word('with', 'with', ['w','i','th']),
      word('big', 'big', ['b','i','g']),
      word('pink', 'pink', ['p','i','nk']),
      word('ears!', 'ears', ['ear','s']),
    ],
    imageUrl: '/illustrations/5_2/page5.png', audioUrl: '/sounds/sentences/L5_2_p5.mp3',
  },

  // Page 6 — Twigs in the snow that turn into antlers
  {
    type: 'story',
    sentences: [
      'Next, I spotted two dark points on a pale mound of snow.',
      'They poked up out of the snow like small twigs.',
      'I went near and a snort came from under the mound.',
      'Was it a log, or was it a deer?',
      'I waited, still as a rock, and did not fear.',
    ],
    words: [
      word('Next,', 'next', ['n','e','x','t']),
      tricky('I', 'I'), word('spotted', 'spotted', ['s','p','o','tt','ed']),
      tricky('two', 'two'), word('dark', 'dark', ['d','ar','k']),
      word('points', 'points', ['p','oi','n','t','s']),
      word('on', 'on', ['o','n']),
      tricky('a', 'a'), word('pale', 'pale', ['p','a-e','l']),
      word('mound', 'mound', ['m','ou','n','d']),
      tricky('of', 'of'), word('snow.', 'snow', ['s','n','ow']),
      tricky('They', 'they'),
      word('poked', 'poked', ['p','o-e','k','ed']),
      word('up', 'up', ['u','p']),
      word('out', 'out', ['ou','t']), tricky('of', 'of'),
      tricky('the', 'the'), word('snow', 'snow', ['s','n','ow']),
      tricky('like', 'like'), tricky('small', 'small'),
      word('twigs.', 'twigs', ['t','w','i','g','s']),
      tricky('I', 'I'), word('went', 'went', ['w','e','n','t']),
      word('near', 'near', ['n','ear']),
      word('and', 'and', ['a','n','d']),
      tricky('a', 'a'), word('snort', 'snort', ['s','n','or','t']),
      word('came', 'came', ['c','a-e','m']),
      word('from', 'from', ['f','r','o','m']),
      word('under', 'under', ['u','n','d','er']),
      tricky('the', 'the'), word('mound.', 'mound', ['m','ou','n','d']),
      tricky('Was', 'was'), word('it', 'it', ['i','t']),
      tricky('a', 'a'), word('log,', 'log', ['l','o','g']),
      word('or', 'or', ['or']), tricky('was', 'was'),
      word('it', 'it', ['i','t']), tricky('a', 'a'),
      word('deer?', 'deer', ['d','ee','r']),
      tricky('I', 'I'), word('waited,', 'waited', ['w','ai','t','ed']),
      word('still', 'still', ['s','t','i','ll']),
      word('as', 'as', ['a','s']), tricky('a', 'a'),
      word('rock,', 'rock', ['r','o','ck']),
      word('and', 'and', ['a','n','d']),
      word('did', 'did', ['d','i','d']),
      word('not', 'not', ['n','o','t']),
      word('fear.', 'fear', ['f','ear']),
    ],
    imageUrl: '/illustrations/5_2/page6.png', audioUrl: '/sounds/sentences/L5_2_p6.mp3',
  },

  // Page 7 — The deer revealed
  {
    type: 'story',
    sentences: [
      'Out stepped a deer, tall and grand, with big antlers.',
      'He stood near me and did not run.',
      'I spoke clear and slow.',
      '"Dear deer," I said, "we will not harm you."',
      'He looked at me, then stepped off into the trees.',
    ],
    words: [
      word('Out', 'out', ['ou','t']),
      word('stepped', 'stepped', ['s','t','e','pp','ed']),
      tricky('a', 'a'), word('deer,', 'deer', ['d','ee','r']),
      tricky('tall', 'tall'),
      word('and', 'and', ['a','n','d']),
      word('grand,', 'grand', ['g','r','a','n','d']),
      word('with', 'with', ['w','i','th']),
      word('big', 'big', ['b','i','g']),
      word('antlers.', 'antlers', ['a','n','t','l','er','s']),
      tricky('He', 'he'), word('stood', 'stood', ['s','t','oo','d']),
      word('near', 'near', ['n','ear']),
      word('me', 'me', ['m','ee']),
      word('and', 'and', ['a','n','d']),
      word('did', 'did', ['d','i','d']),
      word('not', 'not', ['n','o','t']),
      word('run.', 'run', ['r','u','n']),
      tricky('I', 'I'), word('spoke', 'spoke', ['s','p','o-e','k']),
      word('clear', 'clear', ['c','l','ear']),
      word('and', 'and', ['a','n','d']),
      word('slow.', 'slow', ['s','l','ow']),
      word('Dear', 'dear', ['d','ear']),
      word('deer,', 'deer', ['d','ee','r']),
      tricky('I', 'I'), tricky('said,', 'said'),
      tricky('we', 'we'), word('will', 'will', ['w','i','ll']),
      word('not', 'not', ['n','o','t']),
      word('harm', 'harm', ['h','ar','m']),
      tricky('you.', 'you'),
      tricky('He', 'he'), word('looked', 'looked', ['l','oo','k','ed']),
      word('at', 'at', ['a','t']), word('me,', 'me', ['m','ee']),
      word('then', 'then', ['th','e','n']),
      word('stepped', 'stepped', ['s','t','e','pp','ed']),
      word('off', 'off', ['o','ff']),
      tricky('into', 'into'), tricky('the', 'the'),
      word('trees.', 'trees', ['t','r','ee','s']),
    ],
    imageUrl: '/illustrations/5_2/page7.png', audioUrl: '/sounds/sentences/L5_2_p7.mp3',
  },

  // Page 8 — Back to the cabin door
  {
    type: 'story',
    sentences: [
      'Snow dusted my coat as I ran back to the door.',
      'Dad waited there, warm from the fire and keen to hear.',
      '"I saw a fox, a rabbit, and a deer!"',
      'We sat on the floor indoors and read at the fire.',
    ],
    words: [
      word('Snow', 'snow', ['s','n','ow']),
      word('dusted', 'dusted', ['d','u','s','t','ed']),
      word('my', 'my', ['m','y']),
      word('coat', 'coat', ['c','oa','t']),
      word('as', 'as', ['a','s']), tricky('I', 'I'),
      word('ran', 'ran', ['r','a','n']),
      word('back', 'back', ['b','a','ck']),
      tricky('to', 'to'), tricky('the', 'the'),
      word('door.', 'door', ['d','oor']),
      word('Dad', 'dad', ['d','a','d']),
      word('waited', 'waited', ['w','ai','t','ed']),
      tricky('there,', 'there'),
      word('warm', 'warm', ['w','ar','m']),
      word('from', 'from', ['f','r','o','m']),
      tricky('the', 'the'), word('fire', 'fire', ['f','ire']),
      word('and', 'and', ['a','n','d']),
      word('keen', 'keen', ['k','ee','n']),
      tricky('to', 'to'), word('hear.', 'hear', ['h','ear']),
      tricky('I', 'I'), tricky('saw', 'saw'),
      tricky('a', 'a'), word('fox,', 'fox', ['f','o','x']),
      tricky('a', 'a'), word('rabbit,', 'rabbit', ['r','a','bb','i','t']),
      word('and', 'and', ['a','n','d']),
      tricky('a', 'a'), word('deer!', 'deer', ['d','ee','r']),
      tricky('We', 'we'), word('sat', 'sat', ['s','a','t']),
      word('on', 'on', ['o','n']), tricky('the', 'the'),
      word('floor', 'floor', ['f','l','oor']),
      word('indoors', 'indoors', ['i','n','d','oor','s']),
      word('and', 'and', ['a','n','d']),
      word('read', 'read', ['r','ea','d']),
      word('at', 'at', ['a','t']), tricky('the', 'the'),
      word('fire.', 'fire', ['f','ire']),
    ],
    imageUrl: '/illustrations/5_2/page8.png', audioUrl: '/sounds/sentences/L5_2_p8.mp3',
  },

  // ── QUIZ ──
  {
    type: 'quiz',
    questions: [
      { question: 'What three animals did the child see in the woods?',
        options: [{ label: 'a fox, a rabbit, and a deer', isCorrect: true }, { label: 'a wolf, a hare, and a bear', isCorrect: false }, { label: 'a cat, a dog, and a sheep', isCorrect: false }] },
      { question: 'How did the rabbit get over the stream?',
        options: [{ label: 'it leapt clear over the water', isCorrect: true }, { label: 'it ran around the stream', isCorrect: false }, { label: 'it stayed near the rock', isCorrect: false }] },
      { question: 'How did the child speak to the deer?',
        options: [{ label: 'clear and slow', isCorrect: true }, { label: 'fast and loud', isCorrect: false }, { label: 'with a big shout', isCorrect: false }] },
    ],
  },

  // ── SOUND SPOTLIGHTS ──
  { type: 'sound_spotlight', sound: 'ear', items: [
    { word: 'near', imageUrl: '/images/words/near.png', focusIndex: 1 },
    { word: 'hear', imageUrl: '/images/words/hear.png', focusIndex: 1 },
    { word: 'dear', imageUrl: '/images/words/dear.png', focusIndex: 1 },
    { word: 'fear', imageUrl: '/images/words/fear.png', focusIndex: 1 },
  ] },
  { type: 'sound_spotlight', sound: 'oor', items: [
    { word: 'door', imageUrl: '/images/words/door.png', focusIndex: 1 },
    { word: 'floor', imageUrl: '/images/words/floor.png', focusIndex: 2 },
    { word: 'poor', imageUrl: '/images/words/poor.png', focusIndex: 1 },
    { word: 'moor', imageUrl: '/images/words/moor.png', focusIndex: 1 },
  ] },

  { type: 'word_reading', words: [
    word('near', 'near', ['n','ear']), word('dear', 'dear', ['d','ear']),
    word('fear', 'fear', ['f','ear']), word('door', 'door', ['d','oor']),
    word('floor', 'floor', ['f','l','oor']), word('clear', 'clear', ['c','l','ear']),
  ] },

  { type: 'tricky_words', words: [
    tricky('was', 'was'), tricky('could', 'could'), tricky('again', 'again'),
    tricky('there', 'there'), tricky('over', 'over'), tricky('water', 'water'),
  ] },

  { type: 'nonsense_words', words: [
    word('snear', 'snear', ['s','n','ear']), word('gloor', 'gloor', ['g','l','oor']),
    word('drear', 'drear', ['d','r','ear']), word('ploor', 'ploor', ['p','l','oor']),
    word('frear', 'frear', ['f','r','ear']), word('broor', 'broor', ['b','r','oor']),
    word('spear', 'spear', ['s','p','ear']), word('troor', 'troor', ['t','r','oor']),
  ] },

  { type: 'spelling', words: [
    { word: 'near', imageUrl: '/images/words/near.png', letters: ['n','ear'] },
    { word: 'dear', imageUrl: '/images/words/dear.png', letters: ['d','ear'] },
    { word: 'door', imageUrl: '/images/words/door.png', letters: ['d','oor'] },
    { word: 'fear', imageUrl: '/images/words/fear.png', letters: ['f','ear'] },
  ] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/5_2/page1.png', label: 'I heard a crunch near the door.', correctIndex: 0 },
    { imageUrl: '/illustrations/5_2/page2.png', label: 'I crept out into the woods.', correctIndex: 1 },
    { imageUrl: '/illustrations/5_2/page3.png', label: 'I met a soft red fox.', correctIndex: 2 },
    { imageUrl: '/illustrations/5_2/page5.png', label: 'A rabbit leapt the stream.', correctIndex: 3 },
    { imageUrl: '/illustrations/5_2/page7.png', label: 'A tall deer stepped out.', correctIndex: 4 },
    { imageUrl: '/illustrations/5_2/page8.png', label: 'I ran back to Dad.', correctIndex: 5 },
  ] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'Near the Door' },
];


// ═══════════════════════════════════════════════════════════════════════════
// L5.3 — "Sure She Can"
// Focus sounds: ure, tion (Embedded Instructions structure)
// Setting: Jaipur kite festival, girl makes a kite with Dadaji
// ═══════════════════════════════════════════════════════════════════════════

export const BOOK_L5_3_PAGES: InteractivePage[] = [
  { type: 'cover', title: 'Sure She Can', subtitle: 'Level 5 · Reading Together', imageUrl: '/illustrations/5_3/cover.png' },

  {
    type: 'sound_grid',
    focusSounds: ['ure', 'tion'],
    allSounds: L5_ALL_SOUNDS,
    note: "The letters 'ure' have two sounds! At the end of a word it can sound like 'yoor' (as in pure) OR like 'ur' (as in nature). You'll meet both in this book.",
  },

  {
    type: 'vocab_preview',
    words: [
      tricky('sure', 'sure'),
      word('pure', 'pure', ['p','ure']),
      word('attention', 'attention', ['a','tt','e','n','tion']),
      word('section', 'section', ['s','e','c','tion']),
      word('direction', 'direction', ['d','i','r','e','c','tion']),
      tricky('concentration', 'concentration'),
      tricky('frustration', 'frustration'),
      word('action', 'action', ['a','c','tion']),
    ],
  },

  // Page 1
  {
    type: 'story',
    sentences: ['Kites of every colour filled the sky over Jaipur.', 'Red and green and blue, they soared and spun and dipped in the clear winter air.', 'The girl stood on the rooftop and watched with wide eyes.', 'She wanted to fly a kite more than anything.', 'But she did not own one.'],
    words: [
      word('Kites', 'kites', ['k','i-e','t','s']), tricky('of', 'of'),
      word('every', 'every', ['e','v','r','ee']),
      word('colour', 'colour', ['c','o','l','er']),
      word('filled', 'filled', ['f','i','ll','ed']),
      tricky('the', 'the'), word('sky', 'sky', ['s','k','y']),
      tricky('over', 'over'), tricky('Jaipur.', 'jaipur'),
      word('Red', 'red', ['r','e','d']), word('and', 'and', ['a','n','d']),
      word('green', 'green', ['g','r','ee','n']), word('and', 'and', ['a','n','d']),
      word('blue,', 'blue', ['b','l','ue']), tricky('they', 'they'),
      word('soared', 'soared', ['s','ore','ed']),
      word('and', 'and', ['a','n','d']), word('spun', 'spun', ['s','p','u','n']),
      word('and', 'and', ['a','n','d']), word('dipped', 'dipped', ['d','i','pp','ed']),
      word('in', 'in', ['i','n']), tricky('the', 'the'),
      word('clear', 'clear', ['c','l','ear']),
      word('winter', 'winter', ['w','i','n','t','er']),
      word('air.', 'air', ['air']),
      tricky('The', 'the'), word('girl', 'girl', ['g','ir','l']),
      word('stood', 'stood', ['s','t','oo','d']), word('on', 'on', ['o','n']),
      tricky('the', 'the'), word('rooftop', 'rooftop', ['r','oo','f','t','o','p']),
      word('and', 'and', ['a','n','d']), word('watched', 'watched', ['w','a','t','ch','ed']),
      word('with', 'with', ['w','i','th']), word('wide', 'wide', ['w','i-e','d']),
      tricky('eyes.', 'eyes'),
      tricky('She', 'she'), word('wanted', 'wanted', ['w','a','n','t','e','d']),
      tricky('to', 'to'), word('fly', 'fly', ['f','l','y']),
      tricky('a', 'a'), word('kite', 'kite', ['k','i-e','t']),
      word('more', 'more', ['m','ore']), word('than', 'than', ['th','a','n']),
      tricky('anything.', 'anything'),
      word('But', 'but', ['b','u','t']), tricky('she', 'she'),
      word('did', 'did', ['d','i','d']), word('not', 'not', ['n','o','t']),
      word('own', 'own', ['ow','n']), tricky('one.', 'one'),
    ],
    imageUrl: '/illustrations/5_3/page1.png', audioUrl: '/sounds/sentences/L5_3_p1.mp3',
  },

  // Page 2
  {
    type: 'story',
    sentences: ['Dadaji sat near the wall, smiling at all the kites.', 'He held up a thin sheet of paper and two bamboo sticks.', '"We can make one," he said.', '"I can show you the instructions.', 'Pay close attention and follow each step."', 'She felt a rush of joy.'],
    words: [
      word('Dadaji', 'dadaji', ['d','a','d','a','j','ee']),
      word('sat', 'sat', ['s','a','t']), word('near', 'near', ['n','ear']),
      tricky('the', 'the'), tricky('wall,', 'wall'),
      word('smiling', 'smiling', ['s','m','i-e','l','i','ng']),
      word('at', 'at', ['a','t']), tricky('all', 'all'),
      tricky('the', 'the'), word('kites.', 'kites', ['k','i-e','t','s']),
      tricky('He', 'he'), word('held', 'held', ['h','e','l','d']),
      word('up', 'up', ['u','p']), tricky('a', 'a'),
      word('thin', 'thin', ['th','i','n']), word('sheet', 'sheet', ['sh','ee','t']),
      tricky('of', 'of'), tricky('paper', 'paper'),
      word('and', 'and', ['a','n','d']), tricky('two', 'two'),
      word('bamboo', 'bamboo', ['b','a','m','b','oo']),
      word('sticks.', 'sticks', ['s','t','i','ck','s']),
      tricky('We', 'we'), word('can', 'can', ['c','a','n']),
      word('make', 'make', ['m','a-e','k']), tricky('one,', 'one'),
      tricky('he', 'he'), tricky('said.', 'said'),
      tricky('I', 'I'), word('can', 'can', ['c','a','n']),
      word('show', 'show', ['sh','ow']), tricky('you', 'you'),
      tricky('the', 'the'), tricky('instructions.', 'instructions'),
      word('Pay', 'pay', ['p','ay']), word('close', 'close', ['c','l','o-e','s']),
      word('attention', 'attention', ['a','tt','e','n','tion']),
      word('and', 'and', ['a','n','d']), word('follow', 'follow', ['f','o','ll','ow']),
      word('each', 'each', ['ea','ch']), word('step.', 'step', ['s','t','e','p']),
      tricky('She', 'she'), word('felt', 'felt', ['f','e','l','t']),
      tricky('a', 'a'), word('rush', 'rush', ['r','u','sh']),
      tricky('of', 'of'), word('joy.', 'joy', ['j','oy']),
    ],
    imageUrl: '/illustrations/5_3/page2.png', audioUrl: '/sounds/sentences/L5_3_p2.mp3',
  },

  // Page 3
  {
    type: 'story',
    sentences: ['"Step one," said Dadaji.', '"Lay the sticks in a cross shape.', 'Tie them at this section here — that is the frame."', 'With great concentration, the girl tied the sticks.', '"Perfect!" said Dadaji.', '"Now pass the string around each point."'],
    words: [
      word('Step', 'step', ['s','t','e','p']), tricky('one,', 'one'),
      tricky('said', 'said'), word('Dadaji.', 'dadaji', ['d','a','d','a','j','ee']),
      word('Lay', 'lay', ['l','ay']), tricky('the', 'the'),
      word('sticks', 'sticks', ['s','t','i','ck','s']), word('in', 'in', ['i','n']),
      tricky('a', 'a'), word('cross', 'cross', ['c','r','o','ss']),
      word('shape.', 'shape', ['sh','a-e','p']),
      word('Tie', 'tie', ['t','ie']), word('them', 'them', ['th','e','m']),
      word('at', 'at', ['a','t']), word('this', 'this', ['th','i','s']),
      word('section', 'section', ['s','e','c','tion']),
      tricky('here', 'here'), word('that', 'that', ['th','a','t']),
      tricky('is', 'is'), tricky('the', 'the'),
      word('frame.', 'frame', ['f','r','a-e','m']),
      word('With', 'with', ['w','i','th']), word('great', 'great', ['g','r','ea','t']),
      tricky('concentration,', 'concentration'),
      tricky('the', 'the'), word('girl', 'girl', ['g','ir','l']),
      word('tied', 'tied', ['t','ie','d']), tricky('the', 'the'),
      word('sticks.', 'sticks', ['s','t','i','ck','s']),
      tricky('Perfect!', 'perfect'),
      tricky('said', 'said'), word('Dadaji.', 'dadaji', ['d','a','d','a','j','ee']),
      word('Now', 'now', ['n','ow']), word('pass', 'pass', ['p','a','ss']),
      tricky('the', 'the'), word('string', 'string', ['s','t','r','i','ng']),
      word('around', 'around', ['a','r','ou','n','d']),
      word('each', 'each', ['ea','ch']), word('point.', 'point', ['p','oi','n','t']),
    ],
    imageUrl: '/illustrations/5_3/page3.png', audioUrl: '/sounds/sentences/L5_3_p3.mp3',
  },

  {
    type: 'story',
    sentences: ['"Step two," said Dadaji.', '"Lay the paper flat on the frame.', 'Fold each section over the string and press it down."', 'The girl worked fast.', 'But the paper slipped.', 'There was a rip — a long split ran right through the kite.', 'Her heart sank.'],
    words: [
      word('Step', 'step', ['s','t','e','p']), tricky('two,', 'two'),
      tricky('said', 'said'), word('Dadaji.', 'dadaji', ['d','a','d','a','j','ee']),
      word('Lay', 'lay', ['l','ay']), tricky('the', 'the'),
      tricky('paper', 'paper'),
      word('flat', 'flat', ['f','l','a','t']), word('on', 'on', ['o','n']),
      tricky('the', 'the'), word('frame.', 'frame', ['f','r','a-e','m']),
      word('Fold', 'fold', ['f','o','l','d']), word('each', 'each', ['ea','ch']),
      word('section', 'section', ['s','e','c','tion']),
      tricky('over', 'over'), tricky('the', 'the'),
      word('string', 'string', ['s','t','r','i','ng']),
      word('and', 'and', ['a','n','d']), word('press', 'press', ['p','r','e','ss']),
      word('it', 'it', ['i','t']), word('down.', 'down', ['d','ow','n']),
      tricky('The', 'the'), word('girl', 'girl', ['g','ir','l']),
      word('worked', 'worked', ['w','er','k','ed']),
      word('fast.', 'fast', ['f','a','s','t']),
      word('But', 'but', ['b','u','t']), tricky('the', 'the'),
      tricky('paper', 'paper'),
      word('slipped.', 'slipped', ['s','l','i','pp','ed']),
      tricky('There', 'there'), tricky('was', 'was'),
      tricky('a', 'a'), word('rip', 'rip', ['r','i','p']),
      tricky('a', 'a'), word('long', 'long', ['l','o','ng']),
      word('split', 'split', ['s','p','l','i','t']),
      word('ran', 'ran', ['r','a','n']), word('right', 'right', ['r','igh','t']),
      tricky('through', 'through'), tricky('the', 'the'),
      word('kite.', 'kite', ['k','i-e','t']),
      word('Her', 'her', ['h','er']), word('heart', 'heart', ['h','ear','t']),
      word('sank.', 'sank', ['s','a','nk']),
    ],
    imageUrl: '/illustrations/5_3/page4.png', audioUrl: '/sounds/sentences/L5_3_p4.mp3',
  },

  {
    type: 'story',
    sentences: ['The girl crumpled the torn paper in her hands.', '"I am full of frustration!" she said.', '"I give up!"', 'Dadaji did not rush.', 'He sat with a calm look on his face and waited.', '"Are you sure you want to stop?" he said softly.', '"We are not done yet."'],
    words: [
      tricky('The', 'the'), word('girl', 'girl', ['g','ir','l']),
      word('crumpled', 'crumpled', ['c','r','u','m','p','l','ed']),
      tricky('the', 'the'), word('torn', 'torn', ['t','ore','n']),
      tricky('paper', 'paper'),
      word('in', 'in', ['i','n']), word('her', 'her', ['h','er']),
      word('hands.', 'hands', ['h','a','n','d','s']),
      tricky('I', 'I'), word('am', 'am', ['a','m']),
      word('full', 'full', ['f','u','ll']), tricky('of', 'of'),
      tricky('frustration!', 'frustration'),
      tricky('she', 'she'), tricky('said.', 'said'),
      tricky('I', 'I'), word('give', 'give', ['g','i','v']),
      word('up!', 'up', ['u','p']),
      word('Dadaji', 'dadaji', ['d','a','d','a','j','ee']),
      word('did', 'did', ['d','i','d']), word('not', 'not', ['n','o','t']),
      word('rush.', 'rush', ['r','u','sh']),
      tricky('He', 'he'), word('sat', 'sat', ['s','a','t']),
      word('with', 'with', ['w','i','th']), tricky('a', 'a'),
      word('calm', 'calm', ['c','ar','m']),
      word('look', 'look', ['l','oo','k']), word('on', 'on', ['o','n']),
      word('his', 'his', ['h','i','s']), word('face', 'face', ['f','a-e','s']),
      word('and', 'and', ['a','n','d']), word('waited.', 'waited', ['w','ai','t','e','d']),
      tricky('Are', 'are'), tricky('you', 'you'),
      tricky('sure', 'sure'), tricky('you', 'you'),
      word('want', 'want', ['w','a','n','t']), tricky('to', 'to'),
      word('stop?', 'stop', ['s','t','o','p']),
      tricky('he', 'he'), tricky('said', 'said'),
      word('softly.', 'softly', ['s','o','f','t','l','ee']),
      tricky('We', 'we'), tricky('are', 'are'),
      word('not', 'not', ['n','o','t']), word('done', 'done', ['d','u','n']),
      word('yet.', 'yet', ['y','e','t']),
    ],
    imageUrl: '/illustrations/5_3/page5.png', audioUrl: '/sounds/sentences/L5_3_p5.mp3',
  },

  {
    type: 'story',
    sentences: ['The girl took a long breath and tried again.', '"Slow action this time," said Dadaji.', '"Press each section flat before you move on.', 'Work in one direction only."', 'She worked with great care.', 'She pressed. She smoothed. She waited.', 'The paper held.', '"It is working!" she cried.'],
    words: [
      tricky('The', 'the'), word('girl', 'girl', ['g','ir','l']),
      word('took', 'took', ['t','oo','k']), tricky('a', 'a'),
      word('long', 'long', ['l','o','ng']), word('breath', 'breath', ['b','r','e','th']),
      word('and', 'and', ['a','n','d']), word('tried', 'tried', ['t','r','ie','d']),
      word('again.', 'again', ['a','g','ai','n']),
      word('Slow', 'slow', ['s','l','ow']),
      word('action', 'action', ['a','c','tion']),
      word('this', 'this', ['th','i','s']), word('time,', 'time', ['t','i-e','m']),
      tricky('said', 'said'), word('Dadaji.', 'dadaji', ['d','a','d','a','j','ee']),
      word('Press', 'press', ['p','r','e','ss']), word('each', 'each', ['ea','ch']),
      word('section', 'section', ['s','e','c','tion']),
      word('flat', 'flat', ['f','l','a','t']),
      word('before', 'before', ['b','e','f','ore']),
      tricky('you', 'you'), word('move', 'move', ['m','oo','v']),
      word('on.', 'on', ['o','n']),
      word('Work', 'work', ['w','er','k']), word('in', 'in', ['i','n']),
      tricky('one', 'one'),
      word('direction', 'direction', ['d','i','r','e','c','tion']),
      word('only.', 'only', ['o','n','l','ee']),
      tricky('She', 'she'), word('worked', 'worked', ['w','er','k','ed']),
      word('with', 'with', ['w','i','th']), word('great', 'great', ['g','r','ea','t']),
      word('care.', 'care', ['c','are']),
      tricky('She', 'she'), word('pressed.', 'pressed', ['p','r','e','ss','ed']),
      tricky('She', 'she'), word('smoothed.', 'smoothed', ['s','m','oo','th','ed']),
      tricky('She', 'she'), word('waited.', 'waited', ['w','ai','t','e','d']),
      tricky('The', 'the'), tricky('paper', 'paper'),
      word('held.', 'held', ['h','e','l','d']),
      word('It', 'it', ['i','t']), tricky('is', 'is'),
      word('working!', 'working', ['w','er','k','i','ng']),
      tricky('she', 'she'), word('cried.', 'cried', ['c','r','ie','d']),
    ],
    imageUrl: '/illustrations/5_3/page6.png', audioUrl: '/sounds/sentences/L5_3_p6.mp3',
  },

  {
    type: 'story',
    sentences: ['At last, the kite was done.', '"Look at the picture we made!" she cried.', 'Dadaji tied the string to the centre.', '"Now for the action!" he said.', '"Run in that direction and let the wind catch it!"', 'She ran with all her might and let the string out.'],
    words: [
      word('At', 'at', ['a','t']), word('last,', 'last', ['l','a','s','t']),
      tricky('the', 'the'), word('kite', 'kite', ['k','i-e','t']),
      tricky('was', 'was'), word('done.', 'done', ['d','u','n']),
      word('Look', 'look', ['l','oo','k']), word('at', 'at', ['a','t']),
      tricky('the', 'the'), word('picture', 'picture', ['p','i','c','t','ure']),
      tricky('we', 'we'), word('made!', 'made', ['m','a-e','d']),
      tricky('she', 'she'), word('cried.', 'cried', ['c','r','ie','d']),
      word('Dadaji', 'dadaji', ['d','a','d','a','j','ee']),
      word('tied', 'tied', ['t','ie','d']), tricky('the', 'the'),
      word('string', 'string', ['s','t','r','i','ng']),
      tricky('to', 'to'), tricky('the', 'the'),
      word('centre.', 'centre', ['s','e','n','t','er']),
      word('Now', 'now', ['n','ow']), word('for', 'for', ['f','or']),
      tricky('the', 'the'), word('action!', 'action', ['a','c','tion']),
      tricky('he', 'he'), tricky('said.', 'said'),
      word('Run', 'run', ['r','u','n']), word('in', 'in', ['i','n']),
      word('that', 'that', ['th','a','t']),
      word('direction', 'direction', ['d','i','r','e','c','tion']),
      word('and', 'and', ['a','n','d']), word('let', 'let', ['l','e','t']),
      tricky('the', 'the'), word('wind', 'wind', ['w','i','n','d']),
      word('catch', 'catch', ['c','a','tch']),
      word('it!', 'it', ['i','t']),
      tricky('She', 'she'), word('ran', 'ran', ['r','a','n']),
      word('with', 'with', ['w','i','th']), tricky('all', 'all'),
      word('her', 'her', ['h','er']), word('might', 'might', ['m','igh','t']),
      word('and', 'and', ['a','n','d']), word('let', 'let', ['l','e','t']),
      tricky('the', 'the'), word('string', 'string', ['s','t','r','i','ng']),
      word('out.', 'out', ['ou','t']),
    ],
    imageUrl: '/illustrations/5_3/page7.png', audioUrl: '/sounds/sentences/L5_3_p7.mp3',
  },

  {
    type: 'story',
    sentences: ['The kite shot up into the pure blue sky.', 'It soared higher and higher!', '"Woh Kata!" cheered the people on the next rooftop.', 'Dadaji clapped his hands with joy.', 'The girl watched her kite spin and dance over the pink city.', '"Pure joy!" she cried. "Pure joy!"'],
    words: [
      tricky('The', 'the'), word('kite', 'kite', ['k','i-e','t']),
      word('shot', 'shot', ['sh','o','t']), word('up', 'up', ['u','p']),
      tricky('into', 'into'),
      tricky('the', 'the'), word('pure', 'pure', ['p','ure']),
      word('blue', 'blue', ['b','l','ue']), word('sky.', 'sky', ['s','k','y']),
      word('It', 'it', ['i','t']), word('soared', 'soared', ['s','ore','ed']),
      word('higher', 'higher', ['h','igh','er']),
      word('and', 'and', ['a','n','d']), word('higher!', 'higher', ['h','igh','er']),
      word('Woh', 'woh', ['w','o','h']), word('Kata!', 'kata', ['k','a','t','a']),
      word('cheered', 'cheered', ['ch','ear','ed']),
      tricky('the', 'the'), tricky('people', 'people'),
      word('on', 'on', ['o','n']), tricky('the', 'the'),
      word('next', 'next', ['n','e','x','t']),
      word('rooftop.', 'rooftop', ['r','oo','f','t','o','p']),
      word('Dadaji', 'dadaji', ['d','a','d','a','j','ee']),
      word('clapped', 'clapped', ['c','l','a','pp','ed']),
      word('his', 'his', ['h','i','s']), word('hands', 'hands', ['h','a','n','d','s']),
      word('with', 'with', ['w','i','th']), word('joy.', 'joy', ['j','oy']),
      tricky('The', 'the'), word('girl', 'girl', ['g','ir','l']),
      word('watched', 'watched', ['w','a','t','ch','ed']),
      word('her', 'her', ['h','er']), word('kite', 'kite', ['k','i-e','t']),
      word('spin', 'spin', ['s','p','i','n']), word('and', 'and', ['a','n','d']),
      word('dance', 'dance', ['d','a','n','s']),
      tricky('over', 'over'), tricky('the', 'the'),
      word('pink', 'pink', ['p','i','nk']),
      word('city.', 'city', ['s','i','t','ee']),
      word('Pure', 'pure', ['p','ure']), word('joy!', 'joy', ['j','oy']),
      tricky('she', 'she'), word('cried.', 'cried', ['c','r','ie','d']),
      word('Pure', 'pure', ['p','ure']), word('joy!', 'joy', ['j','oy']),
    ],
    imageUrl: '/illustrations/5_3/page8.png', audioUrl: '/sounds/sentences/L5_3_p8.mp3',
  },

  // ── QUIZ ──
  {
    type: 'quiz',
    questions: [
      { question: 'What did the girl want to do?',
        options: [{ label: 'fly a kite', isCorrect: true }, { label: 'fly a plane', isCorrect: false }, { label: 'paint a picture', isCorrect: false }] },
      { question: 'What happened to the paper?',
        options: [{ label: 'it ripped', isCorrect: true }, { label: 'it flew away', isCorrect: false }, { label: 'it got wet', isCorrect: false }] },
      { question: 'How did the girl feel at the end?',
        options: [{ label: 'pure joy', isCorrect: true }, { label: 'frustrated', isCorrect: false }, { label: 'tired', isCorrect: false }] },
    ],
  },

  { type: 'sound_spotlight', sound: 'ure',
    explanation: "The letters 'ure' make two different sounds. Tap each one to hear!",
    variants: [
      { audioKey: 'ure_yoor', label: "sounds 'yoor'", example: 'pure' },
      { audioKey: 'ure_ur',   label: "sounds 'ur'",   example: 'nature' },
    ],
    items: [
      // /jʊər/ — 'yoor' words: the 'y'-glide before 'ure' is triggered by
      // certain preceding consonants (p, c/k, m, s+e, etc). 'lure' /lʊər/
      // doesn't qualify — no /j/ glide after 'l' — so it lives elsewhere.
      // 'sure' is also excluded: its 's' is irregular (/ʃ/) and it lives
      // in the vocab tricky list.
      { word: 'pure',   imageUrl: '/images/words/pure.png',   focusIndex: 1, morphSplit: 1, variant: 'ure_yoor' },
      { word: 'cure',   imageUrl: '/images/words/cure.png',   focusIndex: 1, morphSplit: 1, variant: 'ure_yoor' },
      { word: 'secure', imageUrl: '/images/words/secure.png', focusIndex: 3, morphSplit: 3, variant: 'ure_yoor' },
      // /ər/ — 'ur' words: sound like nat-ure, pict-ure, fut-ure
      { word: 'nature',  imageUrl: '/images/words/nature.png',  focusIndex: 3, morphSplit: 3, variant: 'ure_ur' },
      { word: 'picture', imageUrl: '/images/words/picture.png', focusIndex: 4, morphSplit: 4, variant: 'ure_ur' },
      { word: 'future',  imageUrl: '/images/words/future.png',  focusIndex: 3, morphSplit: 3, variant: 'ure_ur' },
    ],
  },
  { type: 'sound_spotlight', sound: 'tion', items: [
    { word: 'action', imageUrl: '/images/words/action.png', focusIndex: 2 },
    { word: 'section', imageUrl: '/images/words/section.png', focusIndex: 3 },
    { word: 'station', imageUrl: '/images/words/station.png', focusIndex: 3 },
    { word: 'direction', imageUrl: '/images/words/direction.png', focusIndex: 5 },
  ] },

  { type: 'word_reading', words: [
    tricky('sure', 'sure'), word('pure', 'pure', ['p','ure']),
    word('action', 'action', ['a','c','tion']), word('section', 'section', ['s','e','c','tion']),
    word('direction', 'direction', ['d','i','r','e','c','tion']),
    tricky('frustration', 'frustration'),
  ] },

  { type: 'tricky_words', words: [
    tricky('said', 'said'), tricky('was', 'was'), tricky('they', 'they'),
    tricky('people', 'people'), tricky('through', 'through'), tricky('over', 'over'),
  ] },

  { type: 'nonsense_words', words: [
    word('plure', 'plure', ['p','l','ure']), word('tration', 'tration', ['t','r','a','tion']),
    word('brure', 'brure', ['b','r','ure']), word('snection', 'snection', ['s','n','e','c','tion']),
    word('frure', 'frure', ['f','r','ure']), word('draction', 'draction', ['d','r','a','c','tion']),
    word('glure', 'glure', ['g','l','ure']), word('prection', 'prection', ['p','r','e','c','tion']),
  ] },

  { type: 'spelling', words: [
    { word: 'sure', imageUrl: '/images/words/sure.png', letters: ['sh','ure'] },
    { word: 'pure', imageUrl: '/images/words/pure.png', letters: ['p','ure'] },
    { word: 'action', imageUrl: '/images/words/action.png', letters: ['a','c','tion'] },
    { word: 'section', imageUrl: '/images/words/section.png', letters: ['s','e','c','tion'] },
  ] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/5_3/page1.png', label: 'She watched the kites.', correctIndex: 0 },
    { imageUrl: '/illustrations/5_3/page2.png', label: 'Dadaji showed the instructions.', correctIndex: 1 },
    { imageUrl: '/illustrations/5_3/page4.png', label: 'The paper ripped!', correctIndex: 2 },
    { imageUrl: '/illustrations/5_3/page5.png', label: 'She felt frustrated.', correctIndex: 3 },
    { imageUrl: '/illustrations/5_3/page6.png', label: 'She tried again.', correctIndex: 4 },
    { imageUrl: '/illustrations/5_3/page8.png', label: 'The kite flew! Pure joy!', correctIndex: 5 },
  ] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'Sure She Can' },
];


// ═══════════════════════════════════════════════════════════════════════════
// L5.4 — "A Place for Me"
// Focus sounds: review of all L5 sounds (Before/After Contrast structure)
// Setting: Salvador, Brazil — celebration/carnival
// ═══════════════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════════════
// L5.4 — "A Place for Me"
// Focus sounds: review of all L5 sounds (Lost-and-Found at the market structure)
// Setting: Bahian/Brazilian sunny market street with fruit stalls
// REWRITE 2026-05-05: image-driven pivot — text now matches actual rendered
// images (sunny market street with fruit stalls), removed non-decodable words
// (celebration, colourful, alone, dance, music, laughter, every, acarajé,
// together, walked, surprised, children, evening, watching).
// ═══════════════════════════════════════════════════════════════════════════

export const BOOK_L5_4_PAGES: InteractivePage[] = [
  { type: 'cover', title: 'A Place for Me', subtitle: 'Level 5 · Reading Together', imageUrl: '/illustrations/5_4/cover.png' },

  {
    type: 'sound_grid',
    focusSounds: ['ore', 'oor', 'ire', 'ear', 'ure', 'tion'],
    allSounds: L5_ALL_SOUNDS,
  },

  {
    type: 'vocab_preview',
    words: [
      word('door', 'door', ['d','oor']),
      word('near', 'near', ['n','ear']),
      word('pear', 'pear', ['p','ear']),
      word('photo', 'photo', ['ph','o','t','o']),
      word('pure', 'pure', ['p','ure']),
      word('knelt', 'knelt', ['kn','e','l','t']),
      word('wrong', 'wrong', ['wr','o','ng']),
      word('wrap', 'wrap', ['wr','a','p']),
    ],
  },

  // Page 1
  {
    type: 'story',
    sentences: [
      'Dad and I came to a bright market street.',
      'Doors stood open, with flowers over rails on each floor.',
      'Dad went to a stall, and I sat near a door.',
      'I did not know anyone and felt a bit left out.',
    ],
    words: [
      word('Dad', 'dad', ['d','a','d']), word('and', 'and', ['a','n','d']),
      tricky('I', 'I'), word('came', 'came', ['c','a-e','m']),
      tricky('to', 'to'), tricky('a', 'a'),
      word('bright', 'bright', ['b','r','igh','t']),
      word('market', 'market', ['m','ar','k','e','t']),
      word('street.', 'street', ['s','t','r','ee','t']),
      word('Doors', 'doors', ['d','oor','s']),
      word('stood', 'stood', ['s','t','oo','d']),
      word('open,', 'open', ['o','p','e','n']),
      word('with', 'with', ['w','i','th']),
      word('flowers', 'flowers', ['f','l','ow','er','s']),
      tricky('over', 'over'), word('rails', 'rails', ['r','ai','l','s']),
      word('on', 'on', ['o','n']), word('each', 'each', ['ea','ch']),
      word('floor.', 'floor', ['f','l','oor']),
      word('Dad', 'dad', ['d','a','d']),
      word('went', 'went', ['w','e','n','t']),
      tricky('to', 'to'), tricky('a', 'a'),
      word('stall,', 'stall', ['s','t','all']),
      word('and', 'and', ['a','n','d']), tricky('I', 'I'),
      word('sat', 'sat', ['s','a','t']),
      word('near', 'near', ['n','ear']),
      tricky('a', 'a'), word('door.', 'door', ['d','oor']),
      tricky('I', 'I'), word('did', 'did', ['d','i','d']),
      word('not', 'not', ['n','o','t']),
      word('know', 'know', ['kn','ow']),
      tricky('anyone', 'anyone'),
      word('and', 'and', ['a','n','d']),
      word('felt', 'felt', ['f','e','l','t']),
      tricky('a', 'a'), word('bit', 'bit', ['b','i','t']),
      word('left', 'left', ['l','e','f','t']),
      word('out.', 'out', ['ou','t']),
    ],
    imageUrl: '/illustrations/5_4/page1.png', audioUrl: '/sounds/sentences/L5_4_p1.mp3',
  },

  // Page 2
  {
    type: 'story',
    sentences: [
      'I could hear chat and calls from each stall and door.',
      'I went the wrong way and slid by the pears.',
      'Men and mums looked at them, but no one saw me.',
      'I felt my fear rise and I went back.',
    ],
    words: [
      tricky('I', 'I'), tricky('could', 'could'),
      word('hear', 'hear', ['h','ear']),
      word('chat', 'chat', ['ch','a','t']),
      word('and', 'and', ['a','n','d']),
      word('calls', 'calls', ['c','all','s']),
      word('from', 'from', ['f','r','o','m']),
      word('each', 'each', ['ea','ch']),
      word('stall', 'stall', ['s','t','all']),
      word('and', 'and', ['a','n','d']),
      word('door.', 'door', ['d','oor']),
      tricky('I', 'I'), word('went', 'went', ['w','e','n','t']),
      tricky('the', 'the'), word('wrong', 'wrong', ['wr','o','ng']),
      word('way', 'way', ['w','ay']),
      word('and', 'and', ['a','n','d']),
      word('slid', 'slid', ['s','l','i','d']),
      word('by', 'by', ['b','y']), tricky('the', 'the'),
      word('pears.', 'pears', ['p','ear','s']),
      word('Men', 'men', ['m','e','n']),
      word('and', 'and', ['a','n','d']),
      word('mums', 'mums', ['m','u','m','s']),
      word('looked', 'looked', ['l','oo','k','ed']),
      word('at', 'at', ['a','t']), word('them,', 'them', ['th','e','m']),
      word('but', 'but', ['b','u','t']),
      word('no', 'no', ['n','o']), tricky('one', 'one'),
      word('saw', 'saw', ['s','aw']),
      word('me.', 'me', ['m','ee']),
      tricky('I', 'I'), word('felt', 'felt', ['f','e','l','t']),
      word('my', 'my', ['m','y']),
      word('fear', 'fear', ['f','ear']),
      word('rise', 'rise', ['r','i-e','s']),
      word('and', 'and', ['a','n','d']),
      tricky('I', 'I'), word('went', 'went', ['w','e','n','t']),
      word('back.', 'back', ['b','a','ck']),
    ],
    imageUrl: '/illustrations/5_4/page2.png', audioUrl: '/sounds/sentences/L5_4_p2.mp3',
  },

  // Page 3
  {
    type: 'story',
    sentences: [
      'I sat on a step by a tall brown door.',
      'People were near, but no one came to chat.',
      'I shut my eyes and counted to ten, very slow.',
      'I did not want to cry, but I was tired.',
    ],
    words: [
      tricky('I', 'I'), word('sat', 'sat', ['s','a','t']),
      word('on', 'on', ['o','n']), tricky('a', 'a'),
      word('step', 'step', ['s','t','e','p']),
      word('by', 'by', ['b','y']), tricky('a', 'a'),
      tricky('tall', 'tall'),
      word('brown', 'brown', ['b','r','ow','n']),
      word('door.', 'door', ['d','oor']),
      tricky('People', 'people'), tricky('were', 'were'),
      word('near,', 'near', ['n','ear']),
      word('but', 'but', ['b','u','t']),
      word('no', 'no', ['n','o']), tricky('one', 'one'),
      word('came', 'came', ['c','a-e','m']),
      tricky('to', 'to'), word('chat.', 'chat', ['ch','a','t']),
      tricky('I', 'I'), word('shut', 'shut', ['sh','u','t']),
      word('my', 'my', ['m','y']),
      tricky('eyes', 'eyes'),
      word('and', 'and', ['a','n','d']),
      word('counted', 'counted', ['c','ou','n','t','ed']),
      tricky('to', 'to'), word('ten,', 'ten', ['t','e','n']),
      word('very', 'very', ['v','e','r','y']),
      word('slow.', 'slow', ['s','l','ow']),
      tricky('I', 'I'), word('did', 'did', ['d','i','d']),
      word('not', 'not', ['n','o','t']),
      word('want', 'want', ['w','a','n','t']),
      tricky('to', 'to'),
      word('cry,', 'cry', ['c','r','y']),
      word('but', 'but', ['b','u','t']), tricky('I', 'I'),
      tricky('was', 'was'),
      word('tired.', 'tired', ['t','ire','d']),
    ],
    imageUrl: '/illustrations/5_4/page3.png', audioUrl: '/sounds/sentences/L5_4_p3.mp3',
  },

  // Page 4
  {
    type: 'story',
    sentences: [
      'Then a boy came by and sat down near me.',
      'He gave me a big grin and held out his hand.',
      '"Do you want to look at that stall?" he said.',
      'I went with him, and my fear went away.',
    ],
    words: [
      word('Then', 'then', ['th','e','n']), tricky('a', 'a'),
      word('boy', 'boy', ['b','oy']),
      word('came', 'came', ['c','a-e','m']),
      word('by', 'by', ['b','y']),
      word('and', 'and', ['a','n','d']),
      word('sat', 'sat', ['s','a','t']),
      word('down', 'down', ['d','ow','n']),
      word('near', 'near', ['n','ear']),
      word('me.', 'me', ['m','ee']),
      tricky('He', 'he'), word('gave', 'gave', ['g','a-e','v']),
      word('me', 'me', ['m','ee']), tricky('a', 'a'),
      word('big', 'big', ['b','i','g']),
      word('grin', 'grin', ['g','r','i','n']),
      word('and', 'and', ['a','n','d']),
      word('held', 'held', ['h','e','l','d']),
      word('out', 'out', ['ou','t']),
      word('his', 'his', ['h','i','s']),
      word('hand.', 'hand', ['h','a','n','d']),
      tricky('Do', 'do'), tricky('you', 'you'),
      word('want', 'want', ['w','a','n','t']),
      tricky('to', 'to'),
      word('look', 'look', ['l','oo','k']),
      word('at', 'at', ['a','t']),
      word('that', 'that', ['th','a','t']),
      word('stall?', 'stall', ['s','t','all']),
      tricky('he', 'he'), tricky('said.', 'said'),
      tricky('I', 'I'), word('went', 'went', ['w','e','n','t']),
      word('with', 'with', ['w','i','th']),
      word('him,', 'him', ['h','i','m']),
      word('and', 'and', ['a','n','d']),
      word('my', 'my', ['m','y']),
      word('fear', 'fear', ['f','ear']),
      word('went', 'went', ['w','e','n','t']),
      word('away.', 'away', ['a','w','ay']),
    ],
    imageUrl: '/illustrations/5_4/page4.png', audioUrl: '/sounds/sentences/L5_4_p4.mp3',
  },

  // Page 5
  {
    type: 'story',
    sentences: [
      'We met a man at a stall of pears and melons.',
      'He let us hold a melon, and it was big.',
      'My new pal put it on top like a hat.',
      'I chose a ripe pear, and we paid the man.',
      'He gave us a small portion.',
    ],
    words: [
      tricky('We', 'we'), word('met', 'met', ['m','e','t']),
      tricky('a', 'a'), word('man', 'man', ['m','a','n']),
      word('at', 'at', ['a','t']), tricky('a', 'a'),
      word('stall', 'stall', ['s','t','all']),
      tricky('of', 'of'), word('pears', 'pears', ['p','ear','s']),
      word('and', 'and', ['a','n','d']),
      word('melons.', 'melons', ['m','e','l','o','n','s']),
      tricky('He', 'he'), word('let', 'let', ['l','e','t']),
      word('us', 'us', ['u','s']),
      word('hold', 'hold', ['h','o','l','d']),
      tricky('a', 'a'), word('melon,', 'melon', ['m','e','l','o','n']),
      word('and', 'and', ['a','n','d']),
      word('it', 'it', ['i','t']), tricky('was', 'was'),
      word('big.', 'big', ['b','i','g']),
      word('My', 'my', ['m','y']), word('new', 'new', ['n','ew']),
      word('pal', 'pal', ['p','a','l']),
      tricky('put', 'put'), word('it', 'it', ['i','t']),
      word('on', 'on', ['o','n']), word('top', 'top', ['t','o','p']),
      tricky('like', 'like'), tricky('a', 'a'),
      word('hat.', 'hat', ['h','a','t']),
      tricky('I', 'I'),
      word('chose', 'chose', ['ch','o-e','s']),
      tricky('a', 'a'),
      word('ripe', 'ripe', ['r','i-e','p']),
      word('pear,', 'pear', ['p','ear']),
      word('and', 'and', ['a','n','d']),
      tricky('we', 'we'), word('paid', 'paid', ['p','ai','d']),
      tricky('the', 'the'), word('man.', 'man', ['m','a','n']),
      tricky('He', 'he'), word('gave', 'gave', ['g','a-e','v']),
      word('us', 'us', ['u','s']), tricky('a', 'a'),
      tricky('small', 'small'),
      word('portion.', 'portion', ['p','or','tion']),
    ],
    imageUrl: '/illustrations/5_4/page5.png', audioUrl: '/sounds/sentences/L5_4_p5.mp3',
  },

  // Page 6
  {
    type: 'story',
    sentences: [
      'We sat on the steps and ate the pear and melon.',
      'Sweet, wet bits ran on my chin and on my shirt.',
      'We both smiled more and more, with pure joy inside.',
      'When we were done, we slid the peels in a bin.',
    ],
    words: [
      tricky('We', 'we'), word('sat', 'sat', ['s','a','t']),
      word('on', 'on', ['o','n']), tricky('the', 'the'),
      word('steps', 'steps', ['s','t','e','p','s']),
      word('and', 'and', ['a','n','d']),
      word('ate', 'ate', ['a-e','t']),
      tricky('the', 'the'),
      word('pear', 'pear', ['p','ear']),
      word('and', 'and', ['a','n','d']),
      word('melon.', 'melon', ['m','e','l','o','n']),
      word('Sweet,', 'sweet', ['s','w','ee','t']),
      word('wet', 'wet', ['w','e','t']),
      word('bits', 'bits', ['b','i','t','s']),
      word('ran', 'ran', ['r','a','n']),
      word('on', 'on', ['o','n']), word('my', 'my', ['m','y']),
      word('chin', 'chin', ['ch','i','n']),
      word('and', 'and', ['a','n','d']),
      word('on', 'on', ['o','n']), word('my', 'my', ['m','y']),
      word('shirt.', 'shirt', ['sh','ir','t']),
      tricky('We', 'we'),
      word('both', 'both', ['b','o','th']),
      word('smiled', 'smiled', ['s','m','i-e','l','d']),
      word('more', 'more', ['m','ore']),
      word('and', 'and', ['a','n','d']),
      word('more,', 'more', ['m','ore']),
      word('with', 'with', ['w','i','th']),
      word('pure', 'pure', ['p','ure']),
      word('joy', 'joy', ['j','oy']),
      word('inside.', 'inside', ['i','n','s','i-e','d']),
      word('When', 'when', ['wh','e','n']),
      tricky('we', 'we'), tricky('were', 'were'),
      tricky('done,', 'done'),
      tricky('we', 'we'),
      word('slid', 'slid', ['s','l','i','d']),
      tricky('the', 'the'),
      word('peels', 'peels', ['p','ee','l','s']),
      word('in', 'in', ['i','n']), tricky('a', 'a'),
      word('bin.', 'bin', ['b','i','n']),
    ],
    imageUrl: '/illustrations/5_4/page6.png', audioUrl: '/sounds/sentences/L5_4_p6.mp3',
  },

  // Page 7
  {
    type: 'story',
    sentences: [
      'Then my pal said, "Look, Dad is near."',
      'We went down the street, and he ran before me.',
      'We got one more pear and a wrap for Dad.',
      'I said, "Thank you," and he said, "See you soon."',
    ],
    words: [
      word('Then', 'then', ['th','e','n']),
      word('my', 'my', ['m','y']),
      word('pal', 'pal', ['p','a','l']),
      tricky('said,', 'said'),
      word('Look,', 'look', ['l','oo','k']),
      word('Dad', 'dad', ['d','a','d']),
      tricky('is', 'is'), word('near.', 'near', ['n','ear']),
      tricky('We', 'we'), word('went', 'went', ['w','e','n','t']),
      word('down', 'down', ['d','ow','n']),
      tricky('the', 'the'),
      word('street,', 'street', ['s','t','r','ee','t']),
      word('and', 'and', ['a','n','d']),
      tricky('he', 'he'), word('ran', 'ran', ['r','a','n']),
      word('before', 'before', ['b','e','f','ore']),
      word('me.', 'me', ['m','ee']),
      tricky('We', 'we'), word('got', 'got', ['g','o','t']),
      tricky('one', 'one'),
      word('more', 'more', ['m','ore']),
      word('pear', 'pear', ['p','ear']),
      word('and', 'and', ['a','n','d']),
      tricky('a', 'a'),
      word('wrap', 'wrap', ['wr','a','p']),
      word('for', 'for', ['f','or']),
      word('Dad.', 'dad', ['d','a','d']),
      tricky('I', 'I'), tricky('said,', 'said'),
      word('Thank', 'thank', ['th','a','n','k']),
      tricky('you,', 'you'),
      word('and', 'and', ['a','n','d']),
      tricky('he', 'he'), tricky('said,', 'said'),
      word('See', 'see', ['s','ee']),
      tricky('you', 'you'),
      word('soon.', 'soon', ['s','oo','n']),
    ],
    imageUrl: '/illustrations/5_4/page7.png', audioUrl: '/sounds/sentences/L5_4_p7.mp3',
  },

  // Page 8
  {
    type: 'story',
    sentences: [
      'Dad knelt and held me, and I felt safe again.',
      'He got a photo of us with my new pal.',
      'I said, "Can I see him next year?"',
      'Dad said yes, and I waved to the boy.',
      'This street felt like home, and my heart was light.',
    ],
    words: [
      word('Dad', 'dad', ['d','a','d']),
      word('knelt', 'knelt', ['kn','e','l','t']),
      word('and', 'and', ['a','n','d']),
      word('held', 'held', ['h','e','l','d']),
      word('me,', 'me', ['m','ee']),
      word('and', 'and', ['a','n','d']),
      tricky('I', 'I'), word('felt', 'felt', ['f','e','l','t']),
      word('safe', 'safe', ['s','a-e','f']),
      tricky('again.', 'again'),
      tricky('He', 'he'), word('got', 'got', ['g','o','t']),
      tricky('a', 'a'),
      word('photo', 'photo', ['ph','o','t','o']),
      tricky('of', 'of'), word('us', 'us', ['u','s']),
      word('with', 'with', ['w','i','th']),
      word('my', 'my', ['m','y']),
      word('new', 'new', ['n','ew']),
      word('pal.', 'pal', ['p','a','l']),
      tricky('I', 'I'), tricky('said,', 'said'),
      word('Can', 'can', ['c','a','n']),
      tricky('I', 'I'),
      word('see', 'see', ['s','ee']),
      word('him', 'him', ['h','i','m']),
      word('next', 'next', ['n','e','x','t']),
      word('year?', 'year', ['y','ear']),
      word('Dad', 'dad', ['d','a','d']),
      tricky('said', 'said'),
      word('yes,', 'yes', ['y','e','s']),
      word('and', 'and', ['a','n','d']),
      tricky('I', 'I'),
      word('waved', 'waved', ['w','a-e','v','ed']),
      tricky('to', 'to'), tricky('the', 'the'),
      word('boy.', 'boy', ['b','oy']),
      word('This', 'this', ['th','i','s']),
      word('street', 'street', ['s','t','r','ee','t']),
      word('felt', 'felt', ['f','e','l','t']),
      tricky('like', 'like'),
      word('home,', 'home', ['h','o-e','m']),
      word('and', 'and', ['a','n','d']),
      word('my', 'my', ['m','y']),
      tricky('heart', 'heart'),
      tricky('was', 'was'),
      word('light.', 'light', ['l','igh','t']),
    ],
    imageUrl: '/illustrations/5_4/page8.png', audioUrl: '/sounds/sentences/L5_4_p8.mp3',
  },

  // ── QUIZ ──
  {
    type: 'quiz',
    questions: [
      { question: 'Why did the boy feel left out at the start?',
        options: [
          { label: 'he did not know anyone', isCorrect: true },
          { label: 'he had lost a toy', isCorrect: false },
          { label: 'he was hungry', isCorrect: false },
        ] },
      { question: 'What did the new pal share with the boy?',
        options: [
          { label: 'a pear and a melon', isCorrect: true },
          { label: 'a drum', isCorrect: false },
          { label: 'a kite', isCorrect: false },
        ] },
      { question: 'How did the boy feel by the end?',
        options: [
          { label: 'safe, with his heart light', isCorrect: true },
          { label: 'tired and cross', isCorrect: false },
          { label: 'lost again', isCorrect: false },
        ] },
    ],
  },

  // ── SOUND SPOTLIGHTS (review L5 sounds) ──
  { type: 'sound_spotlight', sound: 'oor', items: [
    { word: 'door', imageUrl: '/images/words/door.png', focusIndex: 1 },
    { word: 'floor', imageUrl: '/images/words/floor.png', focusIndex: 2 },
    { word: 'poor', imageUrl: '/images/words/poor.png', focusIndex: 1 },
    { word: 'moor', imageUrl: '/images/words/moor.png', focusIndex: 1 },
  ] },
  { type: 'sound_spotlight', sound: 'ear', items: [
    { word: 'near', imageUrl: '/images/words/near.png', focusIndex: 1 },
    { word: 'pear', imageUrl: '/images/words/pear.png', focusIndex: 1 },
    { word: 'fear', imageUrl: '/images/words/fear.png', focusIndex: 1 },
    { word: 'year', imageUrl: '/images/words/year.png', focusIndex: 1 },
  ] },

  { type: 'word_reading', words: [
    word('door', 'door', ['d','oor']), word('pear', 'pear', ['p','ear']),
    word('pure', 'pure', ['p','ure']), word('photo', 'photo', ['ph','o','t','o']),
    word('knelt', 'knelt', ['kn','e','l','t']), word('wrap', 'wrap', ['wr','a','p']),
  ] },

  { type: 'tricky_words', words: [
    tricky('said', 'said'), tricky('was', 'was'), tricky('could', 'could'),
    tricky('people', 'people'), tricky('anyone', 'anyone'), tricky('heart', 'heart'),
  ] },

  { type: 'nonsense_words', words: [
    word('blore', 'blore', ['b','l','ore']), word('gloor', 'gloor', ['g','l','oor']),
    word('brire', 'brire', ['b','r','ire']), word('snear', 'snear', ['s','n','ear']),
    word('plure', 'plure', ['p','l','ure']), word('tration', 'tration', ['t','r','a','tion']),
    word('phap', 'phap', ['ph','a','p']), word('knet', 'knet', ['kn','e','t']),
  ] },

  { type: 'spelling', words: [
    { word: 'door', imageUrl: '/images/words/door.png', letters: ['d','oor'] },
    { word: 'pear', imageUrl: '/images/words/pear.png', letters: ['p','ear'] },
    { word: 'pure', imageUrl: '/images/words/pure.png', letters: ['p','ure'] },
    { word: 'photo', imageUrl: '/images/words/photo.png', letters: ['ph','o','t','o'] },
  ] },

  { type: 'story_ordering', items: [
    { imageUrl: '/illustrations/5_4/page1.png', label: 'Dad and I came to the market street.', correctIndex: 0 },
    { imageUrl: '/illustrations/5_4/page3.png', label: 'I sat by a tall door, tired.', correctIndex: 1 },
    { imageUrl: '/illustrations/5_4/page4.png', label: 'A boy came and sat near me.', correctIndex: 2 },
    { imageUrl: '/illustrations/5_4/page5.png', label: 'We got a pear and a melon.', correctIndex: 3 },
    { imageUrl: '/illustrations/5_4/page6.png', label: 'We sat and ate, with pure joy.', correctIndex: 4 },
    { imageUrl: '/illustrations/5_4/page8.png', label: 'Dad knelt and held me — safe again.', correctIndex: 5 },
  ] },

  { type: 'drawing', prompt: 'Draw Your Favourite Part' },
  { type: 'certificate', bookTitle: 'A Place for Me' },
];
