// ---------------------------------------------------------------------------
// Picture words for the Level 4-8 sounds — the words a picture-led sheet
// (picture_write, phoneme_frames, missing_grapheme) can honestly draw.
//
// The ledger word banks hold every decodable word, most of them abstract
// ("might", "notion"), and miss whole sounds (tch, kn, ph). This list is
// curated: one concrete, instantly recognisable thing per word, nothing
// against the house values (no witches, weapons, pork, idols/statues).
// Every word still has to pass isAllowed() + hasGraphemeUnit() at the level
// it is used, so a word listed here never leaks onto a lower level.
//
// L8 suffixes (-able, -ous, -cious ...) are deliberately absent: a picture
// of a "table" would teach the wrong thing about the suffix -able. ure has
// no honest pictures either (cure, pure, mature) and stays text-led.
// ---------------------------------------------------------------------------
export const IMAGEABLE = {
  // Level 4
  ay: ['tray', 'hay', 'clay', 'spray', 'crayon', 'jay', 'stingray'],
  ee: ['tree', 'bee', 'sheep', 'feet', 'queen', 'seed', 'jeep', 'wheel', 'teeth', 'sheet'],
  igh: ['light', 'night', 'tights', 'flight', 'highchair'],
  ow: ['snow', 'bow', 'crow', 'bowl', 'window', 'arrow', 'snowman'],
  oo: ['moon', 'spoon', 'boot', 'roof', 'pool', 'zoo', 'broom', 'tooth', 'hoof', 'stool'],
  ar: ['car', 'star', 'shark', 'jar', 'scarf', 'harp', 'cart', 'arm', 'barn', 'card', 'farm'],
  or: ['fork', 'corn', 'horn', 'torch', 'storm', 'thorn', 'cord', 'fort', 'porch'],
  air: ['chair', 'hair', 'stairs', 'pair', 'fair'],
  ir: ['bird', 'girl', 'shirt', 'skirt', 'swirl'],
  ou: ['cloud', 'mouth', 'couch', 'pouch', 'snout', 'ground', 'trout'],
  oy: ['boy', 'toy', 'toys', 'joystick', 'cowboy'],
  wh: ['wheel', 'whisk', 'whistle', 'wheelbarrow'],
  // Level 5
  'a-e': ['cake', 'snake', 'gate', 'cape', 'plane', 'whale', 'tape', 'cave', 'vase', 'skate', 'grapes', 'game'],
  'i-e': ['kite', 'bike', 'slide', 'vine', 'five', 'nine', 'hive', 'pipe', 'smile', 'lime', 'bride', 'tide'],
  'o-e': ['bone', 'rope', 'nose', 'rose', 'stone', 'home', 'cone', 'mole', 'globe', 'hose', 'note'],
  'u-e': ['flute', 'cube', 'tube', 'mule', 'dune', 'prune'],
  ea: ['leaf', 'seal', 'peach', 'beach', 'tea', 'sea', 'bean', 'pea', 'beak', 'wheat', 'teapot', 'meal'],
  ie: ['pie', 'tie', 'magpie'],
  oi: ['coin', 'soil', 'foil', 'oil', 'boil', 'point', 'coins'],
  aw: ['saw', 'paw', 'claw', 'straw', 'yawn', 'hawk', 'jaw', 'prawn', 'lawn', 'crawl', 'shawl'],
  ai: ['rain', 'train', 'snail', 'nail', 'chain', 'tail', 'sail', 'paint', 'hail', 'drain'],
  oa: ['boat', 'coat', 'goat', 'soap', 'road', 'toad', 'toast', 'coal', 'loaf', 'cloak', 'oak'],
  tch: ['match', 'hutch', 'patch', 'ditch', 'stitch', 'switch', 'sketch', 'crutch', 'catch', 'kitchen'],
  dge: ['bridge', 'badge', 'hedge', 'fudge', 'judge', 'ledge', 'sledge', 'wedge', 'edge'],
  kn: ['knee', 'knot', 'knife', 'knock', 'knit', 'kneel', 'knight', 'knob'],
  wr: ['wrist', 'wrap', 'wreath', 'wren', 'write', 'wreck', 'wrench'],
  mb: ['lamb', 'thumb', 'comb', 'climb', 'crumb', 'limb'],
  gn: ['gnome', 'gnat', 'gnaw'],
  // Level 6
  ur: ['nurse', 'purse', 'church', 'turtle', 'burger', 'surf', 'curl', 'turnip', 'hurdle'],
  er: ['hammer', 'ladder', 'letter', 'butter', 'zipper', 'sister', 'winter', 'fern', 'herd'],
  are: ['hare', 'square', 'stare', 'mare'],
  // ow as in cow (L4 above is ow as in snow)
  'ow@6': ['cow', 'owl', 'crown', 'gown', 'town'],
  ew: ['crew', 'screw', 'stew', 'newt', 'jewel', 'chew', 'dew', 'news'],
  ue: ['glue', 'blue', 'clue', 'rescue'],
  ph: ['phone', 'photo', 'dolphin', 'elephant', 'trophy', 'graph', 'alphabet'],
  // Level 7
  ire: ['fire', 'wire', 'bonfire', 'campfire', 'spire', 'umpire'],
  ore: ['shore', 'store', 'snore', 'core', 'score'],
  ear: ['ear', 'beard', 'gear', 'tear', 'earring'],
  oor: ['door', 'floor', 'trapdoor', 'doorbell'],
  tion: ['station', 'potion', 'lotion', 'invitation', 'decoration', 'carnation', 'celebration'],
  // Level 8 — the one suffix that names drawable things
  sion: ['television', 'explosion', 'mansion', 'collision'],
};

// How to draw the words a bare noun would get wrong (artgen subject line).
// Anything not listed is drawn as "a single simple <word>".
export const DESCRIBE = {
  bow: 'a big ribbon bow tied in a loop, like on a present',
  match: 'one wooden matchstick with a red tip, unlit',
  tear: 'a single blue teardrop shape',
  jay: 'a jay bird, blue and brown, perched on a branch',
  crow: 'a black crow bird standing',
  spray: 'a spray bottle squirting a fine mist',
  flight: 'a small aeroplane flying among clouds',
  light: 'a glowing light bulb',
  night: 'a dark blue night sky with a crescent moon and stars',
  storm: 'a dark storm cloud with rain and a lightning bolt',
  fair: 'a funfair big wheel',
  swirl: 'a colourful swirl lollipop',
  ground: 'a patch of brown earth with a small green sprout',
  snout: 'a dog nose and muzzle, close up',
  game: 'a board game with a die and two counters',
  tide: 'waves washing up onto a sandy beach',
  smile: 'a round yellow smiley face with two small solid black oval eyes and a simple curved smile',
  note: 'a folded paper note',
  point: 'a hand pointing with one finger',
  boil: 'a pan of water boiling on a hob, bubbles rising',
  yawn: 'a sleepy child yawning, hand near the mouth',
  crawl: 'a baby in a full-length sleepsuit crawling on hands and knees, small solid black oval eyes',
  catch: 'two hands catching a ball',
  sketch: 'a pencil sketch of a house on a sheet of paper, with a pencil beside it',
  knock: 'a hand knocking on a wooden door',
  kneel: 'a child kneeling on one knee, wearing long trousers that cover the knees and a long-sleeved top',
  write: 'a hand writing with a pencil on paper, no visible letters',
  climb: 'a child climbing a climbing frame, wearing long trousers that cover the knees and a long-sleeved top',
  gnaw: 'a beaver gnawing a log',
  stare: 'a child leaning forward and looking closely at a butterfly, small solid black oval eyes with no white of the eye',
  chew: 'a child chewing an apple',
  dew: 'drops of dew on a green leaf',
  news: 'a folded newspaper with blank grey lines instead of text',
  clue: 'a magnifying glass over a footprint',
  rescue: 'a lifeboat with a ring buoy',
  blue: 'a splash of blue paint',
  surf: 'a surfboard riding a wave',
  curl: 'a curly ribbon',
  herd: 'a small herd of three cows in a field',
  sister: 'a big sister and little brother holding hands, both wearing long trousers that cover the knees and a long-sleeved top',
  winter: 'a snowy winter tree',
  letter: 'a sealed envelope with a stamp',
  judge: 'a judge in a black gown sitting at a bench with a gavel',
  limb: 'a tree branch',
  edge: 'the edge of a grassy cliff',
  ledge: 'a window ledge with a plant pot on it',
  crumb: 'a few bread crumbs next to a slice of bread',
  wreck: 'an old shipwreck on the sea floor',
  wrap: 'a present being wrapped in paper',
  score: 'a football goal with the ball in the net',
  snore: 'a child asleep in bed with wavy snore lines',
  core: 'an apple core',
  store: 'a small shop front with a striped awning',
  shore: 'a sandy shore with gentle waves',
  gear: 'a metal cog gear wheel',
  spire: 'a tall pointed tower spire',
  umpire: 'a cricket umpire in a white coat and hat',
  potion: 'a small glass bottle of colourful medicine',
  lotion: 'a bottle of hand lotion',
  invitation: 'a party invitation card with balloons on it, no writing',
  decoration: 'paper bunting decorations',
  carnation: 'a pink carnation flower',
  celebration: 'a party table with balloons and a cake',
  station: 'a train at a railway station platform',
  explosion: 'a firework bursting in the night sky',
  collision: 'two toy cars bumping into each other',
  mansion: 'a very big grand house with many windows',
  television: 'a television set showing a simple landscape of hills and a sun, no faces',
  graph: 'a simple bar chart',
  alphabet: 'alphabet building blocks, drawn blank with no letters',
  trophy: 'a gold trophy cup',
  photo: 'a printed photograph of a mountain',
  hare: 'a brown hare',
  mare: 'a mother horse with her foal',
  square: 'a red square shape',
  hurdle: 'a running hurdle on a track',
  crutch: 'a single walking crutch',
  ditch: 'a long narrow trench dug in the ground with a little water at the bottom and grass on both sides, seen from the side',
  patch: 'a sewn patch on the knee of jeans',
  stitch: 'a needle and thread making stitches in fabric',
  switch: 'a light switch on a wall',
  hutch: 'a rabbit hutch with a rabbit inside',
  badge: 'a round badge with a star on it',
  hedge: 'a green garden hedge',
  wedge: 'a wedge of cheese',
  sledge: 'a wooden sledge on snow',
  bridge: 'a stone bridge over a river',
  fudge: 'pieces of fudge',
  knit: 'knitting needles with wool',
  knob: 'a round door knob',
  knight: 'a knight in shining armour holding a shield, no weapon',
  wrist: 'a wrist wearing a watch',
  wreath: 'a round green leaf wreath',
  wren: 'a small brown wren bird',
  wrench: 'a metal spanner',
  gnome: 'a garden gnome',
  gnat: 'a tiny flying gnat insect',
  thumb: 'a hand giving a thumbs up',
  meal: 'a plate with a healthy meal of vegetables and rice',
  oil: 'a bottle of cooking oil',
  soil: 'a pile of soil with a spade',
  foil: 'a roll of kitchen foil',
  coins: 'a small stack of coins',
  hail: 'small plain white balls of ice falling from a grey cloud, no faces on anything',
  drain: 'a drain grate in a road',
  coal: 'a few lumps of black coal',
  oak: 'an oak tree',
  cloak: 'a long red hooded cloak on a hanger',
  sail: 'a small sailing boat with a big sail',
  paint: 'a paint pot with a brush',
  bride: 'a bride in a long white modest dress with long sleeves and a headscarf, holding flowers',
  vase: 'a vase of flowers',
  skate: 'a roller skate',
  hive: 'a beehive on a branch, no bees',
  pipe: 'a metal water pipe',
  lime: 'a green lime fruit',
  vine: 'a grape vine',
  hose: 'a garden hose',
  mole: 'a mole poking out of a molehill',
  globe: 'a globe of the world on a stand',
  dune: 'a sand dune in a desert',
  prune: 'a purple prune fruit',
  bean: 'a green bean pod',
  pea: 'a pea pod with peas',
  beak: 'a bird beak, close up',
  wheat: 'a few stalks of golden wheat',
  sea: 'the blue sea with gentle waves',
  tea: 'a cup of tea',
  teapot: 'a teapot',
  magpie: 'a black and white magpie bird',
  tie: 'a school tie',
  prawn: 'a pink prawn',
  hawk: 'a hawk bird',
  lawn: 'a neat green lawn',
  shawl: 'a woollen shawl',
  straw: 'a drinking straw in a cup',
  claw: 'a crab claw',
  jaw: 'a crocodile with its jaw open',
  toast: 'a slice of toast',
  loaf: 'a loaf of bread',
  road: 'a road with a dashed white line',
  tooth: 'a single white tooth',
  stool: 'a wooden stool',
  hoof: 'a horse hoof with a horseshoe',
  roof: 'a house roof with tiles',
  cart: 'a wooden cart with wheels',
  arm: 'a child arm in a long sleeve, flexing',
  cord: 'a long rope cord coiled up',
  fort: 'a toy fort made of wooden blocks',
  thorn: 'a rose stem with a thorn',
  horn: 'a brass horn instrument on its own, nothing else in the picture',
  stairs: 'a staircase',
  pair: 'a pair of socks',
  pouch: 'a small drawstring pouch on its own, nothing else in the picture',
  couch: 'a sofa',
  trout: 'a trout fish seen from the side. Its eye is a single tiny solid black dot, like a full stop, with nothing around it',
  toys: 'a box of toys',
  joystick: 'a game joystick',
  cowboy: 'a boy in a cowboy hat',
  whisk: 'a kitchen whisk',
  whistle: 'a silver whistle',
  wheelbarrow: 'a garden wheelbarrow',
  highchair: 'a baby highchair',
  tights: 'a pair of tights',
  crayon: 'a single crayon',
  stingray: 'a stingray in the sea',
  window: 'a house window with curtains',
  snowman: 'a snowman with a scarf',
  arrow: 'a direction arrow sign',
  bowl: 'an empty bowl',
  clay: 'a lump of modelling clay',
  hay: 'a bale of hay',
  tray: 'a tray with a cup on it',
  seed: 'a seed in a small pot of soil',
  jeep: 'a jeep car',
  wheel: 'a bicycle wheel',
  teeth: 'a row of clean white teeth, just the teeth and pink gums, no lips and no face',
  sheet: 'a folded bed sheet',
  feet: 'two bare feet',
  queen: 'a queen with a crown in a long modest gown with long sleeves',
  shirt: 'a shirt',
  skirt: 'a long skirt',
  girl: 'a girl in a long-sleeved dress and leggings',
  nurse: 'a nurse in a long-sleeved uniform',
  burger: 'a veggie burger',
  turnip: 'a turnip',
  turtle: 'a sea turtle. Every eye is one small solid black oval, with no white of the eye and no ring around it.',
  purse: 'a purse',
  hammer: 'a hammer',
  ladder: 'a ladder',
  butter: 'a block of butter on a dish',
  zipper: 'a zip on a jacket',
  fern: 'a green fern plant',
  owl: 'an owl on a branch',
  cow: 'a cow',
  clown: 'a clown seen from behind a big bunch of balloons that hides the face, with curly red hair, a striped long-sleeved suit and big shoes',
  crown: 'a gold crown',
  gown: 'a long gown dress on a hanger',
  town: 'a small town street of houses',
  crew: 'a ship crew of three adult sailors in long trousers and long sleeves',
  screw: 'a metal screw',
  stew: 'a pot of vegetable stew',
  newt: 'a newt',
  jewel: 'a sparkling jewel',
  glue: 'a glue bottle',
  phone: 'a mobile phone',
  dolphin: 'a dolphin jumping',
  elephant: 'an elephant',
  fire: 'a campfire burning',
  wire: 'a coil of wire',
  bonfire: 'a big bonfire',
  campfire: 'a campfire with logs',
  ear: 'an ear',
  beard: 'a man with a neat beard',
  earring: 'a pair of earrings',
  door: 'a front door',
  floor: 'a wooden floor with a rug',
  trapdoor: 'a trapdoor in a wooden floor',
  doorbell: 'a doorbell button beside a door',
  knee: 'a child knee in trousers, bent',
  knot: 'a knot tied in a rope',
  knife: 'a table butter knife',
  comb: 'a hair comb',
  lamb: 'a lamb',
  gate: 'a garden gate',
  cape: 'a red superhero cape',
  cave: 'a cave in a hillside',
  tape: 'a roll of sticky tape',
  grapes: 'a bunch of grapes',
  five: 'a hand showing five fingers',
  nine: 'nine colourful balloons',
  slide: 'a playground slide',
  bike: 'a bicycle',
  kite: 'a kite in the sky',
  nose: 'a nose',
  rose: 'a red rose',
  home: 'a cosy house',
  cone: 'an ice cream cone',
  stone: 'a smooth grey stone',
  flute: 'a flute',
  cube: 'a blue cube',
  tube: 'a toothpaste tube',
  mule: 'a mule',
  leaf: 'a green leaf',
  seal: 'a seal on a rock',
  peach: 'a peach',
  beach: 'a sandy beach with a bucket and spade',
  pie: 'an apple pie',
  coin: 'a plain gold coin with a blank face, no symbol, no letters, no numbers',
  saw: 'a wood saw',
  paw: 'a dog paw print',
  church: 'a small church building',
  tree: 'a tree',
  bee: 'a bumblebee seen from the side, with small solid black oval eyes',
  sheep: 'a sheep',
  moon: 'a crescent moon',
  spoon: 'a metal spoon on its own, nothing else in the picture',
  boot: 'a wellington boot',
  pool: 'a swimming pool',
  zoo: 'a zoo entrance with animals',
  broom: 'a broom',
  car: 'a car',
  star: 'a yellow star',
  shark: 'a shark',
  jar: 'a jar of jam',
  scarf: 'a striped scarf',
  harp: 'a harp',
  barn: 'a red barn',
  card: 'a greetings card',
  farm: 'a farm with a barn and fields',
  fork: 'a fork',
  corn: 'a corn cob',
  torch: 'a torch shining',
  porch: 'a house porch',
  chair: 'a chair',
  hair: 'the back of a head with long brown plaited hair, no face showing',
  bird: 'a bird',
  cloud: 'a white cloud',
  mouth: 'closed pink lips in a gentle smile, only the lips, nothing else in the picture, no eyes, no face',
  boy: 'a boy wearing long trousers that cover the knees and a long-sleeved top',
  toy: 'a toy train',
  snow: 'snowflakes falling',
  rain: 'rain falling from a cloud',
  train: 'a train',
  snail: 'a snail',
  nail: 'a metal nail',
  chain: 'a metal chain',
  tail: 'a dog wagging its tail',
  boat: 'a boat',
  coat: 'a coat',
  goat: 'a goat',
  soap: 'a bar of soap',
  toad: 'a brown toad seen from the side. Its eye is a single small solid black dot, like a full stop, with nothing around it',
  kitchen: 'a kitchen with a cooker and sink',
  plane: 'an aeroplane',
  whale: 'a whale',
  snake: 'a snake',
  cake: 'a birthday cake',
};

/** Picture words for `grapheme` at `level` (ow is split by level). */
export function imageableFor(grapheme, level) {
  if (grapheme === 'ow' && level >= 6) return IMAGEABLE['ow@6'];
  return IMAGEABLE[grapheme] ?? [];
}

/** Every listed word, for the drawable-noun index. */
export const ALL_IMAGEABLE = [...new Set(Object.values(IMAGEABLE).flat())];

/** The subject line artgen draws for `word`. */
export const describe = (word) => DESCRIBE[word] ?? `a single simple ${word}`;
