// Curated sentences for the concrete nouns in content.mjs NOUNS.
//
// Each sentence is written so the gap word is the only word that fits, and
// the sentence means something to a five-year-old. Generic frames
// ("My ___ is the best in town" filled with "hay") read as nonsense, which
// is exactly what Lynden flagged on 2026-09-21. The decodability guard still
// runs on every sentence at the sheet's level; anything that fails is skipped
// and the old frames are the fallback of last resort.
//
// Keep sentences short, present tense, and built from early graphemes plus
// the taught tricky words (the, a, I, is, to, my, we, he, she, was, you, are,
// said, into, go, no, put, of, her, all, like...).
export const SENTENCES = {
  // ---- L1-2 CVC and simple nouns ----
  ant: ['An ant is on the log.', 'The ant can dig.'],
  axe: ['Dad cuts logs with the axe.'],
  bag: ['Pack the bag for the trip.', 'The bag is full of nuts.'],
  bat: ['A bat naps in the dark.', 'The bat hangs in the shed.'],
  bed: ['I nap on my bed.', 'The cat sits on the bed.'],
  bee: ['A bee buzzes in the garden.', 'The bee lands on the flower.'],
  bell: ['Ring the bell at the door.', 'The bell is big and gold.'],
  bin: ['Put the rubbish in the bin.', 'The bin lid is shut.'],
  bird: ['A bird sings in the tree.', 'The bird has a red beak.'],
  boat: ['The boat floats on the pond.', 'We sail the boat at the beach.'],
  book: ['I read a book at night.', 'This book has ten pages.'],
  boot: ['My boot is full of mud.', 'Put on a boot to go out.'],
  box: ['The cat sits in a box.', 'Put the toys in the box.'],
  bug: ['A bug sits on the leaf.', 'The bug has six legs.'],
  bun: ['I had a jam bun for lunch.', 'The bun is hot from the oven.'],
  bus: ['We go to school on the bus.', 'The bus stops at the shop.'],
  cab: ['Dad got a cab to the station.'],
  cap: ['I put my cap on in the sun.', 'The cap is red.'],
  cat: ['The cat sits on the mat.', 'My cat naps in the sun.'],
  chick: ['The chick is soft and yellow.', 'A chick pecks at the corn.'],
  chip: ['I had a chip with my fish.'],
  clock: ['The clock says it is six.', 'Look at the clock on the wall.'],
  coat: ['Put on your coat, it is cold.', 'My coat has a hood.'],
  cod: ['We had cod and chips.'],
  coin: ['I found a coin on the path.', 'The coin is gold.'],
  cot: ['The baby sleeps in a cot.'],
  cow: ['The cow eats grass.', 'A cow gives us milk.'],
  crab: ['A crab hid in the rock pool.', 'The crab has big claws.'],
  cup: ['Fill the cup with milk.', 'The cup is hot.'],
  dad: ['Dad can fix the van.', 'I sat on the rug with Dad.'],
  deer: ['A deer ran into the trees.', 'The deer has big ears.'],
  den: ['The fox sleeps in a den.', 'We made a den from sticks.'],
  dog: ['The dog digs in the mud.', 'My dog can sit and beg.'],
  doll: ['The doll has a red dress.'],
  dot: ['Put a dot on the map.'],
  drum: ['I bang on the drum.', 'The drum is loud.'],
  duck: ['The duck swims on the pond.', 'A duck says quack.'],
  egg: ['The hen laid an egg.', 'I had an egg for lunch.'],
  elf: ['The elf has a green hat.'],
  fan: ['The fan keeps us cool.'],
  farm: ['The pigs live on the farm.', 'We went to the farm to see the lambs.'],
  fig: ['A fig is sweet.'],
  fish: ['The fish swims in the tank.', 'I can see a fish in the pond.'],
  fox: ['A fox ran into the wood.', 'The fox has a red tail.'],
  frog: ['The frog hops into the pond.', 'A frog sits on a log.'],
  gate: ['Shut the gate so the dog stays in.', 'The gate is at the end of the path.'],
  goat: ['The goat eats the grass.', 'A goat can climb rocks.'],
  gull: ['A gull took my chip!', 'The gull sits on the boat.'],
  hat: ['I put on my hat.', 'The hat is too big.'],
  hen: ['The hen sits on her eggs.', 'A hen pecks at the corn.'],
  hill: ['We ran up the hill.', 'The hill is steep.'],
  hut: ['The hut is made of sticks.'],
  ink: ['The pen has run out of ink.'],
  jam: ['I put jam on my toast.', 'The jam is red and sweet.'],
  jet: ['The jet zooms in the sky.'],
  jug: ['Fill the jug with milk.', 'The jug is on the shelf.'],
  kid: ['The kid ran to the park.'],
  king: ['The king sits on his throne.', 'The king has a gold crown.'],
  kit: ['Pack your kit for the match.'],
  lamb: ['The lamb skips in the grass.', 'A lamb is a baby sheep.'],
  leaf: ['A leaf fell from the tree.', 'The leaf is green.'],
  lid: ['Put the lid on the pot.', 'The lid is stuck.'],
  log: ['A frog sat on the log.', 'Put the log on the fire.'],
  man: ['The man has a black hat.'],
  map: ['Look at the map to find the park.', 'The map shows the path.'],
  mat: ['The cat sits on the mat.', 'Wipe your feet on the mat.'],
  milk: ['I drink milk at bedtime.', 'The cat laps up the milk.'],
  moon: ['The moon is big and bright.', 'I can see the moon at night.'],
  moth: ['A moth flew to the light.'],
  mug: ['Mum has tea in a mug.', 'The mug is hot.'],
  mum: ['Mum reads to me at night.', 'I help Mum in the garden.'],
  nail: ['Dad hit the nail with a hammer.', 'The nail is in the wall.'],
  net: ['We got a fish in the net.', 'The net is full of shells.'],
  nut: ['The squirrel hid a nut.'],
  owl: ['An owl hoots at night.', 'The owl sits in the tree.'],
  pan: ['The eggs are in the pan.', 'The pan is hot.'],
  peg: ['Put the peg on the sock.'],
  pen: ['I write with a pen.', 'The pen has blue ink.'],
  pig: ['The pig rolls in the mud.', 'A pig says oink.'],
  pin: ['Pin the badge on my coat.'],
  pip: ['There is a pip in the apple.'],
  pod: ['Peas grow in a pod.'],
  pond: ['The ducks swim on the pond.', 'A frog lives in the pond.'],
  pot: ['The soup is in the pot.', 'Put the lid on the pot.'],
  pup: ['The pup wags its tail.', 'My pup likes to dig.'],
  rain: ['The rain drips off the roof.', 'We got wet in the rain.'],
  ram: ['The ram has big horns.'],
  rat: ['A rat ran under the shed.', 'The rat has a long tail.'],
  ring: ['Mum has a gold ring.', 'The ring is on her hand.'],
  rock: ['A crab hid under the rock.', 'The rock is hard.'],
  rug: ['The dog naps on the rug.', 'The rug is red.'],
  sack: ['The sack is full of coal.', 'Dad lifts the sack.'],
  seal: ['A seal swims in the sea.', 'The seal claps its flippers.'],
  shark: ['A shark has sharp teeth.', 'The shark swims fast.'],
  shed: ['The bikes are in the shed.', 'Dad is in the shed.'],
  sheep: ['The sheep eat grass on the hill.', 'A sheep has a woolly coat.'],
  shell: ['I found a shell on the beach.', 'The shell is pink.'],
  ship: ['The ship sails on the sea.', 'A big ship is in the dock.'],
  shop: ['We got milk from the shop.', 'The shop shuts at six.'],
  snail: ['A snail is on the path.', 'The snail has a shell.'],
  sock: ['I lost a sock.', 'The sock has a hole in it.'],
  spoon: ['Eat your soup with a spoon.', 'The spoon is in the cup.'],
  star: ['I can see a star in the sky.', 'The star is bright.'],
  sun: ['The sun is hot.', 'The cat naps in the sun.'],
  tap: ['Turn off the tap.', 'The tap drips.'],
  taxi: ['We got a taxi to the station.'],
  tent: ['We slept in a tent.', 'The tent is in the garden.'],
  tin: ['The beans are in a tin.', 'Open the tin of soup.'],
  toad: ['A toad sat by the pond.'],
  train: ['The train is late.', 'We went to the seaside by train.'],
  tree: ['The bird sits in the tree.', 'The tree has green leaves.'],
  truck: ['The truck is full of sand.', 'A big truck went past.'],
  tub: ['The tub is full of water.'],
  van: ['Dad drives a red van.', 'The van is stuck in the mud.'],
  vet: ['The vet fixed the dog’s leg.', 'We took the cat to the vet.'],
  web: ['A spider spins a web.', 'The web is in the shed.'],
  wig: ['The clown has a red wig.'],
  worm: ['A worm wriggles in the soil.', 'The bird ate a worm.'],
  zip: ['Do up the zip on your coat.', 'The zip is stuck.'],
  // ---- L4-6 digraph and trigraph nouns ----
  beach: ['We dug in the sand at the beach.', 'The beach is hot today.'],
  chain: ['The dog is on a chain.', 'The chain is made of gold.'],
  church: ['The church has a tall tower.', 'The bells ring at the church.'],
  cloud: ['A cloud hid the sun.', 'The cloud is grey.'],
  clown: ['The clown has a red nose.', 'A clown made us laugh.'],
  coach: ['We went to the zoo on a coach.', 'The coach is full of kids.'],
  crew: ['The crew sail the ship.'],
  crown: ['The king has a gold crown.', 'The crown is on his head.'],
  house: ['My house has a red door.', 'We live in a house by the park.'],
  jewel: ['The jewel shines in the light.'],
  newt: ['A newt swims in the pond.'],
  nurse: ['The nurse put a plaster on my knee.', 'A nurse helps sick people.'],
  peach: ['A peach is soft and sweet.'],
  porch: ['Leave your boots on the porch.'],
  purse: ['Mum keeps coins in her purse.', 'The purse is in her bag.'],
  road: ['Look both ways before you cross the road.', 'The road is wet.'],
  screw: ['Dad turns the screw with a screwdriver.'],
  soap: ['Wash your hands with soap.', 'The soap smells of lemon.'],
  stew: ['We had stew for tea.', 'The stew is hot.'],
  torch: ['Shine the torch in the dark.', 'The torch needs a new battery.'],
  town: ['We went to town on the bus.', 'The shops in town are shut.'],
  boy: ['The boy kicks the ball.', 'A boy ran to the park.'],
  toy: ['My toy is a red car.', 'Put the toy back in the box.'],
  girl: ['The girl reads a book.', 'A girl sat on the swing.'],
  car: ['Dad parks the car.', 'The car is red.'],
  park: ['We play in the park.', 'The park has swings.'],
  fork: ['Eat your peas with a fork.', 'The fork is next to the spoon.'],
  corn: ['The hens peck at the corn.', 'Corn grows in the field.'],
  foot: ['I hurt my foot on a rock.', 'Put your foot in the boot.'],
  wood: ['The fox ran into the wood.', 'The desk is made of wood.'],
  light: ['Turn off the light at bedtime.', 'The light is too bright.'],
  tray: ['Put the cups on the tray.', 'The tray is full of cakes.'],
  clay: ['We made pots from clay.', 'The clay is soft and wet.'],
  hay: ['The horse eats hay.', 'The hay is in the barn.'],
  sheet: ['Put a clean sheet on the bed.', 'The sheet is white.'],
  queen: ['The queen waves from the coach.', 'The queen has a crown.'],
  chair: ['Sit on the chair.', 'The chair has a soft seat.'],
  barn: ['The cows sleep in the barn.', 'The barn is full of hay.'],
  card: ['I made a card for Mum.', 'The card says happy birthday.'],
  // ---- L5 split digraphs ----
  bone: ['The dog dug up a bone.', 'The bone is for the dog.'],
  rope: ['Pull the rope to ring the bell.', 'We tied the boat with a rope.'],
  nose: ['The clown has a red nose.', 'My nose is cold.'],
  rose: ['A rose has sharp thorns.', 'The rose is red.'],
  stone: ['I skimmed a stone on the lake.', 'The stone is smooth.'],
  home: ['We went home on the bus.', 'My home is by the sea.'],
  cone: ['I had an ice cream in a cone.'],
  cake: ['We made a cake for Mum.', 'The cake has five candles.'],
  snake: ['A snake slid under the rock.', 'The snake is long and green.'],
  cape: ['The king wears a red cape.'],
  plane: ['The plane flew over the sea.', 'We went on a plane to Spain.'],
  whale: ['A whale is bigger than a bus.', 'The whale swims in the deep sea.'],
  tape: ['Stick it down with tape.'],
  cave: ['A bat sleeps in the cave.', 'The cave is dark.'],
  kite: ['My kite flew up high.', 'The kite got stuck in a tree.'],
  bike: ['I ride my bike to the park.', 'The bike has a flat tyre.'],
  slide: ['We went down the slide.', 'The slide is in the park.'],
  vine: ['Grapes grow on a vine.'],
  flute: ['She plays the flute in the band.'],
  cube: ['An ice cube melts in the sun.'],
  tube: ['Squeeze the tube of toothpaste.'],
  mole: ['A mole digs under the lawn.'],
  mule: ['The mule carries the bags up the hill.'],
  // ---- L4 vowel digraphs (non-noun and extra target words) ----
  day: ['It is a hot day.', 'We had a fun day at the beach.'],
  play: ['We play in the park.', 'Can I play with the ball?'],
  stay: ['Stay in the car, Dad said.', 'The dog must stay in the garden.'],
  way: ['This is the way to the shop.'],
  say: ['Say the sound out loud.'],
  spray: ['The hose can spray water.'],
  feet: ['My feet are wet.', 'The duck has red feet.'],
  green: ['The frog is green.', 'The grass is green and wet.'],
  seed: ['Plant the seed in the pot.', 'A seed grows into a plant.'],
  sleep: ['I sleep in my bed.', 'The cat can sleep all day.'],
  three: ['I have three pets.', 'Three ducks swim on the pond.'],
  week: ['We go to the shop each week.'],
  night: ['The moon is out at night.', 'An owl hoots at night.'],
  high: ['The kite is high in the sky.', 'The shelf is too high.'],
  right: ['Turn right at the shop.', 'Put your right hand up.'],
  bright: ['The sun is bright.', 'The light is too bright.'],
  fright: ['The bang gave me a fright.'],
  tight: ['My boots are too tight.'],
  snow: ['The snow is cold and white.', 'We made a man from snow.'],
  blow: ['Blow on the hot soup.'],
  glow: ['The stars glow in the dark.'],
  slow: ['A snail is slow.', 'The bus is slow in the snow.'],
  show: ['Show me your book.'],
  grow: ['The seeds grow in the sun.'],
  bowl: ['The soup is in a bowl.', 'Fill the bowl with milk.'],
  row: ['We sit in a row.'],
  food: ['The dog eats his food.', 'The food is hot.'],
  roof: ['The cat sits on the roof.', 'The rain drips off the roof.'],
  zoo: ['We saw a lion at the zoo.', 'The zoo has a big pool.'],
  pool: ['We swim in the pool.', 'The pool is cold.'],
  cool: ['The fan keeps us cool.'],
  hoop: ['The dog jumps through the hoop.'],
  look: ['Look at the moon!', 'Look both ways at the road.'],
  cook: ['Mum can cook fish.', 'Dad will cook tea.'],
  hook: ['Hang your coat on the hook.'],
  dark: ['It is dark at night.', 'A bat flies in the dark.'],
  arm: ['I hurt my arm.', 'The cast is on my arm.'],
  jar: ['The jam is in a jar.', 'Open the jar of jam.'],
  scarf: ['I wear a scarf in the snow.', 'The scarf is red.'],
  horse: ['The horse eats hay.', 'A horse can run fast.'],
  storm: ['The storm blew the tent down.', 'We hid from the storm.'],
  fort: ['We made a fort from boxes.'],
  sport: ['My best sport is football.'],
  short: ['The path is short.'],
  hair: ['My hair is wet.', 'Brush your hair.'],
  fair: ['We went on the rides at the fair.', 'The fair is in town.'],
  pair: ['I have a pair of red boots.', 'This is a pair of socks.'],
  stairs: ['Go up the stairs to bed.', 'The cat sits on the stairs.'],
  shirt: ['My shirt has a stain on it.', 'Put on a clean shirt.'],
  skirt: ['Her skirt is red.'],
  dirt: ['The dog is full of dirt.'],
  first: ['I was first in the race.'],
  third: ['She came third in the race.'],
  out: ['Go out to play.', 'The cat got out of the box.'],
  shout: ['Do not shout in class.'],
  loud: ['The drum is loud.', 'The bang was loud.'],
  round: ['The ball is round.', 'Run round the park.'],
  sound: ['Say the sound.', 'I can hear a sound in the shed.'],
  mouth: ['Open your mouth at the dentist.'],
  found: ['I found a coin on the path.'],
  joy: ['The pup jumps for joy.'],
  enjoy: ['I enjoy a good book.'],
  // ---- L5 ----
  dream: ['I had a dream about a dragon.'],
  team: ['Our team won the match.', 'I am on the red team.'],
  seat: ['Sit in your seat on the bus.'],
  meal: ['We had a big meal at Gran’s.'],
  pie: ['Mum made an apple pie.', 'The pie is hot.'],
  tie: ['Dad wears a tie to work.'],
  soil: ['Plant the seed in the soil.'],
  boil: ['Boil the water for tea.'],
  oil: ['Put oil in the pan.'],
  paw: ['The dog hurt his paw.', 'The cat licks her paw.'],
  claw: ['The crab has a big claw.'],
  saw: ['I saw a fox in the wood.', 'Dad cut the log with a saw.'],
  straw: ['Sip your drink with a straw.'],
  yawn: ['I yawn when I am tired.'],
  draw: ['I can draw a cat.', 'Draw a house.'],
  tail: ['The dog wags his tail.', 'The cat has a long tail.'],
  paint: ['We paint with red and blue.', 'The paint is wet.'],
  toast: ['I had toast with jam.', 'The toast is hot.'],
  cloak: ['The king wears a red cloak.'],
  // ---- L6 ----
  new: ['I got new boots.', 'The car is new.'],
  chew: ['Chew your food well.', 'Dogs chew on bones.'],
  flew: ['The bird flew to the tree.'],
  drew: ['I drew a cat.'],
  grew: ['The plant grew tall.'],
  threw: ['He threw the ball.'],
  glue: ['Stick it with glue.', 'The glue is sticky.'],
  blue: ['The sky is blue.', 'My coat is blue.'],
  true: ['Is it true that owls hoot?'],
  clue: ['I found a clue in the sand.'],
  care: ['Take care on the ice.'],
  share: ['Share the cake with your sister.'],
  dare: ['I dare you to jump in.'],
  stare: ['Do not stare at the sun.'],
  scare: ['The bang gave me a scare.'],
  square: ['A box is a square.'],
  down: ['Sit down on the mat.', 'The sun goes down at night.'],
  now: ['We can go now.'],
  how: ['How did the cat get out?'],
  howl: ['Wolves howl at the moon.'],
  letter: ['I got a letter from Gran.', 'Post the letter.'],
  ladder: ['Dad went up the ladder.'],
  dinner: ['We had fish for dinner.'],
  summer: ['It is hot in summer.'],
  winter: ['It snows in winter.'],
  sister: ['My sister is six.'],
  river: ['The boat is on the river.', 'Ducks swim on the river.'],
  curl: ['Her hair has a curl in it.'],
  turn: ['Turn left at the shop.', 'It is my turn to roll the die.'],
  burn: ['The pan is hot and can burn you.'],
  fur: ['The cat has soft fur.', 'The fox has red fur.'],
  hurt: ['I hurt my knee.'],
  surf: ['We surf at the beach.'],
  turnip: ['A turnip grows under the soil.'],
  // ---- L7 ----
  fire: ['We sat by the fire.', 'The fire is hot.'],
  wire: ['The wire is on the fence.'],
  tyre: ['The car has a flat tyre.'],
  hire: ['We can hire a bike at the park.'],
  shore: ['The boat is on the shore.', 'We walked along the shore.'],
  store: ['We got food at the store.'],
  snore: ['Dad can snore all night.'],
  core: ['I ate the apple down to the core.'],
  more: ['Can I have more cake?'],
  ear: ['I can hear with my ear.', 'The dog has a floppy ear.'],
  hear: ['I can hear the bell.'],
  near: ['The shop is near the park.'],
  dear: ['Gran is very dear to me.'],
  fear: ['I have no fear of the dark.'],
  clear: ['The water is clear.'],
  year: ['I am six this year.'],
  door: ['Shut the door.', 'The door is red.'],
  floor: ['The toys are on the floor.', 'Sweep the floor.'],
  poor: ['The poor dog got wet.'],
  pure: ['The water is pure and clean.'],
  sure: ['Are you sure the door is shut?'],
  cure: ['The vet found a cure for the pup.'],
  action: ['The film is full of action.'],
  section: ['Read the next section of the book.'],
  direction: ['Which direction is the park?'],
  attention: ['Pay attention in class.'],
  instruction: ['Read each instruction on the sheet.'],
  fiction: ['I like fiction books best.'],
  motion: ['The boat is in motion.'],
  potion: ['The witch made a potion.'],
  lotion: ['Put lotion on your sunburn.'],
  // ---- L8 suffixes: adjectives, so the frames are built around them ----
  famous: ['The singer is famous.', 'A famous chef made the cake.'],
  enormous: ['The whale is enormous.', 'An enormous truck went past.'],
  marvellous: ['We had a marvellous day at the beach.'],
  glorious: ['It was a glorious sunny day.'],
  fabulous: ['The cake was fabulous.'],
  joyous: ['The wedding was a joyous day.'],
  dangerous: ['The cliff is dangerous.', 'It is dangerous to run on ice.'],
  jealous: ['The cat is jealous of the new pup.'],
  curious: ['The curious cat looked in the box.'],
  furious: ['Dad was furious about the mud on the rug.'],
  capable: ['She is capable of running a mile.'],
  remarkable: ['The dog did a remarkable trick.'],
  comfortable: ['This chair is comfortable.'],
  reasonable: ['That is a reasonable price for a book.'],
  washable: ['The coat is washable.'],
  reliable: ['My bike is reliable.'],
  adorable: ['The kitten is adorable.'],
  suitable: ['Boots are suitable for the snow.'],
  enjoyable: ['The film was enjoyable.'],
  valuable: ['The ring is valuable.'],
  predictable: ['The ending of the film was predictable.'],
  sensible: ['It is sensible to wear a coat in the rain.'],
  possible: ['It is possible to see the moon in the day.'],
  terrible: ['The storm was terrible.'],
  horrible: ['The soup tasted horrible.'],
  visible: ['The moon is visible tonight.'],
  incredible: ['The view from the hill is incredible.'],
  responsible: ['I am responsible for feeding the cat.'],
  flexible: ['A gymnast is flexible.'],
  delicious: ['The cake is delicious.'],
  suspicious: ['The dog looked suspicious of the vet.'],
  precious: ['The ring is precious to Mum.'],
  gracious: ['The queen gave a gracious wave.'],
  spacious: ['The new house is spacious.'],
  vicious: ['The vicious dog barked at us.'],
  cautious: ['Be cautious on the ice.'],
  nutritious: ['Carrots are nutritious.'],
  ambitious: ['She is ambitious and wants to win.'],
  scrumptious: ['The pie was scrumptious.'],
  explosion: ['The explosion was loud.'],
  decision: ['It was a good decision to bring a coat.'],
  confusion: ['There was confusion at the station.'],
  invasion: ['The film was about an alien invasion.'],
  television: ['We watch television after tea.'],
  mansion: ['The mansion has a hundred rooms.'],
  station: ['The train is at the station.', 'We met Gran at the station.'],
};
