// Emit src/data/workbook2/soundPages.ts from the Sound Pack transcription
// manifest + the extra-grapheme authoring, with img flags checked against the
// actual files in public/soundart. Re-run after any crop/generation change.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const packs = path.join(root, 'output', '_research', 'soundpacks');
const manifest = JSON.parse(fs.readFileSync(path.join(packs, 'soundpack_manifest.json'), 'utf8'));
const extra = JSON.parse(fs.readFileSync(path.join(packs, 'extra_graphemes.json'), 'utf8'));
const artRoot = path.join(root, 'public', 'soundart');

function hasArt(g, word) {
  return fs.existsSync(path.join(artRoot, g, `${word.replace(/ /g, '_')}.png`));
}

// ALWAYS derive the gap from the word itself (first occurrence of the
// grapheme) — the vision transcription's gap strings proved unreliable
// ("_at" for ant, "im_" for rim).
function shownFor(g, word) {
  const i = word.indexOf(g);
  if (i < 0) return `_${word.slice(1)}`;
  return `${word.slice(0, i)}_${word.slice(i + g.length)}`;
}

const pages = {};
for (const [g, data] of Object.entries(manifest)) {
  pages[g] = {
    grapheme: g,
    trace: data.trace_words.slice(0, 4).map((w) => ({ word: w, img: hasArt(g, w) })),
    missing: data.missing.map((m) => ({
      word: m.word,
      shown: shownFor(g, m.word),
      img: hasArt(g, m.word),
    })),
  };
}
for (const [g, data] of Object.entries(extra)) {
  if (g.startsWith('_')) continue;
  pages[g] = {
    grapheme: g,
    trace: data.trace_words.map((w) => ({ word: w, img: hasArt(g, w) })),
    missing: data.missing.map((m) => ({ word: m.word, shown: m.shown, img: hasArt(g, m.word) })),
  };
}

const order = Object.keys(pages).sort();
const body = order.map((g) => `  ${JSON.stringify(g)}: ${JSON.stringify(pages[g])},`).join('\n');
const out = `// GENERATED by scripts/_emit_soundpages.js — do not edit by hand.
// Source of truth: the approved Sound Pack sheets (Drive/TPT), transcribed in
// output/_research/soundpacks/soundpack_manifest.json, plus the five
// extra-grapheme authorings in extra_graphemes.json. img flags reflect the
// files actually present in public/soundart (missing art = empty slot).
import type { SoundPageData } from '@/data/workbook2/levels';

export const SOUND_PAGES: Record<string, SoundPageData> = {
${body}
};

export function soundPagesFor(...graphemes: string[]): SoundPageData[] {
  return graphemes.map((g) => {
    const p = SOUND_PAGES[g];
    if (!p) throw new Error(\`no sound page data for grapheme "\${g}"\`);
    return p;
  });
}
`;
fs.writeFileSync(path.join(root, 'src', 'data', 'workbook2', 'soundPages.ts'), out);
const withArt = order.filter((g) => pages[g].trace.every((t) => t.img) && pages[g].missing.every((m) => m.img));
console.log(`${order.length} graphemes emitted; full art: ${withArt.length}`);
