/**
 * LandingPage — public front door.
 *
 * Message hierarchy (from the printed leaflet, per user):
 *   1. Explore the books — the library is open, free books included
 *   2. Assess your child free (3 minutes)
 *   3. Read on any screen, or download & print real booklets
 *   4. "From first sounds to last sounds" — the 8-level journey
 * Plus the floating cover imagery (kept) and real testimonials (kept).
 *
 * "Paper & stickers" design language shared with the app: sticker chips,
 * white sticker cards, 3D pressable buttons, journey-level colours.
 */
import { useState, useEffect, useRef, useMemo } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import {
  BookOpen, Sparkles, Globe, BarChart3, CheckCircle2, ChevronRight, ChevronLeft, Volume2,
  Trophy, GraduationCap, Printer, Heart, ClipboardList, PlayCircle, ShoppingBag,
  Globe2,
} from 'lucide-react';
import { JOURNEY_LEVELS } from '@/lib/levels8';
import { useFunnelTracker } from '@/hooks/useFunnelTracker';
import LandingTestimonials from '@/components/LandingTestimonials';
import { useTranslation, Trans } from 'react-i18next';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import EnglishOnly from '@/i18n/EnglishOnly';
import { LANGUAGES } from '@/i18n/languages';

const STICKER = '0 1px 2px rgba(40,30,40,0.10), 0 8px 20px rgba(40,30,40,0.10)';
const PINK = '#E84B8A';
const PINK_INK = '#BE1862';

/* ─── Real book-photo cutouts for the hero shelf (public/shop/cutouts/) ───
 * One curated title per level (plus a couple of extras) so the shelf runs
 * through the full pink→teal ledger colour range. SKU = r-l{level}-{index},
 * matching public/shop/cutouts/{sku}.webp — transparent PNG/WebP cutouts of
 * the photorealistic booklet mockups generated by scripts/generate_book_cutouts.py. */
const FLOATING_SHOWCASE = [
  { level: 1, index: 1, title: 'Tap! Tap! Tap!' },
  { level: 1, index: 2, title: 'The Mud on the Dog' },
  { level: 2, index: 1, title: 'The Red Socks' },
  { level: 2, index: 3, title: 'Fox Fell Off!' },
  { level: 3, index: 1, title: 'The Fish in the Tank' },
  { level: 4, index: 1, title: 'The Night Light' },
  { level: 4, index: 4, title: 'The Fair in the Air' },
  { level: 5, index: 1, title: 'The Big Bike Race' },
  { level: 5, index: 5, title: 'The Boat with the Red Sail' },
  { level: 6, index: 1, title: 'The Purple Purse' },
  { level: 7, index: 1, title: 'Before the Shore' },
  { level: 8, index: 1, title: 'The Marvellous Neighbourhood' },
  { level: 8, index: 3, title: 'It Looks Suspicious!' },
];

/** Books per journey level (33 total). */
const BOOK_COUNTS: Record<number, number> = { 1: 2, 2: 5, 3: 3, 4: 6, 5: 5, 6: 4, 7: 4, 8: 4 };

/* ─── Scroll-reveal hook ─── */
function useReveal() {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setVisible(true); }, { threshold: 0.15 });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return { ref, visible };
}

/** 3D pressable button — the app's signature CTA. */
function PushButton({ onClick, children, tone = 'pink', className = '' }: {
  onClick: () => void; children: React.ReactNode; tone?: 'pink' | 'white'; className?: string;
}) {
  if (tone === 'white') {
    return (
      <button
        onClick={onClick}
        className={`inline-flex items-center justify-center gap-2 px-7 py-4 rounded-2xl font-display font-extrabold text-base bg-white text-foreground transition-all active:translate-y-[3px] ${className}`}
        style={{ boxShadow: `0 4px 0 rgba(40,30,40,0.10), ${STICKER}`, border: '1px solid rgba(40,30,40,0.06)' }}
      >
        {children}
      </button>
    );
  }
  return (
    <button
      onClick={onClick}
      className={`inline-flex items-center justify-center gap-2 px-7 py-4 rounded-2xl font-display font-extrabold text-base text-white transition-all active:translate-y-[4px] ${className}`}
      style={{ background: PINK, boxShadow: `0 5px 0 ${PINK_INK}, 0 14px 28px -10px ${PINK}80` }}
    >
      {children}
    </button>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════ */

export default function LandingPage() {
  useFunnelTracker();
  const navigate = useNavigate();
  const { t } = useTranslation('landing');

  return (
    <div className="min-h-screen bg-background" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
      {/* sr-only rather than the global .skip-link (left:-9999px), which in
          RTL makes the page ~10,000px wide and scrolls the content away. */}
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:start-2 focus:z-[100] focus:rounded-lg focus:bg-foreground focus:text-background focus:px-3 focus:py-2"
      >
        {t('skipToMain')}
      </a>

      <NavBar onBrowse={() => navigate('/library')} />

      <main id="main">
        <HeroSection onBrowse={() => navigate('/library')} onAssess={() => navigate('/assessment')} />
        <PlatformVideo />
        <ThreeThings
          onAssess={() => navigate('/assessment')}
          onBrowse={() => navigate('/library')}
        />
        <LandingTestimonials />
        <LevelJourney />
        <FeatureShowcase />
        <FreeForAll onSignUp={() => navigate('/auth?mode=signup')} onSupport={() => navigate('/support')} />
        <FooterCTA onBrowse={() => navigate('/library')} onAssess={() => navigate('/assessment')} />
      </main>
      <Footer />
    </div>
  );
}

/* ─── PLATFORM VIDEO ─── */
function PlatformVideo() {
  const { t } = useTranslation('landing');
  return (
    <section className="py-12 md:py-16">
      <div className="max-w-5xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-6">
          <div
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider mb-3"
            style={{ background: 'rgba(232,75,138,0.10)', color: PINK_INK }}
          >
            <PlayCircle className="w-3.5 h-3.5" /> {t('video.badge')}
          </div>
          <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight">
            {t('video.title')}
          </h2>
          <p className="mt-2 text-muted-foreground max-w-2xl mx-auto">
            {t('video.body')}
          </p>
        </div>
        <div
          className="max-w-4xl mx-auto rounded-3xl overflow-hidden bg-slate-900"
          style={{ boxShadow: STICKER }}
        >
          <video
            controls
            preload="metadata"
            playsInline
            poster="/videos/platform-tour-poster.jpg"
            className="w-full aspect-video block"
          >
            <source src="/videos/platform-tour.mp4" type="video/mp4" />
            <Trans
              t={t}
              i18nKey="video.fallback"
              components={{ link: <a href="/videos/platform-tour.mp4" className="underline" /> }}
            />
          </video>
        </div>
      </div>
    </section>
  );
}

/* ─── NAV BAR ─── */
function NavBar({ onBrowse }: { onBrowse: () => void }) {
  const { t } = useTranslation('landing');
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', fn, { passive: true });
    return () => window.removeEventListener('scroll', fn);
  }, []);

  return (
    <header className={`fixed top-0 inset-x-0 z-50 transition-all duration-300 safe-top ${scrolled ? 'bg-card/95 backdrop-blur-xl shadow-card border-b border-border' : 'bg-transparent'}`}>
      <div className="max-w-6xl mx-auto px-3 sm:px-6 py-3 flex items-center justify-between gap-2">
        <Link to="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity shrink-0 min-w-0" aria-label={t('nav.homeAria')}>
          <img src="/logo/mpb-mark-transparent.png" alt="" className="w-9 h-9 sm:w-10 sm:h-10 object-contain shrink-0" draggable={false} />
          <span dir="ltr" className="font-display text-base sm:text-lg font-extrabold text-foreground tracking-tight truncate hidden xs:inline">
            My<span className="text-primary-ink">Phonics</span>Books
          </span>
        </Link>
        <div className="flex items-center gap-1.5 sm:gap-3 shrink-0">
          <Link to="/create-book" className="text-xs sm:text-sm font-bold text-foreground hover:text-primary-ink transition-colors whitespace-nowrap inline-flex items-center gap-1">
            <Sparkles className="w-4 h-4" /> {t('nav.createBook')}
          </Link>
          <Link to="/world-of-books" className="text-xs sm:text-sm font-bold text-foreground hover:text-primary-ink transition-colors whitespace-nowrap items-center gap-1 hidden sm:inline-flex">
            <Globe2 className="w-4 h-4" /> {t('nav.worldOfBooks')}
          </Link>
          <Link to="/shop" className="text-xs sm:text-sm font-bold text-foreground hover:text-primary-ink transition-colors whitespace-nowrap items-center gap-1 hidden sm:inline-flex">
            <ShoppingBag className="w-4 h-4" /> {t('nav.shop')}
          </Link>
          <Link to="/love" className="text-xs sm:text-sm font-bold text-foreground hover:text-primary-ink transition-colors whitespace-nowrap items-center gap-1 hidden sm:inline-flex">
            <Heart className="w-4 h-4" /> {t('nav.wallOfLove')}
          </Link>
          <Link to="/school" className="text-xs sm:text-sm font-bold text-foreground hover:text-primary-ink transition-colors whitespace-nowrap inline-flex items-center gap-1">
            <GraduationCap className="w-4 h-4" />
            <span className="hidden xs:inline">{t('nav.forSchools')}</span>
            <span className="xs:hidden">{t('nav.schools')}</span>
          </Link>
          <LanguageSwitcher variant="compact" className="shrink-0 px-2 py-1.5" />
          <button
            onClick={onBrowse}
            className="text-xs sm:text-sm font-display font-extrabold text-white px-3 sm:px-4 py-2 rounded-xl transition-all active:translate-y-[2px] whitespace-nowrap"
            style={{ background: PINK, boxShadow: `0 3px 0 ${PINK_INK}` }}
          >
            <span className="sm:hidden">{t('nav.explore')}</span>
            <span className="hidden sm:inline">{t('nav.exploreBooks')}</span>
          </button>
        </div>
      </div>
    </header>
  );
}

/* ─── HERO ─── */
function HeroSection({ onBrowse, onAssess }: { onBrowse: () => void; onAssess: () => void }) {
  const { t } = useTranslation('landing');
  return (
    <section className="relative pt-28 pb-16 md:pt-36 md:pb-24 overflow-hidden">
      {/* Background gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-[hsl(338,78%,96%)] via-background to-[hsl(142,60%,97%)]" />
      <div className="absolute top-20 end-0 w-96 h-96 bg-primary/5 rounded-full blur-3xl" />
      <div className="absolute bottom-0 start-0 w-72 h-72 bg-[hsl(var(--level-3))]/5 rounded-full blur-3xl" />

      <div className="relative max-w-6xl mx-auto px-4 sm:px-6">
        <div className="grid md:grid-cols-2 gap-10 items-center">
          {/* Text */}
          <div className="text-center md:text-start">
            {/* Audience switch — parents stay here; schools/nurseries jump
                to their own product. Parent is the active state. */}
            <div className="inline-flex items-center gap-1 p-1 mb-5 rounded-full bg-card border border-border shadow-sm">
              <span className="px-3 py-1.5 rounded-full text-xs font-bold bg-primary text-white">
                {t('hero.forParents')}
              </span>
              <Link
                to="/school"
                className="px-3 py-1.5 rounded-full text-xs font-bold text-muted-foreground hover:text-primary-ink transition-colors inline-flex items-center gap-1"
              >
                <GraduationCap className="w-3.5 h-3.5" /> {t('hero.forSchools')}
              </Link>
            </div>

            {/* Language sticker — tells parents the site speaks their
                language (the books themselves stay in English). The pill
                on the right is the real language picker. */}
            <div className="flex justify-center md:justify-start mb-5 -mt-1">
              <div
                className="inline-flex items-center gap-2 rounded-full bg-white ps-3 pe-1 py-1 -rotate-1"
                style={{ boxShadow: STICKER, border: '2px solid #fff', outline: `2px solid ${PINK}30` }}
              >
                <span className="text-xs font-extrabold text-primary-ink whitespace-nowrap">
                  <span aria-hidden>🌐 </span>{t('hero.languages', { n: LANGUAGES.length })}
                </span>
                <LanguageSwitcher variant="full" align="start" className="rounded-full py-1 px-2.5 text-xs" />
              </div>
            </div>

            <h1 className="font-display text-4xl sm:text-5xl lg:text-[3.4rem] font-extrabold text-foreground tracking-tight leading-[1.05]">
              {t('hero.titleA')}{' '}
              <span className="text-primary-ink">{t('hero.titleB')}</span>
            </h1>
            <p className="mt-5 text-lg text-muted-foreground leading-relaxed max-w-lg mx-auto md:mx-0">
              {t('hero.body')}
            </p>
            <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center md:justify-start">
              <PushButton onClick={onBrowse}>
                <BookOpen className="w-5 h-5" /> {t('hero.exploreBooks')}
              </PushButton>
              <PushButton onClick={onAssess} tone="white">
                {t('hero.checkLevelFree')} <ChevronRight className="w-4 h-4 rtl:-scale-x-100" />
              </PushButton>
            </div>
            <p className="mt-4 text-xs text-muted-foreground font-semibold">
              {t('hero.freeNote')}
            </p>
          </div>

          {/* Floating book shelf — real product-photo cutouts, swipe/drag to browse */}
          <div className="h-[420px] md:h-[480px]" dir="ltr">
            <FloatingBookShelf />
          </div>
        </div>
      </div>

      {/* CSS animation */}
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-10px); }
        }
        .book-shelf-track {
          scrollbar-width: none;
          -ms-overflow-style: none;
          -webkit-overflow-scrolling: touch;
          overscroll-behavior-x: contain;
        }
        .book-shelf-track::-webkit-scrollbar { display: none; }
        @media (prefers-reduced-motion: reduce) {
          .book-shelf-card { animation: none !important; }
        }
      `}</style>
    </section>
  );
}

/* ─── FLOATING BOOK SHELF — the hero's real product photography ───
 * One book fully visible at a time (full-width scroll-snap slide) — no
 * neighbouring cover or colour peeking in at the edges, and no artificial
 * background behind it, so it just floats on the section's own gradient.
 * Native CSS scroll-snap gives touch/trackpad swipe for free; a pointer
 * handler adds the same for desktop mouse drag; arrows are the only nav
 * chrome. A gentle idle float-bob runs via the `float` keyframe above. */
function FloatingBookShelf() {
  const { t } = useTranslation('landing');
  const trackRef = useRef<HTMLDivElement>(null);
  const [active, setActive] = useState(0);

  const items = useMemo(
    () =>
      FLOATING_SHOWCASE.map((b) => {
        const lvl = JOURNEY_LEVELS[b.level - 1];
        return { ...b, sku: `r-l${b.level}-${b.index}`, hex: lvl.hex, levelName: lvl.name };
      }),
    []
  );

  useEffect(() => {
    const el = trackRef.current;
    if (!el) return;
    // One full-width slide per book — the active index is just scrollLeft /
    // slide width, no per-card measuring needed since neighbours are never
    // partially visible.
    let raf = 0;
    const update = () => {
      raf = 0;
      if (!el.clientWidth) return;
      const idx = Math.round(el.scrollLeft / el.clientWidth);
      setActive(Math.max(0, Math.min(items.length - 1, idx)));
    };
    const onScroll = () => {
      if (!raf) raf = requestAnimationFrame(update);
    };
    update();
    el.addEventListener('scroll', onScroll, { passive: true });
    window.addEventListener('resize', onScroll);
    return () => {
      el.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
      if (raf) cancelAnimationFrame(raf);
    };
  }, [items.length]);

  const scrollToIndex = (i: number) => {
    const el = trackRef.current;
    if (!el) return;
    el.scrollTo({ left: i * el.clientWidth, behavior: 'smooth' });
  };

  // Mouse click-and-drag scroll — overflow-x:auto only responds to touch/
  // trackpad/scrollbar natively, so desktop mouse users need this to "swipe"
  // the shelf the way the arrows and touch already do.
  const drag = useRef({ down: false, startX: 0, startScroll: 0, moved: false });
  const onPointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    const el = trackRef.current;
    if (!el) return;
    drag.current = { down: true, startX: e.clientX, startScroll: el.scrollLeft, moved: false };
    el.setPointerCapture(e.pointerId);
    el.style.scrollSnapType = 'none';
    el.style.cursor = 'grabbing';
  };
  const onPointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    const el = trackRef.current;
    if (!el || !drag.current.down) return;
    const dx = e.clientX - drag.current.startX;
    if (Math.abs(dx) > 3) drag.current.moved = true;
    el.scrollLeft = drag.current.startScroll - dx;
  };
  const endDrag = () => {
    const el = trackRef.current;
    if (!el || !drag.current.down) return;
    drag.current.down = false;
    el.style.scrollSnapType = 'x mandatory';
    el.style.cursor = 'grab';
  };

  const activeItem = items[active];

  return (
    <div className="relative h-full">
      {/* One full-width slide per book — at rest only the active book is
       * ever in the viewport, so there's no neighbouring cover/colour
       * bleeding in at the edges. The track itself has no fill, so the
       * section's own background shows straight through. */}
      <div
        ref={trackRef}
        role="region"
        aria-label={t('shelf.regionAria')}
        tabIndex={0}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={endDrag}
        onPointerLeave={endDrag}
        onPointerCancel={endDrag}
        className="book-shelf-track flex items-center overflow-x-auto snap-x snap-mandatory h-[340px] md:h-[390px] cursor-grab select-none"
      >
        {items.map((b, i) => (
          <div key={b.sku} className="snap-center shrink-0 w-full h-full flex items-center justify-center">
            <div
              className="book-shelf-card"
              style={{ animation: 'float 3.6s ease-in-out infinite', animationDelay: `${i * 0.22}s` }}
            >
              <picture>
                <source srcSet={`/shop/cutouts/${b.sku}.webp`} type="image/webp" />
                <img
                  src={`/shop/cutouts/${b.sku}.png`}
                  alt={t('shelf.coverAlt', { title: b.title, level: b.level, levelName: b.levelName })}
                  className="h-[220px] md:h-[280px] w-auto drop-shadow-[0_22px_28px_rgba(30,20,15,0.22)]"
                  loading={i < 4 ? 'eager' : 'lazy'}
                  decoding="async"
                  draggable={false}
                />
              </picture>
            </div>
          </div>
        ))}
      </div>

      {/* Prev / next — the only navigation chrome; swipe/drag/wheel also work */}
      <button
        type="button"
        onClick={() => scrollToIndex(Math.max(0, active - 1))}
        disabled={active === 0}
        aria-label={t('shelf.prevBook')}
        className="absolute left-0 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white flex items-center justify-center text-foreground disabled:opacity-30 transition-opacity hover:opacity-80"
        style={{ boxShadow: STICKER }}
      >
        <ChevronLeft className="w-4 h-4" />
      </button>
      <button
        type="button"
        onClick={() => scrollToIndex(Math.min(items.length - 1, active + 1))}
        disabled={active === items.length - 1}
        aria-label={t('shelf.nextBook')}
        className="absolute right-0 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white flex items-center justify-center text-foreground disabled:opacity-30 transition-opacity hover:opacity-80"
        style={{ boxShadow: STICKER }}
      >
        <ChevronRight className="w-4 h-4" />
      </button>

      {/* Active title pill */}
      <div className="text-center mt-1">
        <AnimatePresence mode="wait">
          <motion.span
            key={activeItem.sku}
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.18 }}
            className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-1.5 text-xs font-extrabold text-foreground"
            style={{ boxShadow: STICKER, border: '2px solid #fff', outline: `2px solid ${activeItem.hex}40` }}
          >
            <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: activeItem.hex }} />
            <span dir="auto">{t('shelf.level', { level: activeItem.level })}</span> &middot;{' '}
            <span lang="en">{activeItem.title}</span>
          </motion.span>
        </AnimatePresence>
      </div>
    </div>
  );
}

/* ─── THE THREE THINGS (leaflet message) ─── */
function ThreeThings({ onAssess, onBrowse }: { onAssess: () => void; onBrowse: () => void }) {
  const { t } = useTranslation('landing');
  const r = useReveal();
  const cards = [
    {
      icon: ClipboardList,
      hex: '#E84B8A',
      tilt: '-1deg',
      title: t('three.check.title'),
      desc: t('three.check.desc'),
      cta: t('three.check.cta'),
      onClick: onAssess,
    },
    {
      icon: Volume2,
      hex: '#3B82F6',
      tilt: '1deg',
      title: t('three.read.title'),
      desc: t('three.read.desc'),
      cta: t('three.read.cta'),
      onClick: onBrowse,
    },
    {
      icon: Printer,
      hex: '#22C55E',
      tilt: '-0.5deg',
      title: t('three.print.title'),
      desc: t('three.print.desc'),
      cta: t('three.print.cta'),
      onClick: onBrowse,
    },
  ];

  return (
    <section className="py-14 md:py-20">
      <div ref={r.ref} className={`max-w-5xl mx-auto px-4 sm:px-6 transition-all duration-700 ${r.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        <div className="text-center mb-12">
          <span
            className="inline-block rounded-full bg-white px-4 py-1.5 text-xs font-extrabold -rotate-1 text-primary-ink"
            style={{ boxShadow: STICKER, border: '2px solid #fff', outline: `2px solid ${PINK}30` }}
          >
            {t('three.badge')}
          </span>
          <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight mt-4">
            {t('three.title')}
          </h2>
          <p className="mt-3 text-muted-foreground text-lg">{t('three.subtitle')}</p>
        </div>

        <div className="grid md:grid-cols-3 gap-5">
          {cards.map((c, i) => (
            <div
              key={i}
              className="rounded-[2rem] bg-white p-6 flex flex-col text-center"
              style={{ boxShadow: STICKER, border: '1px solid rgba(40,30,40,0.05)', rotate: c.tilt }}
            >
              <span
                className="w-14 h-14 rounded-2xl flex items-center justify-center text-white mx-auto"
                style={{ background: c.hex, boxShadow: `0 8px 18px -6px ${c.hex}90` }}
              >
                <c.icon className="w-7 h-7" />
              </span>
              <h3 className="font-display text-xl font-extrabold text-foreground mt-4">{c.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground leading-relaxed flex-1">{c.desc}</p>
              <button
                onClick={c.onClick}
                className="mt-5 w-full py-3 rounded-2xl font-display font-extrabold text-sm text-white transition-all active:translate-y-[3px]"
                style={{ background: c.hex, boxShadow: `0 4px 0 ${c.hex}AA` }}
              >
                {c.cta}
              </button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── LEVEL JOURNEY — first sounds to last sounds ─── */
function LevelJourney() {
  const { t } = useTranslation('landing');
  const r = useReveal();

  return (
    <section className="py-14 md:py-20 bg-card">
      <div ref={r.ref} className={`max-w-6xl mx-auto px-4 sm:px-6 transition-all duration-700 ${r.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        <div className="text-center mb-12">
          <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight">
            {t('journey.title')}
          </h2>
          <p className="mt-3 text-muted-foreground text-lg">
            {t('journey.subtitle')}
          </p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {JOURNEY_LEVELS.map(lv => (
            <div
              key={lv.level}
              className="relative bg-background rounded-2xl p-4 border border-border hover:shadow-card-hover transition-shadow overflow-hidden"
            >
              <div className="absolute top-0 inset-x-0 h-1.5" style={{ backgroundColor: lv.hex }} />
              <div className="flex items-center gap-2.5 mb-2.5 mt-1">
                <div className="w-9 h-9 rounded-xl flex items-center justify-center text-white font-extrabold text-sm shrink-0" style={{ backgroundColor: lv.hex }}>
                  {lv.level}
                </div>
                <div className="min-w-0">
                  <h3 lang="en" className="font-display font-extrabold text-foreground text-sm leading-tight truncate">{lv.name}</h3>
                  <p className="text-[11px] text-muted-foreground">
                    {/* LRI…PDI keeps "4–5" reading left-to-right inside RTL text. */}
                    {t('journey.ages', { range: `\u2066${lv.ageRange.replace(/^Ages\s*/, '')}\u2069` })}
                  </p>
                </div>
              </div>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                <span dir="ltr" lang="en" className="font-child font-bold" style={{ color: lv.inkHex }}>
                  {lv.gpcs.slice(0, 5).join(' · ')}
                </span>
              </p>
              <p className="text-[11px] text-muted-foreground mt-1.5 font-semibold">
                {t('journey.books', { count: BOOK_COUNTS[lv.level] })}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── FEATURES ─── */
function FeatureShowcase() {
  const { t } = useTranslation('landing');
  const r = useReveal();
  const features = [
    { icon: Volume2, text: t('features.items.soundedOut') },
    { icon: BookOpen, text: t('features.items.books') },
    { icon: Globe, text: t('features.items.settings') },
    { icon: Trophy, text: t('features.items.quizzes') },
    { icon: BarChart3, text: t('features.items.progress') },
    { icon: CheckCircle2, text: t('features.items.aligned') },
  ];

  return (
    <section className="py-14 md:py-20">
      <div ref={r.ref} className={`max-w-6xl mx-auto px-4 sm:px-6 transition-all duration-700 ${r.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight">
              {t('features.titleA')}{' '}
              <span className="text-primary">{t('features.titleB')}</span>
            </h2>
            <p className="mt-4 text-muted-foreground text-lg leading-relaxed">
              {t('features.body')}
            </p>
            <div className="mt-8 space-y-4">
              {features.map((f, i) => (
                <div key={i} className="flex items-start gap-3">
                  <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                    <f.icon className="w-4 h-4 text-primary" />
                  </div>
                  <p className="text-sm font-medium text-foreground leading-relaxed">{f.text}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Phone mockup */}
          <div className="relative flex justify-center">
            <div className="w-64 md:w-72 bg-foreground rounded-[2.5rem] p-3 shadow-2xl rotate-2">
              <div className="bg-card rounded-[2rem] overflow-hidden" dir="ltr">
                <div className="bg-primary/10 px-4 py-3 flex items-center gap-2">
                  <div className="w-6 h-6 rounded-md gradient-primary flex items-center justify-center">
                    <span className="text-white text-[8px] font-bold">M</span>
                  </div>
                  <span lang="en" className="text-xs font-bold text-foreground">The Fish in the Tank</span>
                </div>
                <img src="/illustrations/1_3/page1.png" alt={t('features.mockAlt')} className="w-full aspect-[4/3] object-cover" loading="lazy" decoding="async" />
                <div className="px-4 py-3 space-y-2">
                  <EnglishOnly className="flex flex-wrap gap-1.5">
                    {['A', 'big', 'fish', 'is', 'in', 'the', 'tank!'].map(w => (
                      <span key={w} className="text-sm font-bold text-foreground bg-primary/5 px-2 py-0.5 rounded-lg" style={{ fontFamily: "'Andika', sans-serif" }}>
                        {w}
                      </span>
                    ))}
                  </EnglishOnly>
                  <div dir="auto" className="flex items-center gap-1 text-[10px] text-muted-foreground">
                    <Volume2 className="w-3 h-3" /> {t('features.tapHint')}
                  </div>
                </div>
              </div>
            </div>
            {/* Print sticker — the second half of "read OR print" */}
            <span
              className="absolute -bottom-3 end-2 sm:end-10 rounded-full bg-white px-4 py-2 text-xs font-extrabold -rotate-3 text-emerald-700 inline-flex items-center gap-1.5"
              style={{ boxShadow: STICKER, border: '2px solid #fff', outline: '2px solid #22C55E40' }}
            >
              <Printer className="w-3.5 h-3.5" /> {t('features.printSticker')}
            </span>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─── PRICING ─── */
function FreeForAll({ onSignUp, onSupport }: { onSignUp: () => void; onSupport: () => void }) {
  const { t } = useTranslation('landing');
  const r = useReveal();

  return (
    <section className="py-14 md:py-20 bg-card">
      <div ref={r.ref} className={`max-w-4xl mx-auto px-4 sm:px-6 transition-all duration-700 ${r.visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        <div className="text-center mb-10">
          <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight">{t('free.title')}</h2>
          <p className="mt-3 text-muted-foreground text-lg">{t('free.subtitle')}</p>
        </div>

        <div className="grid sm:grid-cols-2 gap-5">
          {/* Read & play — nothing needed */}
          <div className="bg-background rounded-[2rem] p-6 flex flex-col" style={{ boxShadow: STICKER, border: '1px solid rgba(40,30,40,0.05)' }}>
            <h3 className="font-display text-lg font-extrabold text-foreground">{t('free.read.title')}</h3>
            <div className="mt-2 mb-5"><span className="font-display text-4xl font-extrabold text-foreground">£0</span><span className="text-sm text-muted-foreground font-semibold ms-1">{t('free.read.note')}</span></div>
            <ul className="space-y-3 mb-6 flex-1">
              {[t('free.read.items.books'), t('free.read.items.tapToHear'), t('free.read.items.games'), t('free.read.items.check')].map(f => (
                <li key={f} className="flex items-center gap-2 text-sm text-muted-foreground">
                  <CheckCircle2 className="w-4 h-4 text-[hsl(var(--level-3))] shrink-0" /> {f}
                </li>
              ))}
            </ul>
            <Link to="/library" className="w-full py-3 rounded-2xl border-2 border-primary text-primary font-display font-extrabold text-sm hover:bg-primary/5 transition-colors text-center">
              {t('free.read.cta')}
            </Link>
          </div>

          {/* Download — free account */}
          <div className="relative bg-background rounded-[2rem] p-6 flex flex-col" style={{ boxShadow: STICKER, border: `2px solid ${PINK}`, outline: `4px solid ${PINK}20` }}>
            <span
              className="absolute -top-3 end-5 rounded-full bg-white px-3 py-1 text-[11px] font-extrabold rotate-2 text-primary-ink"
              style={{ boxShadow: STICKER, border: '2px solid #fff', outline: `2px solid ${PINK}40` }}
            >
              {t('free.print.badge')}
            </span>
            <h3 className="font-display text-lg font-extrabold text-foreground">{t('free.print.title')}</h3>
            <div className="mt-2 mb-5"><span className="font-display text-4xl font-extrabold text-foreground">£0</span><span className="text-sm text-muted-foreground font-semibold ms-1">{t('free.print.note')}</span></div>
            <ul className="space-y-3 mb-6 flex-1">
              {[t('free.print.items.everything'), t('free.print.items.download'), t('free.print.items.worksheets'), t('free.print.items.progress')].map(f => (
                <li key={f} className="flex items-center gap-2 text-sm text-muted-foreground">
                  <CheckCircle2 className="w-4 h-4 text-primary shrink-0" /> {f}
                </li>
              ))}
            </ul>
            <button
              onClick={onSignUp}
              className="w-full py-3 rounded-2xl font-display font-extrabold text-sm text-white transition-all active:translate-y-[3px]"
              style={{ background: PINK, boxShadow: `0 4px 0 ${PINK_INK}` }}
            >
              {t('free.print.cta')}
            </button>
          </div>
        </div>

        <p className="text-center text-sm text-muted-foreground mt-6">
          <Trans
            t={t}
            i18nKey="free.support"
            components={{ btn: <button onClick={onSupport} className="font-bold text-primary-ink hover:underline" /> }}
          />
        </p>
      </div>
    </section>
  );
}

/* ─── FOOTER CTA ─── */
function FooterCTA({ onBrowse, onAssess }: { onBrowse: () => void; onAssess: () => void }) {
  const { t } = useTranslation('landing');
  return (
    <section className="py-16 md:py-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 text-center">
        <div className="bg-gradient-to-br from-primary/10 via-background to-[hsl(var(--level-5))]/10 rounded-[2.5rem] p-10 md:p-14 border border-primary/20">
          <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight">
            {t('footerCta.title')}
          </h2>
          <p className="mt-4 text-muted-foreground text-lg max-w-lg mx-auto">
            {t('footerCta.body')}
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center">
            <PushButton onClick={onBrowse}>
              <BookOpen className="w-5 h-5" /> {t('footerCta.explore')}
            </PushButton>
            <PushButton onClick={onAssess} tone="white">
              {t('footerCta.check')} <ChevronRight className="w-4 h-4 rtl:-scale-x-100" />
            </PushButton>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─── FOOTER ─── */
function Footer() {
  const { t } = useTranslation('landing');
  const navigate = useNavigate();
  return (
    <footer className="border-t border-indigo-100 py-8 bg-gradient-to-b from-card to-indigo-50/40">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <img src="/logo/mpb-mark-transparent.png" alt="" className="w-8 h-8 object-contain" draggable={false} />
          <span dir="ltr" className="font-display text-sm font-bold text-foreground">MyPhonicsBooks</span>
        </div>
        <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-muted-foreground">
          <Link to="/create-book" className="hover:text-trust-ink transition-colors">{t('footer.createBook')}</Link>
          <Link to="/world-of-books" className="hover:text-trust-ink transition-colors">{t('footer.worldOfBooks')}</Link>
          <Link to="/shop" className="hover:text-trust-ink transition-colors">{t('footer.shop')}</Link>
          <Link to="/love" className="hover:text-trust-ink transition-colors">{t('footer.wallOfLove')}</Link>
          <a href="/privacy" className="hover:text-trust-ink transition-colors">{t('footer.privacy')}</a>
          <a href="/terms" className="hover:text-trust-ink transition-colors">{t('footer.terms')}</a>
          <a href="mailto:hello@myphonicsbooks.co.uk" className="hover:text-trust-ink transition-colors">{t('footer.contact')}</a>
          <button
            onClick={() => navigate('/admin')}
            className="hover:text-foreground transition-colors"
            aria-label={t('footer.admin')}
          >
            {t('footer.admin')}
          </button>
        </div>
        <p className="text-xs text-muted-foreground">{t('footer.madeWith')}</p>
      </div>
    </footer>
  );
}
