"""
public/worksheets/manifest.json  ->  src/data/forgedWorksheets.ts

The Library's WorksheetsPanel merges these folders into its per-book list:
a forged folder whose bookNumber matches an existing book adds a group to it
(and flips "coming-soon" to ready); otherwise it appears as a new folder.

  py -3.12 scripts/worksheets/write_site_data.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(ROOT, "public", "worksheets", "manifest.json")
OUT = os.path.join(ROOT, "src", "data", "forgedWorksheets.ts")


def main():
    m = json.load(open(MANIFEST, encoding="utf-8"))
    folders = []
    for p in m["packs"]:
        b = p["book"]
        sub = b.get("sub")  # "L4.1" journey number, or None for level extras
        folders.append({
            "id": "forged-" + p["folder"].lower().replace("/", "-"),
            "bookNumber": sub[1:] if sub else f"L{p['level']}",
            "title": b["title"],
            "focusSounds": b["sounds"],
            "status": "ready",
            "storyFileId": b.get("file_id"),
            "groups": [{
                "label": p["label"],
                "bundleHref": p["bundle"],
                "bundleLabel": f"Download all {len(p['sheets'])} sheets",
                "sheets": [{"href": s["href"], "title": s["title"], "thumb": s["thumb"], "objective": s["objective"]} for s in p["sheets"]],
            }],
        })
    ts = ("// GENERATED by scripts/worksheets/write_site_data.py from public/worksheets/manifest.json.\n"
          "// Do not edit by hand: re-run the forge batch, then this script.\n"
          "export type ForgedSheet = { href: string; title: string; thumb: string | null; objective: string };\n"
          "export type ForgedGroup = { label: string; bundleHref: string; bundleLabel: string; sheets: ForgedSheet[] };\n"
          "export type ForgedFolder = {\n"
          "  id: string; bookNumber: string; title: string; focusSounds: string[]; status: 'ready';\n"
          "  storyFileId: string | null; groups: ForgedGroup[];\n"
          "};\n\n"
          f"export const FORGED_FOLDERS: ForgedFolder[] = {json.dumps(folders, ensure_ascii=False, indent=2)};\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(ts)
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(folders)} folders, {sum(len(f['groups'][0]['sheets']) for f in folders)} sheets")


if __name__ == "__main__":
    main()
