// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE = the modern, more-secure OAuth flow. Required for Google
    // sign-in to land a session on the SPA on return. Without this the
    // redirect carries an auth code that nothing on the page knows how to
    // exchange, the user lands on the home route, and the Sign-In button
    // is still there.
    flowType: 'pkce',
    // Detect ?code=... or #access_token=... in the URL on first load and
    // exchange it for a session. Defaults to true in current supabase-js,
    // but being explicit prevents regressions if the default ever flips.
    detectSessionInUrl: true,
  }
});