// GENERATED by scripts/worksheets/write_site_data.py from public/worksheets/manifest.json.
// Do not edit by hand: re-run the forge batch, then this script.
export type ForgedSheet = { href: string; title: string; thumb: string | null; objective: string };
export type ForgedGroup = { label: string; bundleHref: string; bundleLabel: string; sheets: ForgedSheet[] };
export type ForgedFolder = {
  id: string; bookNumber: string; title: string; focusSounds: string[]; status: 'ready';
  storyFileId: string | null; groups: ForgedGroup[];
};

export const FORGED_FOLDERS: ForgedFolder[] = [
  {
    "id": "forged-l1-1_1_tap_tap_tap",
    "bookNumber": "1.1",
    "title": "Tap! Tap! Tap!",
    "focusSounds": [
      "s",
      "a",
      "t",
      "p",
      "i",
      "n"
    ],
    "status": "ready",
    "storyFileId": "1_1",
    "groups": [
      {
        "label": "More practice",
        "bundleHref": "/worksheets/L1/1_1_tap_tap_tap/pack.pdf",
        "bundleLabel": "Download all 3 sheets",
        "sheets": [
          {
            "href": "/worksheets/L1/1_1_tap_tap_tap/01_assess_s.pdf",
            "title": "Check-up: s",
            "thumb": "/worksheets/L1/1_1_tap_tap_tap/01_assess_s.png",
            "objective": "Show the sound s is secure before moving on."
          },
          {
            "href": "/worksheets/L1/1_1_tap_tap_tap/02_draw_s.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L1/1_1_tap_tap_tap/02_draw_s.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L1/1_1_tap_tap_tap/03_game_s.pdf",
            "title": "Story game: Tap! Tap! Tap!",
            "thumb": "/worksheets/L1/1_1_tap_tap_tap/03_game_s.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l1-1_2_the_mud_on_the_dog",
    "bookNumber": "1.2",
    "title": "The Mud on the Dog",
    "focusSounds": [
      "m",
      "d",
      "g",
      "o"
    ],
    "status": "ready",
    "storyFileId": "1_2",
    "groups": [
      {
        "label": "More practice",
        "bundleHref": "/worksheets/L1/1_2_the_mud_on_the_dog/pack.pdf",
        "bundleLabel": "Download all 3 sheets",
        "sheets": [
          {
            "href": "/worksheets/L1/1_2_the_mud_on_the_dog/01_assess_m.pdf",
            "title": "Check-up: m",
            "thumb": "/worksheets/L1/1_2_the_mud_on_the_dog/01_assess_m.png",
            "objective": "Show the sound m is secure before moving on."
          },
          {
            "href": "/worksheets/L1/1_2_the_mud_on_the_dog/02_draw_m.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L1/1_2_the_mud_on_the_dog/02_draw_m.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L1/1_2_the_mud_on_the_dog/03_game_m.pdf",
            "title": "Story game: The Mud on the Dog",
            "thumb": "/worksheets/L1/1_2_the_mud_on_the_dog/03_game_m.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l2-1_4_the_red_socks",
    "bookNumber": "2.1",
    "title": "The Red Socks",
    "focusSounds": [
      "c",
      "k",
      "ck",
      "e"
    ],
    "status": "ready",
    "storyFileId": "1_4",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L2/1_4_the_red_socks/pack.pdf",
        "bundleLabel": "Download all 7 sheets",
        "sheets": [
          {
            "href": "/worksheets/L2/1_4_the_red_socks/01_handwriting_c.pdf",
            "title": "Trace and write c",
            "thumb": "/worksheets/L2/1_4_the_red_socks/01_handwriting_c.png",
            "objective": "Form the sound c correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_4_the_red_socks/02_handwriting_k.pdf",
            "title": "Trace and write k",
            "thumb": "/worksheets/L2/1_4_the_red_socks/02_handwriting_k.png",
            "objective": "Form the sound k correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_4_the_red_socks/03_handwriting_ck.pdf",
            "title": "Trace and write ck",
            "thumb": "/worksheets/L2/1_4_the_red_socks/03_handwriting_ck.png",
            "objective": "Form the sound ck correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_4_the_red_socks/04_handwriting_e.pdf",
            "title": "Trace and write e",
            "thumb": "/worksheets/L2/1_4_the_red_socks/04_handwriting_e.png",
            "objective": "Form the sound e correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_4_the_red_socks/05_segmenting_c.pdf",
            "title": "Hear and build c",
            "thumb": "/worksheets/L2/1_4_the_red_socks/05_segmenting_c.png",
            "objective": "Hear every sound in a c word and write it down."
          },
          {
            "href": "/worksheets/L2/1_4_the_red_socks/06_draw_c.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L2/1_4_the_red_socks/06_draw_c.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L2/1_4_the_red_socks/07_game_c.pdf",
            "title": "Story game: The Red Socks",
            "thumb": "/worksheets/L2/1_4_the_red_socks/07_game_c.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l2-1_5_run_pup_run",
    "bookNumber": "2.2",
    "title": "Run, Pup, Run!",
    "focusSounds": [
      "u",
      "r",
      "h",
      "b"
    ],
    "status": "ready",
    "storyFileId": "1_5",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L2/1_5_run_pup_run/pack.pdf",
        "bundleLabel": "Download all 7 sheets",
        "sheets": [
          {
            "href": "/worksheets/L2/1_5_run_pup_run/01_handwriting_u.pdf",
            "title": "Trace and write u",
            "thumb": "/worksheets/L2/1_5_run_pup_run/01_handwriting_u.png",
            "objective": "Form the sound u correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_5_run_pup_run/02_handwriting_r.pdf",
            "title": "Trace and write r",
            "thumb": "/worksheets/L2/1_5_run_pup_run/02_handwriting_r.png",
            "objective": "Form the sound r correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_5_run_pup_run/03_handwriting_h.pdf",
            "title": "Trace and write h",
            "thumb": "/worksheets/L2/1_5_run_pup_run/03_handwriting_h.png",
            "objective": "Form the sound h correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_5_run_pup_run/04_handwriting_b.pdf",
            "title": "Trace and write b",
            "thumb": "/worksheets/L2/1_5_run_pup_run/04_handwriting_b.png",
            "objective": "Form the sound b correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_5_run_pup_run/05_segmenting_u.pdf",
            "title": "Hear and build u",
            "thumb": "/worksheets/L2/1_5_run_pup_run/05_segmenting_u.png",
            "objective": "Hear every sound in a u word and write it down."
          },
          {
            "href": "/worksheets/L2/1_5_run_pup_run/06_draw_u.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L2/1_5_run_pup_run/06_draw_u.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L2/1_5_run_pup_run/07_game_u.pdf",
            "title": "Story game: Run, Pup, Run!",
            "thumb": "/worksheets/L2/1_5_run_pup_run/07_game_u.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l2-1_6_fox_fell_off",
    "bookNumber": "2.3",
    "title": "Fox Fell Off!",
    "focusSounds": [
      "f",
      "l",
      "ff",
      "ll"
    ],
    "status": "ready",
    "storyFileId": "1_6",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L2/1_6_fox_fell_off/pack.pdf",
        "bundleLabel": "Download all 7 sheets",
        "sheets": [
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/01_handwriting_f.pdf",
            "title": "Trace and write f",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/01_handwriting_f.png",
            "objective": "Form the sound f correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/02_handwriting_l.pdf",
            "title": "Trace and write l",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/02_handwriting_l.png",
            "objective": "Form the sound l correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/03_handwriting_ff.pdf",
            "title": "Trace and write ff",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/03_handwriting_ff.png",
            "objective": "Form the sound ff correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/04_handwriting_ll.pdf",
            "title": "Trace and write ll",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/04_handwriting_ll.png",
            "objective": "Form the sound ll correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/05_segmenting_f.pdf",
            "title": "Hear and build f",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/05_segmenting_f.png",
            "objective": "Hear every sound in a f word and write it down."
          },
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/06_draw_f.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/06_draw_f.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L2/1_6_fox_fell_off/07_game_f.pdf",
            "title": "Story game: Fox Fell Off!",
            "thumb": "/worksheets/L2/1_6_fox_fell_off/07_game_f.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l2-1_7_the_jam_jug",
    "bookNumber": "2.4",
    "title": "The Jam Jug",
    "focusSounds": [
      "j",
      "v",
      "w"
    ],
    "status": "ready",
    "storyFileId": "1_7",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L2/1_7_the_jam_jug/pack.pdf",
        "bundleLabel": "Download all 5 sheets",
        "sheets": [
          {
            "href": "/worksheets/L2/1_7_the_jam_jug/01_handwriting_j.pdf",
            "title": "Trace and write j",
            "thumb": "/worksheets/L2/1_7_the_jam_jug/01_handwriting_j.png",
            "objective": "Form the sound j correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_7_the_jam_jug/03_handwriting_w.pdf",
            "title": "Trace and write w",
            "thumb": "/worksheets/L2/1_7_the_jam_jug/03_handwriting_w.png",
            "objective": "Form the sound w correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_7_the_jam_jug/04_segmenting_j.pdf",
            "title": "Hear and build j",
            "thumb": "/worksheets/L2/1_7_the_jam_jug/04_segmenting_j.png",
            "objective": "Hear every sound in a j word and write it down."
          },
          {
            "href": "/worksheets/L2/1_7_the_jam_jug/05_draw_j.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L2/1_7_the_jam_jug/05_draw_j.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L2/1_7_the_jam_jug/06_game_j.pdf",
            "title": "Story game: The Jam Jug",
            "thumb": "/worksheets/L2/1_7_the_jam_jug/06_game_j.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l2-1_8_the_yak_and_the_box",
    "bookNumber": "2.5",
    "title": "The Yak and the Box",
    "focusSounds": [
      "x",
      "y",
      "z"
    ],
    "status": "ready",
    "storyFileId": "1_8",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L2/1_8_the_yak_and_the_box/pack.pdf",
        "bundleLabel": "Download all 5 sheets",
        "sheets": [
          {
            "href": "/worksheets/L2/1_8_the_yak_and_the_box/01_handwriting_x.pdf",
            "title": "Trace and write x",
            "thumb": "/worksheets/L2/1_8_the_yak_and_the_box/01_handwriting_x.png",
            "objective": "Form the sound x correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_8_the_yak_and_the_box/02_handwriting_y.pdf",
            "title": "Trace and write y",
            "thumb": "/worksheets/L2/1_8_the_yak_and_the_box/02_handwriting_y.png",
            "objective": "Form the sound y correctly and write words that use it."
          },
          {
            "href": "/worksheets/L2/1_8_the_yak_and_the_box/04_segmenting_x.pdf",
            "title": "Hear and build x",
            "thumb": "/worksheets/L2/1_8_the_yak_and_the_box/04_segmenting_x.png",
            "objective": "Hear every sound in a x word and write it down."
          },
          {
            "href": "/worksheets/L2/1_8_the_yak_and_the_box/05_draw_x.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L2/1_8_the_yak_and_the_box/05_draw_x.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L2/1_8_the_yak_and_the_box/06_game_x.pdf",
            "title": "Story game: The Yak and the Box",
            "thumb": "/worksheets/L2/1_8_the_yak_and_the_box/06_game_x.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l3-1_3_the_fish_in_the_tank",
    "bookNumber": "3.1",
    "title": "The Fish in the Tank",
    "focusSounds": [
      "sh",
      "nk"
    ],
    "status": "ready",
    "storyFileId": "1_3",
    "groups": [
      {
        "label": "More practice",
        "bundleHref": "/worksheets/L3/1_3_the_fish_in_the_tank/pack.pdf",
        "bundleLabel": "Download all 3 sheets",
        "sheets": [
          {
            "href": "/worksheets/L3/1_3_the_fish_in_the_tank/01_assess_sh.pdf",
            "title": "Check-up: sh",
            "thumb": "/worksheets/L3/1_3_the_fish_in_the_tank/01_assess_sh.png",
            "objective": "Show the sound sh is secure before moving on."
          },
          {
            "href": "/worksheets/L3/1_3_the_fish_in_the_tank/02_draw_sh.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L3/1_3_the_fish_in_the_tank/02_draw_sh.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L3/1_3_the_fish_in_the_tank/03_game_sh.pdf",
            "title": "Story game: The Fish in the Tank",
            "thumb": "/worksheets/L3/1_3_the_fish_in_the_tank/03_game_sh.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l3-1_9_chop_chop_chop",
    "bookNumber": "3.2",
    "title": "Chop, Chop, Chop!",
    "focusSounds": [
      "ch",
      "th"
    ],
    "status": "ready",
    "storyFileId": "1_9",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L3/1_9_chop_chop_chop/pack.pdf",
        "bundleLabel": "Download all 5 sheets",
        "sheets": [
          {
            "href": "/worksheets/L3/1_9_chop_chop_chop/01_handwriting_ch.pdf",
            "title": "Trace and write ch",
            "thumb": "/worksheets/L3/1_9_chop_chop_chop/01_handwriting_ch.png",
            "objective": "Form the sound ch correctly and write words that use it."
          },
          {
            "href": "/worksheets/L3/1_9_chop_chop_chop/02_handwriting_th.pdf",
            "title": "Trace and write th",
            "thumb": "/worksheets/L3/1_9_chop_chop_chop/02_handwriting_th.png",
            "objective": "Form the sound th correctly and write words that use it."
          },
          {
            "href": "/worksheets/L3/1_9_chop_chop_chop/03_segmenting_ch.pdf",
            "title": "Hear and build ch",
            "thumb": "/worksheets/L3/1_9_chop_chop_chop/03_segmenting_ch.png",
            "objective": "Hear every sound in a ch word and write it down."
          },
          {
            "href": "/worksheets/L3/1_9_chop_chop_chop/04_draw_ch.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L3/1_9_chop_chop_chop/04_draw_ch.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L3/1_9_chop_chop_chop/05_game_ch.pdf",
            "title": "Story game: Chop, Chop, Chop!",
            "thumb": "/worksheets/L3/1_9_chop_chop_chop/05_game_ch.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l3-1_10_buzz_and_sing",
    "bookNumber": "3.3",
    "title": "Buzz and Sing!",
    "focusSounds": [
      "ng",
      "qu",
      "zz"
    ],
    "status": "ready",
    "storyFileId": "1_10",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L3/1_10_buzz_and_sing/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L3/1_10_buzz_and_sing/01_handwriting_ng.pdf",
            "title": "Trace and write ng",
            "thumb": "/worksheets/L3/1_10_buzz_and_sing/01_handwriting_ng.png",
            "objective": "Form the sound ng correctly and write words that use it."
          },
          {
            "href": "/worksheets/L3/1_10_buzz_and_sing/02_handwriting_qu.pdf",
            "title": "Trace and write qu",
            "thumb": "/worksheets/L3/1_10_buzz_and_sing/02_handwriting_qu.png",
            "objective": "Form the sound qu correctly and write words that use it."
          },
          {
            "href": "/worksheets/L3/1_10_buzz_and_sing/03_handwriting_zz.pdf",
            "title": "Trace and write zz",
            "thumb": "/worksheets/L3/1_10_buzz_and_sing/03_handwriting_zz.png",
            "objective": "Form the sound zz correctly and write words that use it."
          },
          {
            "href": "/worksheets/L3/1_10_buzz_and_sing/04_segmenting_ng.pdf",
            "title": "Hear and build ng",
            "thumb": "/worksheets/L3/1_10_buzz_and_sing/04_segmenting_ng.png",
            "objective": "Hear every sound in a ng word and write it down."
          },
          {
            "href": "/worksheets/L3/1_10_buzz_and_sing/05_draw_ng.pdf",
            "title": "Read, draw and write",
            "thumb": "/worksheets/L3/1_10_buzz_and_sing/05_draw_ng.png",
            "objective": "Read a sentence with the book's sounds and show you understood it."
          },
          {
            "href": "/worksheets/L3/1_10_buzz_and_sing/06_game_ng.pdf",
            "title": "Story game: Buzz and Sing!",
            "thumb": "/worksheets/L3/1_10_buzz_and_sing/06_game_ng.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l4-2_1_the_night_light",
    "bookNumber": "4.1",
    "title": "The Night Light",
    "focusSounds": [
      "ay",
      "ee",
      "igh"
    ],
    "status": "ready",
    "storyFileId": "2_1",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L4/2_1_the_night_light/pack.pdf",
        "bundleLabel": "Download all 8 sheets",
        "sheets": [
          {
            "href": "/worksheets/L4/2_1_the_night_light/01_segmenting_ay.pdf",
            "title": "Hear and build ay",
            "thumb": "/worksheets/L4/2_1_the_night_light/01_segmenting_ay.png",
            "objective": "Hear every sound in a ay word and write it down."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/02_sentences_ay.pdf",
            "title": "Read ay in sentences",
            "thumb": "/worksheets/L4/2_1_the_night_light/02_sentences_ay.png",
            "objective": "Read and complete sentences that use the sound ay."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/03_segmenting_ee.pdf",
            "title": "Hear and build ee",
            "thumb": "/worksheets/L4/2_1_the_night_light/03_segmenting_ee.png",
            "objective": "Hear every sound in a ee word and write it down."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/04_sentences_ee.pdf",
            "title": "Read ee in sentences",
            "thumb": "/worksheets/L4/2_1_the_night_light/04_sentences_ee.png",
            "objective": "Read and complete sentences that use the sound ee."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/05_segmenting_igh.pdf",
            "title": "Hear and build igh",
            "thumb": "/worksheets/L4/2_1_the_night_light/05_segmenting_igh.png",
            "objective": "Hear every sound in a igh word and write it down."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/06_sentences_igh.pdf",
            "title": "Read igh in sentences",
            "thumb": "/worksheets/L4/2_1_the_night_light/06_sentences_igh.png",
            "objective": "Read and complete sentences that use the sound igh."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/07_assess_ay.pdf",
            "title": "Check-up: ay",
            "thumb": "/worksheets/L4/2_1_the_night_light/07_assess_ay.png",
            "objective": "Show the sound ay is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_1_the_night_light/08_game_ay.pdf",
            "title": "Story game: The Night Light",
            "thumb": "/worksheets/L4/2_1_the_night_light/08_game_ay.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l4-2_2_hot_food_cool_moon",
    "bookNumber": "4.2",
    "title": "Hot Food, Cool Moon",
    "focusSounds": [
      "ow",
      "oo"
    ],
    "status": "ready",
    "storyFileId": "2_2",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L4/2_2_hot_food_cool_moon/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L4/2_2_hot_food_cool_moon/01_segmenting_ow.pdf",
            "title": "Hear and build ow",
            "thumb": "/worksheets/L4/2_2_hot_food_cool_moon/01_segmenting_ow.png",
            "objective": "Hear every sound in a ow word and write it down."
          },
          {
            "href": "/worksheets/L4/2_2_hot_food_cool_moon/02_sentences_ow.pdf",
            "title": "Read ow in sentences",
            "thumb": "/worksheets/L4/2_2_hot_food_cool_moon/02_sentences_ow.png",
            "objective": "Read and complete sentences that use the sound ow."
          },
          {
            "href": "/worksheets/L4/2_2_hot_food_cool_moon/03_segmenting_oo.pdf",
            "title": "Hear and build oo",
            "thumb": "/worksheets/L4/2_2_hot_food_cool_moon/03_segmenting_oo.png",
            "objective": "Hear every sound in a oo word and write it down."
          },
          {
            "href": "/worksheets/L4/2_2_hot_food_cool_moon/04_sentences_oo.pdf",
            "title": "Read oo in sentences",
            "thumb": "/worksheets/L4/2_2_hot_food_cool_moon/04_sentences_oo.png",
            "objective": "Read and complete sentences that use the sound oo."
          },
          {
            "href": "/worksheets/L4/2_2_hot_food_cool_moon/05_assess_ow.pdf",
            "title": "Check-up: ow",
            "thumb": "/worksheets/L4/2_2_hot_food_cool_moon/05_assess_ow.png",
            "objective": "Show the sound ow is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_2_hot_food_cool_moon/06_game_ow.pdf",
            "title": "Story game: Hot Food, Cool Moon",
            "thumb": "/worksheets/L4/2_2_hot_food_cool_moon/06_game_ow.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l4-2_3_morning_on_the_farm",
    "bookNumber": "4.3",
    "title": "Morning on the Farm",
    "focusSounds": [
      "ar",
      "or"
    ],
    "status": "ready",
    "storyFileId": "2_3",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L4/2_3_morning_on_the_farm/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L4/2_3_morning_on_the_farm/01_segmenting_ar.pdf",
            "title": "Hear and build ar",
            "thumb": "/worksheets/L4/2_3_morning_on_the_farm/01_segmenting_ar.png",
            "objective": "Hear every sound in a ar word and write it down."
          },
          {
            "href": "/worksheets/L4/2_3_morning_on_the_farm/02_sentences_ar.pdf",
            "title": "Read ar in sentences",
            "thumb": "/worksheets/L4/2_3_morning_on_the_farm/02_sentences_ar.png",
            "objective": "Read and complete sentences that use the sound ar."
          },
          {
            "href": "/worksheets/L4/2_3_morning_on_the_farm/03_segmenting_or.pdf",
            "title": "Hear and build or",
            "thumb": "/worksheets/L4/2_3_morning_on_the_farm/03_segmenting_or.png",
            "objective": "Hear every sound in a or word and write it down."
          },
          {
            "href": "/worksheets/L4/2_3_morning_on_the_farm/04_sentences_or.pdf",
            "title": "Read or in sentences",
            "thumb": "/worksheets/L4/2_3_morning_on_the_farm/04_sentences_or.png",
            "objective": "Read and complete sentences that use the sound or."
          },
          {
            "href": "/worksheets/L4/2_3_morning_on_the_farm/05_assess_ar.pdf",
            "title": "Check-up: ar",
            "thumb": "/worksheets/L4/2_3_morning_on_the_farm/05_assess_ar.png",
            "objective": "Show the sound ar is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_3_morning_on_the_farm/06_game_ar.pdf",
            "title": "Story game: Morning on the Farm",
            "thumb": "/worksheets/L4/2_3_morning_on_the_farm/06_game_ar.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l4-2_4_the_fair_in_the_air",
    "bookNumber": "4.4",
    "title": "The Fair in the Air",
    "focusSounds": [
      "air",
      "ir"
    ],
    "status": "ready",
    "storyFileId": "2_4",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L4/2_4_the_fair_in_the_air/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L4/2_4_the_fair_in_the_air/01_segmenting_air.pdf",
            "title": "Hear and build air",
            "thumb": "/worksheets/L4/2_4_the_fair_in_the_air/01_segmenting_air.png",
            "objective": "Hear every sound in a air word and write it down."
          },
          {
            "href": "/worksheets/L4/2_4_the_fair_in_the_air/02_sentences_air.pdf",
            "title": "Read air in sentences",
            "thumb": "/worksheets/L4/2_4_the_fair_in_the_air/02_sentences_air.png",
            "objective": "Read and complete sentences that use the sound air."
          },
          {
            "href": "/worksheets/L4/2_4_the_fair_in_the_air/03_segmenting_ir.pdf",
            "title": "Hear and build ir",
            "thumb": "/worksheets/L4/2_4_the_fair_in_the_air/03_segmenting_ir.png",
            "objective": "Hear every sound in a ir word and write it down."
          },
          {
            "href": "/worksheets/L4/2_4_the_fair_in_the_air/04_sentences_ir.pdf",
            "title": "Read ir in sentences",
            "thumb": "/worksheets/L4/2_4_the_fair_in_the_air/04_sentences_ir.png",
            "objective": "Read and complete sentences that use the sound ir."
          },
          {
            "href": "/worksheets/L4/2_4_the_fair_in_the_air/05_assess_air.pdf",
            "title": "Check-up: air",
            "thumb": "/worksheets/L4/2_4_the_fair_in_the_air/05_assess_air.png",
            "objective": "Show the sound air is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_4_the_fair_in_the_air/06_game_air.pdf",
            "title": "Story game: The Fair in the Air",
            "thumb": "/worksheets/L4/2_4_the_fair_in_the_air/06_game_air.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l4-2_5_round_and_round",
    "bookNumber": "4.5",
    "title": "Round and Round",
    "focusSounds": [
      "ou",
      "oy"
    ],
    "status": "ready",
    "storyFileId": "2_5",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L4/2_5_round_and_round/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L4/2_5_round_and_round/01_segmenting_ou.pdf",
            "title": "Hear and build ou",
            "thumb": "/worksheets/L4/2_5_round_and_round/01_segmenting_ou.png",
            "objective": "Hear every sound in a ou word and write it down."
          },
          {
            "href": "/worksheets/L4/2_5_round_and_round/02_sentences_ou.pdf",
            "title": "Read ou in sentences",
            "thumb": "/worksheets/L4/2_5_round_and_round/02_sentences_ou.png",
            "objective": "Read and complete sentences that use the sound ou."
          },
          {
            "href": "/worksheets/L4/2_5_round_and_round/03_segmenting_oy.pdf",
            "title": "Hear and build oy",
            "thumb": "/worksheets/L4/2_5_round_and_round/03_segmenting_oy.png",
            "objective": "Hear every sound in a oy word and write it down."
          },
          {
            "href": "/worksheets/L4/2_5_round_and_round/04_sentences_oy.pdf",
            "title": "Read oy in sentences",
            "thumb": "/worksheets/L4/2_5_round_and_round/04_sentences_oy.png",
            "objective": "Read and complete sentences that use the sound oy."
          },
          {
            "href": "/worksheets/L4/2_5_round_and_round/05_assess_ou.pdf",
            "title": "Check-up: ou",
            "thumb": "/worksheets/L4/2_5_round_and_round/05_assess_ou.png",
            "objective": "Show the sound ou is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_5_round_and_round/06_game_ou.pdf",
            "title": "Story game: Round and Round",
            "thumb": "/worksheets/L4/2_5_round_and_round/06_game_ou.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l4-2_6_the_night_fair",
    "bookNumber": "4.6",
    "title": "The Night Fair",
    "focusSounds": [
      "ay",
      "ee",
      "igh",
      "ow",
      "oo",
      "ar",
      "or",
      "air",
      "ir",
      "ou",
      "oy"
    ],
    "status": "ready",
    "storyFileId": "2_6",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L4/2_6_the_night_fair/pack.pdf",
        "bundleLabel": "Download all 12 sheets",
        "sheets": [
          {
            "href": "/worksheets/L4/2_6_the_night_fair/01_assess_ay.pdf",
            "title": "Check-up: ay",
            "thumb": "/worksheets/L4/2_6_the_night_fair/01_assess_ay.png",
            "objective": "Show the sound ay is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/02_assess_ee.pdf",
            "title": "Check-up: ee",
            "thumb": "/worksheets/L4/2_6_the_night_fair/02_assess_ee.png",
            "objective": "Show the sound ee is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/03_assess_igh.pdf",
            "title": "Check-up: igh",
            "thumb": "/worksheets/L4/2_6_the_night_fair/03_assess_igh.png",
            "objective": "Show the sound igh is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/04_assess_ow.pdf",
            "title": "Check-up: ow",
            "thumb": "/worksheets/L4/2_6_the_night_fair/04_assess_ow.png",
            "objective": "Show the sound ow is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/05_assess_oo.pdf",
            "title": "Check-up: oo",
            "thumb": "/worksheets/L4/2_6_the_night_fair/05_assess_oo.png",
            "objective": "Show the sound oo is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/06_assess_ar.pdf",
            "title": "Check-up: ar",
            "thumb": "/worksheets/L4/2_6_the_night_fair/06_assess_ar.png",
            "objective": "Show the sound ar is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/07_assess_or.pdf",
            "title": "Check-up: or",
            "thumb": "/worksheets/L4/2_6_the_night_fair/07_assess_or.png",
            "objective": "Show the sound or is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/08_assess_air.pdf",
            "title": "Check-up: air",
            "thumb": "/worksheets/L4/2_6_the_night_fair/08_assess_air.png",
            "objective": "Show the sound air is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/09_assess_ir.pdf",
            "title": "Check-up: ir",
            "thumb": "/worksheets/L4/2_6_the_night_fair/09_assess_ir.png",
            "objective": "Show the sound ir is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/10_assess_ou.pdf",
            "title": "Check-up: ou",
            "thumb": "/worksheets/L4/2_6_the_night_fair/10_assess_ou.png",
            "objective": "Show the sound ou is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/11_assess_oy.pdf",
            "title": "Check-up: oy",
            "thumb": "/worksheets/L4/2_6_the_night_fair/11_assess_oy.png",
            "objective": "Show the sound oy is secure before moving on."
          },
          {
            "href": "/worksheets/L4/2_6_the_night_fair/12_game_ay.pdf",
            "title": "Story game: The Night Fair",
            "thumb": "/worksheets/L4/2_6_the_night_fair/12_game_ay.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l5-3_1_the_big_bike_race",
    "bookNumber": "5.1",
    "title": "The Big Bike Race",
    "focusSounds": [
      "a-e",
      "i-e"
    ],
    "status": "ready",
    "storyFileId": "3_1",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L5/3_1_the_big_bike_race/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L5/3_1_the_big_bike_race/01_spelling_ae.pdf",
            "title": "Spell a-e words",
            "thumb": "/worksheets/L5/3_1_the_big_bike_race/01_spelling_ae.png",
            "objective": "Choose the right spelling for the a-e sound and use it."
          },
          {
            "href": "/worksheets/L5/3_1_the_big_bike_race/02_sentences_ae.pdf",
            "title": "Read a-e in sentences",
            "thumb": "/worksheets/L5/3_1_the_big_bike_race/02_sentences_ae.png",
            "objective": "Read and complete sentences that use the sound a-e."
          },
          {
            "href": "/worksheets/L5/3_1_the_big_bike_race/03_spelling_ie.pdf",
            "title": "Spell i-e words",
            "thumb": "/worksheets/L5/3_1_the_big_bike_race/03_spelling_ie.png",
            "objective": "Choose the right spelling for the i-e sound and use it."
          },
          {
            "href": "/worksheets/L5/3_1_the_big_bike_race/04_sentences_ie.pdf",
            "title": "Read i-e in sentences",
            "thumb": "/worksheets/L5/3_1_the_big_bike_race/04_sentences_ie.png",
            "objective": "Read and complete sentences that use the sound i-e."
          },
          {
            "href": "/worksheets/L5/3_1_the_big_bike_race/05_assess_ae.pdf",
            "title": "Check-up: a-e",
            "thumb": "/worksheets/L5/3_1_the_big_bike_race/05_assess_ae.png",
            "objective": "Show the sound a-e is secure before moving on."
          },
          {
            "href": "/worksheets/L5/3_1_the_big_bike_race/06_game_ae.pdf",
            "title": "Story game: The Big Bike Race",
            "thumb": "/worksheets/L5/3_1_the_big_bike_race/06_game_ae.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l5-3_2_lost_at_the_night_market",
    "bookNumber": "5.2",
    "title": "Lost at the Night Market",
    "focusSounds": [
      "o-e",
      "u-e"
    ],
    "status": "ready",
    "storyFileId": "3_2",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L5/3_2_lost_at_the_night_market/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L5/3_2_lost_at_the_night_market/01_spelling_oe.pdf",
            "title": "Spell o-e words",
            "thumb": "/worksheets/L5/3_2_lost_at_the_night_market/01_spelling_oe.png",
            "objective": "Choose the right spelling for the o-e sound and use it."
          },
          {
            "href": "/worksheets/L5/3_2_lost_at_the_night_market/02_sentences_oe.pdf",
            "title": "Read o-e in sentences",
            "thumb": "/worksheets/L5/3_2_lost_at_the_night_market/02_sentences_oe.png",
            "objective": "Read and complete sentences that use the sound o-e."
          },
          {
            "href": "/worksheets/L5/3_2_lost_at_the_night_market/03_spelling_ue.pdf",
            "title": "Spell u-e words",
            "thumb": "/worksheets/L5/3_2_lost_at_the_night_market/03_spelling_ue.png",
            "objective": "Choose the right spelling for the u-e sound and use it."
          },
          {
            "href": "/worksheets/L5/3_2_lost_at_the_night_market/04_sentences_ue.pdf",
            "title": "Read u-e in sentences",
            "thumb": "/worksheets/L5/3_2_lost_at_the_night_market/04_sentences_ue.png",
            "objective": "Read and complete sentences that use the sound u-e."
          },
          {
            "href": "/worksheets/L5/3_2_lost_at_the_night_market/05_assess_oe.pdf",
            "title": "Check-up: o-e",
            "thumb": "/worksheets/L5/3_2_lost_at_the_night_market/05_assess_oe.png",
            "objective": "Show the sound o-e is secure before moving on."
          },
          {
            "href": "/worksheets/L5/3_2_lost_at_the_night_market/06_game_oe.pdf",
            "title": "Story game: Lost at the Night Market",
            "thumb": "/worksheets/L5/3_2_lost_at_the_night_market/06_game_oe.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l5-3_3_the_dream_team",
    "bookNumber": "5.3",
    "title": "The Dream Team",
    "focusSounds": [
      "ea",
      "ie"
    ],
    "status": "ready",
    "storyFileId": "3_3",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L5/3_3_the_dream_team/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L5/3_3_the_dream_team/01_spelling_ea.pdf",
            "title": "Spell ea words",
            "thumb": "/worksheets/L5/3_3_the_dream_team/01_spelling_ea.png",
            "objective": "Choose the right spelling for the ea sound and use it."
          },
          {
            "href": "/worksheets/L5/3_3_the_dream_team/02_sentences_ea.pdf",
            "title": "Read ea in sentences",
            "thumb": "/worksheets/L5/3_3_the_dream_team/02_sentences_ea.png",
            "objective": "Read and complete sentences that use the sound ea."
          },
          {
            "href": "/worksheets/L5/3_3_the_dream_team/03_spelling_ie.pdf",
            "title": "Spell ie words",
            "thumb": "/worksheets/L5/3_3_the_dream_team/03_spelling_ie.png",
            "objective": "Choose the right spelling for the ie sound and use it."
          },
          {
            "href": "/worksheets/L5/3_3_the_dream_team/04_sentences_ie.pdf",
            "title": "Read ie in sentences",
            "thumb": "/worksheets/L5/3_3_the_dream_team/04_sentences_ie.png",
            "objective": "Read and complete sentences that use the sound ie."
          },
          {
            "href": "/worksheets/L5/3_3_the_dream_team/05_assess_ea.pdf",
            "title": "Check-up: ea",
            "thumb": "/worksheets/L5/3_3_the_dream_team/05_assess_ea.png",
            "objective": "Show the sound ea is secure before moving on."
          },
          {
            "href": "/worksheets/L5/3_3_the_dream_team/06_game_ea.pdf",
            "title": "Story game: The Dream Team",
            "thumb": "/worksheets/L5/3_3_the_dream_team/06_game_ea.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l5-3_4_what_min_saw",
    "bookNumber": "5.4",
    "title": "What Min Saw",
    "focusSounds": [
      "oi",
      "aw"
    ],
    "status": "ready",
    "storyFileId": "3_4",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L5/3_4_what_min_saw/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L5/3_4_what_min_saw/01_spelling_oi.pdf",
            "title": "Spell oi words",
            "thumb": "/worksheets/L5/3_4_what_min_saw/01_spelling_oi.png",
            "objective": "Choose the right spelling for the oi sound and use it."
          },
          {
            "href": "/worksheets/L5/3_4_what_min_saw/02_sentences_oi.pdf",
            "title": "Read oi in sentences",
            "thumb": "/worksheets/L5/3_4_what_min_saw/02_sentences_oi.png",
            "objective": "Read and complete sentences that use the sound oi."
          },
          {
            "href": "/worksheets/L5/3_4_what_min_saw/03_spelling_aw.pdf",
            "title": "Spell aw words",
            "thumb": "/worksheets/L5/3_4_what_min_saw/03_spelling_aw.png",
            "objective": "Choose the right spelling for the aw sound and use it."
          },
          {
            "href": "/worksheets/L5/3_4_what_min_saw/04_sentences_aw.pdf",
            "title": "Read aw in sentences",
            "thumb": "/worksheets/L5/3_4_what_min_saw/04_sentences_aw.png",
            "objective": "Read and complete sentences that use the sound aw."
          },
          {
            "href": "/worksheets/L5/3_4_what_min_saw/05_assess_oi.pdf",
            "title": "Check-up: oi",
            "thumb": "/worksheets/L5/3_4_what_min_saw/05_assess_oi.png",
            "objective": "Show the sound oi is secure before moving on."
          },
          {
            "href": "/worksheets/L5/3_4_what_min_saw/06_game_oi.pdf",
            "title": "Story game: What Min Saw",
            "thumb": "/worksheets/L5/3_4_what_min_saw/06_game_oi.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l5-3_5_the_boat_with_the_red_sail",
    "bookNumber": "5.5",
    "title": "The Boat with the Red Sail",
    "focusSounds": [
      "ai",
      "oa"
    ],
    "status": "ready",
    "storyFileId": "3_5",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L5/3_5_the_boat_with_the_red_sail/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L5/3_5_the_boat_with_the_red_sail/01_spelling_ai.pdf",
            "title": "Spell ai words",
            "thumb": "/worksheets/L5/3_5_the_boat_with_the_red_sail/01_spelling_ai.png",
            "objective": "Choose the right spelling for the ai sound and use it."
          },
          {
            "href": "/worksheets/L5/3_5_the_boat_with_the_red_sail/02_sentences_ai.pdf",
            "title": "Read ai in sentences",
            "thumb": "/worksheets/L5/3_5_the_boat_with_the_red_sail/02_sentences_ai.png",
            "objective": "Read and complete sentences that use the sound ai."
          },
          {
            "href": "/worksheets/L5/3_5_the_boat_with_the_red_sail/03_spelling_oa.pdf",
            "title": "Spell oa words",
            "thumb": "/worksheets/L5/3_5_the_boat_with_the_red_sail/03_spelling_oa.png",
            "objective": "Choose the right spelling for the oa sound and use it."
          },
          {
            "href": "/worksheets/L5/3_5_the_boat_with_the_red_sail/04_sentences_oa.pdf",
            "title": "Read oa in sentences",
            "thumb": "/worksheets/L5/3_5_the_boat_with_the_red_sail/04_sentences_oa.png",
            "objective": "Read and complete sentences that use the sound oa."
          },
          {
            "href": "/worksheets/L5/3_5_the_boat_with_the_red_sail/05_assess_ai.pdf",
            "title": "Check-up: ai",
            "thumb": "/worksheets/L5/3_5_the_boat_with_the_red_sail/05_assess_ai.png",
            "objective": "Show the sound ai is secure before moving on."
          },
          {
            "href": "/worksheets/L5/3_5_the_boat_with_the_red_sail/06_game_ai.pdf",
            "title": "Story game: The Boat with the Red Sail",
            "thumb": "/worksheets/L5/3_5_the_boat_with_the_red_sail/06_game_ai.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l6-4_1_the_purple_purse",
    "bookNumber": "6.1",
    "title": "The Purple Purse",
    "focusSounds": [
      "ur",
      "er"
    ],
    "status": "ready",
    "storyFileId": "4_1",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L6/4_1_the_purple_purse/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L6/4_1_the_purple_purse/01_spelling_ur.pdf",
            "title": "Spell ur words",
            "thumb": "/worksheets/L6/4_1_the_purple_purse/01_spelling_ur.png",
            "objective": "Choose the right spelling for the ur sound and use it."
          },
          {
            "href": "/worksheets/L6/4_1_the_purple_purse/02_code_ur.pdf",
            "title": "Crack the code: ur",
            "thumb": "/worksheets/L6/4_1_the_purple_purse/02_code_ur.png",
            "objective": "Decode ur words letter by letter."
          },
          {
            "href": "/worksheets/L6/4_1_the_purple_purse/03_spelling_er.pdf",
            "title": "Spell er words",
            "thumb": "/worksheets/L6/4_1_the_purple_purse/03_spelling_er.png",
            "objective": "Choose the right spelling for the er sound and use it."
          },
          {
            "href": "/worksheets/L6/4_1_the_purple_purse/04_code_er.pdf",
            "title": "Crack the code: er",
            "thumb": "/worksheets/L6/4_1_the_purple_purse/04_code_er.png",
            "objective": "Decode er words letter by letter."
          },
          {
            "href": "/worksheets/L6/4_1_the_purple_purse/05_sentences_ur.pdf",
            "title": "Read ur in sentences",
            "thumb": "/worksheets/L6/4_1_the_purple_purse/05_sentences_ur.png",
            "objective": "Read and complete sentences that use the sound ur."
          },
          {
            "href": "/worksheets/L6/4_1_the_purple_purse/06_game_ur.pdf",
            "title": "Story game: The Purple Purse",
            "thumb": "/worksheets/L6/4_1_the_purple_purse/06_game_ur.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l6-4_2_the_brown_owl",
    "bookNumber": "6.2",
    "title": "The Brown Owl",
    "focusSounds": [
      "are",
      "ow"
    ],
    "status": "ready",
    "storyFileId": "4_2",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L6/4_2_the_brown_owl/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L6/4_2_the_brown_owl/01_spelling_are.pdf",
            "title": "Spell are words",
            "thumb": "/worksheets/L6/4_2_the_brown_owl/01_spelling_are.png",
            "objective": "Choose the right spelling for the are sound and use it."
          },
          {
            "href": "/worksheets/L6/4_2_the_brown_owl/02_code_are.pdf",
            "title": "Crack the code: are",
            "thumb": "/worksheets/L6/4_2_the_brown_owl/02_code_are.png",
            "objective": "Decode are words letter by letter."
          },
          {
            "href": "/worksheets/L6/4_2_the_brown_owl/03_spelling_ow.pdf",
            "title": "Spell ow words",
            "thumb": "/worksheets/L6/4_2_the_brown_owl/03_spelling_ow.png",
            "objective": "Choose the right spelling for the ow sound and use it."
          },
          {
            "href": "/worksheets/L6/4_2_the_brown_owl/04_code_ow.pdf",
            "title": "Crack the code: ow",
            "thumb": "/worksheets/L6/4_2_the_brown_owl/04_code_ow.png",
            "objective": "Decode ow words letter by letter."
          },
          {
            "href": "/worksheets/L6/4_2_the_brown_owl/05_sentences_are.pdf",
            "title": "Read are in sentences",
            "thumb": "/worksheets/L6/4_2_the_brown_owl/05_sentences_are.png",
            "objective": "Read and complete sentences that use the sound are."
          },
          {
            "href": "/worksheets/L6/4_2_the_brown_owl/06_game_are.pdf",
            "title": "Story game: The Brown Owl",
            "thumb": "/worksheets/L6/4_2_the_brown_owl/06_game_are.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l6-4_3_the_new_glue",
    "bookNumber": "6.3",
    "title": "The New Glue",
    "focusSounds": [
      "ew",
      "ue"
    ],
    "status": "ready",
    "storyFileId": "4_3",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L6/4_3_the_new_glue/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L6/4_3_the_new_glue/01_spelling_ew.pdf",
            "title": "Spell ew words",
            "thumb": "/worksheets/L6/4_3_the_new_glue/01_spelling_ew.png",
            "objective": "Choose the right spelling for the ew sound and use it."
          },
          {
            "href": "/worksheets/L6/4_3_the_new_glue/02_code_ew.pdf",
            "title": "Crack the code: ew",
            "thumb": "/worksheets/L6/4_3_the_new_glue/02_code_ew.png",
            "objective": "Decode ew words letter by letter."
          },
          {
            "href": "/worksheets/L6/4_3_the_new_glue/03_spelling_ue.pdf",
            "title": "Spell ue words",
            "thumb": "/worksheets/L6/4_3_the_new_glue/03_spelling_ue.png",
            "objective": "Choose the right spelling for the ue sound and use it."
          },
          {
            "href": "/worksheets/L6/4_3_the_new_glue/04_code_ue.pdf",
            "title": "Crack the code: ue",
            "thumb": "/worksheets/L6/4_3_the_new_glue/04_code_ue.png",
            "objective": "Decode ue words letter by letter."
          },
          {
            "href": "/worksheets/L6/4_3_the_new_glue/05_sentences_ew.pdf",
            "title": "Read ew in sentences",
            "thumb": "/worksheets/L6/4_3_the_new_glue/05_sentences_ew.png",
            "objective": "Read and complete sentences that use the sound ew."
          },
          {
            "href": "/worksheets/L6/4_3_the_new_glue/06_game_ew.pdf",
            "title": "Story game: The New Glue",
            "thumb": "/worksheets/L6/4_3_the_new_glue/06_game_ew.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l6-4_4_the_cheeky_monkey",
    "bookNumber": "6.4",
    "title": "The Cheeky Monkey",
    "focusSounds": [
      "ur",
      "er",
      "are",
      "ow",
      "ew",
      "ue"
    ],
    "status": "ready",
    "storyFileId": "4_4",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L6/4_4_the_cheeky_monkey/pack.pdf",
        "bundleLabel": "Download all 7 sheets",
        "sheets": [
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/01_assess_ur.pdf",
            "title": "Check-up: ur",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/01_assess_ur.png",
            "objective": "Show the sound ur is secure before moving on."
          },
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/02_assess_er.pdf",
            "title": "Check-up: er",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/02_assess_er.png",
            "objective": "Show the sound er is secure before moving on."
          },
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/03_assess_are.pdf",
            "title": "Check-up: are",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/03_assess_are.png",
            "objective": "Show the sound are is secure before moving on."
          },
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/04_assess_ow.pdf",
            "title": "Check-up: ow",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/04_assess_ow.png",
            "objective": "Show the sound ow is secure before moving on."
          },
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/05_assess_ew.pdf",
            "title": "Check-up: ew",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/05_assess_ew.png",
            "objective": "Show the sound ew is secure before moving on."
          },
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/06_assess_ue.pdf",
            "title": "Check-up: ue",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/06_assess_ue.png",
            "objective": "Show the sound ue is secure before moving on."
          },
          {
            "href": "/worksheets/L6/4_4_the_cheeky_monkey/07_game_ur.pdf",
            "title": "Story game: The Cheeky Monkey",
            "thumb": "/worksheets/L6/4_4_the_cheeky_monkey/07_game_ur.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l7-5_1_before_the_shore",
    "bookNumber": "7.1",
    "title": "Before the Shore",
    "focusSounds": [
      "ire",
      "ore"
    ],
    "status": "ready",
    "storyFileId": "5_1",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L7/5_1_before_the_shore/pack.pdf",
        "bundleLabel": "Download all 4 sheets",
        "sheets": [
          {
            "href": "/worksheets/L7/5_1_before_the_shore/01_spelling_ire.pdf",
            "title": "Spell ire words",
            "thumb": "/worksheets/L7/5_1_before_the_shore/01_spelling_ire.png",
            "objective": "Choose the right spelling for the ire sound and use it."
          },
          {
            "href": "/worksheets/L7/5_1_before_the_shore/03_spelling_ore.pdf",
            "title": "Spell ore words",
            "thumb": "/worksheets/L7/5_1_before_the_shore/03_spelling_ore.png",
            "objective": "Choose the right spelling for the ore sound and use it."
          },
          {
            "href": "/worksheets/L7/5_1_before_the_shore/05_sentences_ire.pdf",
            "title": "Read ire in sentences",
            "thumb": "/worksheets/L7/5_1_before_the_shore/05_sentences_ire.png",
            "objective": "Read and complete sentences that use the sound ire."
          },
          {
            "href": "/worksheets/L7/5_1_before_the_shore/06_game_ire.pdf",
            "title": "Story game: Before the Shore",
            "thumb": "/worksheets/L7/5_1_before_the_shore/06_game_ire.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l7-5_2_near_the_door",
    "bookNumber": "7.2",
    "title": "Near the Door",
    "focusSounds": [
      "ear",
      "oor"
    ],
    "status": "ready",
    "storyFileId": "5_2",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L7/5_2_near_the_door/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L7/5_2_near_the_door/01_spelling_ear.pdf",
            "title": "Spell ear words",
            "thumb": "/worksheets/L7/5_2_near_the_door/01_spelling_ear.png",
            "objective": "Choose the right spelling for the ear sound and use it."
          },
          {
            "href": "/worksheets/L7/5_2_near_the_door/02_fluency_ear.pdf",
            "title": "Fluency: ear",
            "thumb": "/worksheets/L7/5_2_near_the_door/02_fluency_ear.png",
            "objective": "Read ear words quickly and accurately."
          },
          {
            "href": "/worksheets/L7/5_2_near_the_door/03_spelling_oor.pdf",
            "title": "Spell oor words",
            "thumb": "/worksheets/L7/5_2_near_the_door/03_spelling_oor.png",
            "objective": "Choose the right spelling for the oor sound and use it."
          },
          {
            "href": "/worksheets/L7/5_2_near_the_door/04_fluency_oor.pdf",
            "title": "Fluency: oor",
            "thumb": "/worksheets/L7/5_2_near_the_door/04_fluency_oor.png",
            "objective": "Read oor words quickly and accurately."
          },
          {
            "href": "/worksheets/L7/5_2_near_the_door/05_sentences_ear.pdf",
            "title": "Read ear in sentences",
            "thumb": "/worksheets/L7/5_2_near_the_door/05_sentences_ear.png",
            "objective": "Read and complete sentences that use the sound ear."
          },
          {
            "href": "/worksheets/L7/5_2_near_the_door/06_game_ear.pdf",
            "title": "Story game: Near the Door",
            "thumb": "/worksheets/L7/5_2_near_the_door/06_game_ear.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l7-5_3_sure_she_can",
    "bookNumber": "7.3",
    "title": "Sure She Can!",
    "focusSounds": [
      "ure",
      "tion"
    ],
    "status": "ready",
    "storyFileId": "5_3",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L7/5_3_sure_she_can/pack.pdf",
        "bundleLabel": "Download all 5 sheets",
        "sheets": [
          {
            "href": "/worksheets/L7/5_3_sure_she_can/01_spelling_ure.pdf",
            "title": "Spell ure words",
            "thumb": "/worksheets/L7/5_3_sure_she_can/01_spelling_ure.png",
            "objective": "Choose the right spelling for the ure sound and use it."
          },
          {
            "href": "/worksheets/L7/5_3_sure_she_can/03_spelling_tion.pdf",
            "title": "Spell tion words",
            "thumb": "/worksheets/L7/5_3_sure_she_can/03_spelling_tion.png",
            "objective": "Choose the right spelling for the tion sound and use it."
          },
          {
            "href": "/worksheets/L7/5_3_sure_she_can/04_fluency_tion.pdf",
            "title": "Fluency: tion",
            "thumb": "/worksheets/L7/5_3_sure_she_can/04_fluency_tion.png",
            "objective": "Read tion words quickly and accurately."
          },
          {
            "href": "/worksheets/L7/5_3_sure_she_can/05_sentences_ure.pdf",
            "title": "Read ure in sentences",
            "thumb": "/worksheets/L7/5_3_sure_she_can/05_sentences_ure.png",
            "objective": "Read and complete sentences that use the sound ure."
          },
          {
            "href": "/worksheets/L7/5_3_sure_she_can/06_game_ure.pdf",
            "title": "Story game: Sure She Can!",
            "thumb": "/worksheets/L7/5_3_sure_she_can/06_game_ure.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l7-5_4_a_place_for_me",
    "bookNumber": "7.4",
    "title": "A Place for Me",
    "focusSounds": [
      "ire",
      "ore",
      "ear",
      "oor",
      "ure",
      "tion"
    ],
    "status": "ready",
    "storyFileId": "5_4",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L7/5_4_a_place_for_me/pack.pdf",
        "bundleLabel": "Download all 7 sheets",
        "sheets": [
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/01_assess_ire.pdf",
            "title": "Check-up: ire",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/01_assess_ire.png",
            "objective": "Show the sound ire is secure before moving on."
          },
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/02_assess_ore.pdf",
            "title": "Check-up: ore",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/02_assess_ore.png",
            "objective": "Show the sound ore is secure before moving on."
          },
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/03_assess_ear.pdf",
            "title": "Check-up: ear",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/03_assess_ear.png",
            "objective": "Show the sound ear is secure before moving on."
          },
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/04_assess_oor.pdf",
            "title": "Check-up: oor",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/04_assess_oor.png",
            "objective": "Show the sound oor is secure before moving on."
          },
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/05_assess_ure.pdf",
            "title": "Check-up: ure",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/05_assess_ure.png",
            "objective": "Show the sound ure is secure before moving on."
          },
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/06_assess_tion.pdf",
            "title": "Check-up: tion",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/06_assess_tion.png",
            "objective": "Show the sound tion is secure before moving on."
          },
          {
            "href": "/worksheets/L7/5_4_a_place_for_me/07_game_ire.pdf",
            "title": "Story game: A Place for Me",
            "thumb": "/worksheets/L7/5_4_a_place_for_me/07_game_ire.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l8-6_1_the_marvellous_neighbourhood",
    "bookNumber": "8.1",
    "title": "The Marvellous Neighbourhood",
    "focusSounds": [
      "ous"
    ],
    "status": "ready",
    "storyFileId": "6_1",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L8/6_1_the_marvellous_neighbourhood/pack.pdf",
        "bundleLabel": "Download all 4 sheets",
        "sheets": [
          {
            "href": "/worksheets/L8/6_1_the_marvellous_neighbourhood/01_spelling_ous.pdf",
            "title": "Spell ous words",
            "thumb": "/worksheets/L8/6_1_the_marvellous_neighbourhood/01_spelling_ous.png",
            "objective": "Choose the right spelling for the ous sound and use it."
          },
          {
            "href": "/worksheets/L8/6_1_the_marvellous_neighbourhood/02_wordsearch_ous.pdf",
            "title": "Word search: ous",
            "thumb": "/worksheets/L8/6_1_the_marvellous_neighbourhood/02_wordsearch_ous.png",
            "objective": "Find and read ous words fast."
          },
          {
            "href": "/worksheets/L8/6_1_the_marvellous_neighbourhood/03_sentences_ous.pdf",
            "title": "Read ous in sentences",
            "thumb": "/worksheets/L8/6_1_the_marvellous_neighbourhood/03_sentences_ous.png",
            "objective": "Read and complete sentences that use the sound ous."
          },
          {
            "href": "/worksheets/L8/6_1_the_marvellous_neighbourhood/04_game_ous.pdf",
            "title": "Story game: The Marvellous Neighbourhood",
            "thumb": "/worksheets/L8/6_1_the_marvellous_neighbourhood/04_game_ous.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l8-6_2_you_are_remarkable",
    "bookNumber": "8.2",
    "title": "You Are Remarkable",
    "focusSounds": [
      "able",
      "ible"
    ],
    "status": "ready",
    "storyFileId": "6_2",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L8/6_2_you_are_remarkable/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L8/6_2_you_are_remarkable/01_spelling_able.pdf",
            "title": "Spell able words",
            "thumb": "/worksheets/L8/6_2_you_are_remarkable/01_spelling_able.png",
            "objective": "Choose the right spelling for the able sound and use it."
          },
          {
            "href": "/worksheets/L8/6_2_you_are_remarkable/02_wordsearch_able.pdf",
            "title": "Word search: able",
            "thumb": "/worksheets/L8/6_2_you_are_remarkable/02_wordsearch_able.png",
            "objective": "Find and read able words fast."
          },
          {
            "href": "/worksheets/L8/6_2_you_are_remarkable/03_spelling_ible.pdf",
            "title": "Spell ible words",
            "thumb": "/worksheets/L8/6_2_you_are_remarkable/03_spelling_ible.png",
            "objective": "Choose the right spelling for the ible sound and use it."
          },
          {
            "href": "/worksheets/L8/6_2_you_are_remarkable/04_wordsearch_ible.pdf",
            "title": "Word search: ible",
            "thumb": "/worksheets/L8/6_2_you_are_remarkable/04_wordsearch_ible.png",
            "objective": "Find and read ible words fast."
          },
          {
            "href": "/worksheets/L8/6_2_you_are_remarkable/05_sentences_able.pdf",
            "title": "Read able in sentences",
            "thumb": "/worksheets/L8/6_2_you_are_remarkable/05_sentences_able.png",
            "objective": "Read and complete sentences that use the sound able."
          },
          {
            "href": "/worksheets/L8/6_2_you_are_remarkable/06_game_able.pdf",
            "title": "Story game: You Are Remarkable",
            "thumb": "/worksheets/L8/6_2_you_are_remarkable/06_game_able.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l8-6_3_it_looks_suspicious",
    "bookNumber": "8.3",
    "title": "It Looks Suspicious!",
    "focusSounds": [
      "cious",
      "tious"
    ],
    "status": "ready",
    "storyFileId": "6_3",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L8/6_3_it_looks_suspicious/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L8/6_3_it_looks_suspicious/01_spelling_cious.pdf",
            "title": "Spell cious words",
            "thumb": "/worksheets/L8/6_3_it_looks_suspicious/01_spelling_cious.png",
            "objective": "Choose the right spelling for the cious sound and use it."
          },
          {
            "href": "/worksheets/L8/6_3_it_looks_suspicious/02_wordsearch_cious.pdf",
            "title": "Word search: cious",
            "thumb": "/worksheets/L8/6_3_it_looks_suspicious/02_wordsearch_cious.png",
            "objective": "Find and read cious words fast."
          },
          {
            "href": "/worksheets/L8/6_3_it_looks_suspicious/03_spelling_tious.pdf",
            "title": "Spell tious words",
            "thumb": "/worksheets/L8/6_3_it_looks_suspicious/03_spelling_tious.png",
            "objective": "Choose the right spelling for the tious sound and use it."
          },
          {
            "href": "/worksheets/L8/6_3_it_looks_suspicious/04_wordsearch_tious.pdf",
            "title": "Word search: tious",
            "thumb": "/worksheets/L8/6_3_it_looks_suspicious/04_wordsearch_tious.png",
            "objective": "Find and read tious words fast."
          },
          {
            "href": "/worksheets/L8/6_3_it_looks_suspicious/05_sentences_cious.pdf",
            "title": "Read cious in sentences",
            "thumb": "/worksheets/L8/6_3_it_looks_suspicious/05_sentences_cious.png",
            "objective": "Read and complete sentences that use the sound cious."
          },
          {
            "href": "/worksheets/L8/6_3_it_looks_suspicious/06_game_cious.pdf",
            "title": "Story game: It Looks Suspicious!",
            "thumb": "/worksheets/L8/6_3_it_looks_suspicious/06_game_cious.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l8-6_4_the_incredible_bush_walk",
    "bookNumber": "8.4",
    "title": "The Incredible Bush Walk",
    "focusSounds": [
      "ous",
      "able",
      "ible",
      "cious",
      "tious"
    ],
    "status": "ready",
    "storyFileId": "6_4",
    "groups": [
      {
        "label": "Worksheets",
        "bundleHref": "/worksheets/L8/6_4_the_incredible_bush_walk/pack.pdf",
        "bundleLabel": "Download all 6 sheets",
        "sheets": [
          {
            "href": "/worksheets/L8/6_4_the_incredible_bush_walk/01_assess_ous.pdf",
            "title": "Check-up: ous",
            "thumb": "/worksheets/L8/6_4_the_incredible_bush_walk/01_assess_ous.png",
            "objective": "Show the sound ous is secure before moving on."
          },
          {
            "href": "/worksheets/L8/6_4_the_incredible_bush_walk/02_assess_able.pdf",
            "title": "Check-up: able",
            "thumb": "/worksheets/L8/6_4_the_incredible_bush_walk/02_assess_able.png",
            "objective": "Show the sound able is secure before moving on."
          },
          {
            "href": "/worksheets/L8/6_4_the_incredible_bush_walk/03_assess_ible.pdf",
            "title": "Check-up: ible",
            "thumb": "/worksheets/L8/6_4_the_incredible_bush_walk/03_assess_ible.png",
            "objective": "Show the sound ible is secure before moving on."
          },
          {
            "href": "/worksheets/L8/6_4_the_incredible_bush_walk/04_assess_cious.pdf",
            "title": "Check-up: cious",
            "thumb": "/worksheets/L8/6_4_the_incredible_bush_walk/04_assess_cious.png",
            "objective": "Show the sound cious is secure before moving on."
          },
          {
            "href": "/worksheets/L8/6_4_the_incredible_bush_walk/05_assess_tious.pdf",
            "title": "Check-up: tious",
            "thumb": "/worksheets/L8/6_4_the_incredible_bush_walk/05_assess_tious.png",
            "objective": "Show the sound tious is secure before moving on."
          },
          {
            "href": "/worksheets/L8/6_4_the_incredible_bush_walk/06_game_ous.pdf",
            "title": "Story game: The Incredible Bush Walk",
            "thumb": "/worksheets/L8/6_4_the_incredible_bush_walk/06_game_ous.png",
            "objective": "Read the book's words in a race game, so practice feels like play."
          }
        ]
      }
    ]
  },
  {
    "id": "forged-l8-extras",
    "bookNumber": "L8",
    "title": "Level 8 extra sounds",
    "focusSounds": [
      "sion"
    ],
    "status": "ready",
    "storyFileId": null,
    "groups": [
      {
        "label": "Extra sounds",
        "bundleHref": "/worksheets/L8/extras/pack.pdf",
        "bundleLabel": "Download all 1 sheets",
        "sheets": [
          {
            "href": "/worksheets/L8/extras/01_spelling_sion.pdf",
            "title": "Spell sion words",
            "thumb": "/worksheets/L8/extras/01_spelling_sion.png",
            "objective": "Choose the right spelling for the sion sound and use it."
          }
        ]
      }
    ]
  }
];
